### ISSUE TITLE
Configuring a theme

### ISSUE THREAD

**Issue by RooneyTu** [trntv/yii2-starter-kit#100]
Pls help me configuring a new theme.
I've gone through the steps in the guide:
'components' => [
    'view' => [
        'theme' => [
            'pathMap' => ['@app/views' => '@app/themes/basic'],
            'baseUrl' => '@web/themes/basic',
        ],
    ],
], 
however don't working.

**Comment by trntv** [comment]
Provide more information. Where did you paste this code? ``@app`` alias represents folder of current running application, are you sure you theme is in the right place?
