### ISSUE TITLE
csrf errors on shared hosting

### ISSUE THREAD

**Issue by dev6** [trntv/yii2-starter-kit#102]
Very good starter kit, only thing I would suggest is to use improved advanced template instead of the regular advanced template from Yii. This works for all kind of environments and good file structure.

Faced Bad Request (#400) when tried to updated anything from the backend. It is resolvable by disabling the csrf tokens but not a satisfied solution for me. Any other ideas of how I can resolve this issue?

**Comment by trntv** [comment]
don't face this problem. Can you give more information? CSRF tokens work? Is there <meta name="csrf-token"> in <head>? Is it matches token in your session? Does your forms have  csrf token hidden input?

**Comment by dev6** [comment]
I faced this error when i moved my app from localhost to remote server which is only a shared hosting. To get the proper url, I moved the web folder of frontend app to root folder of the website and the web folder of backend app to the admin folder.

But once I did this, a Bad Request (#400) with message 'Unable to verify your data submission.' error started showing up whenever I was trying to update anything from the backend. This was because of the CSRF tokens in ajax controller. Once i disabled them in all the controllers, this error doesnt show up.

**Comment by trntv** [comment]
Are backend and frontend apps work on the same domain now? If so, this is the problem.

**Comment by dev6** [comment]
Yes they are working on the same domain. And the workaround for it was later found here: https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-shared-hosting.md
The part where it is stated to change the config file of backend, is what helped me out to clear the error on my host. But the same setting didnt help me on my localhost. I guess that is pretty obvious.

Hope it helps to anyone else who is looking for a solution in this situation.

Amazing framework and a very good starter kit.

**Comment by trntv** [comment]
Glad to hear you've solved your problem. Good luck.
