### ISSUE TITLE
php console/yii migrate showing error

### ISSUE THREAD

**Issue by mohdbashir** [trntv/yii2-starter-kit#103]
I have successfully created the project. But when i am running the below migrate command it is showing error:

F:\xampp\htdocs\yii2-starter-kit>php console/yii migrate

Warning: require(F:\xampp\htdocs\yii2-starter-kit\console/../vendor/autoload.php
): failed to open stream: No such file or directory in F:\xampp\htdocs\yii2-star
ter-kit\console\yii on line 8

Fatal error: require(): Failed opening required 'F:\xampp\htdocs\yii2-starter-ki
t\console/../vendor/autoload.php' (include_path='.;F:\xampp\php\PEAR') in F:\xam
pp\htdocs\yii2-starter-kit\console\yii on line 8

**Comment by trntv** [comment]
```
composer global require "fxp/composer-asset-plugin"
```

then, in project root
```
composer install
```

**Comment by mohdbashir** [comment]
I have installed the project by composer using the command:- 
php composer.phar global require "fxp/composer-asset-plugin"

Please suggest how i can resolve the issue.

**Comment by trntv** [comment]
Is ``composer-asset-plugin`` installed? What version is it? Did't you try to manually install composer dependencies in project root folder? Do you know what composer is?

**Comment by mohdbashir** [comment]
Actually i was skip the first command[ php composer.phar global require "fxp/composer-asset-plugin" ].

Now it is installed but at home page it is showing error: 
symlink(): Cannot create symlink, error code(1314)

**Comment by mohdbashir** [comment]
Now it is running.
i have false the linkAssets in config/web.php

Thank u so mush for your supprot.
