### ISSUE TITLE
Can you suggest me the step to use mongodb with the yii2-starter-kit

### ISSUE THREAD

**Issue by mohdbashir** [trntv/yii2-starter-kit#104]
To use mongodb as a database, we have installed extension with command:- 
composer require --prefer-dist yiisoft/yii2-mongodb "*"

In common/config/base.php , i have added below line of code:
'mongodb' => [           
	 'class' => 'yii\mongodb\Connection',           
	 'dsn' => 'mongodb://dblogin:dbpwd@localhost:27017/redealnew',			         
	],

But it is showing error:-  "ReflectionException
Class db does not exist

    1. in F:\xampp\htdocs\redealnew\trunk\vendor\yiisoft\yii2\di\Container.php at line 415
    2. in F:\xampp\htdocs\redealnew\trunk\vendor\yiisoft\yii2\di\Container.php – ReflectionClass::__construct('db') at line 415
    3. in F:\xampp\htdocs\redealnew\trunk\vendor\yiisoft\yii2\di\Container.php – yii\di\Container::getDependencies('db') at line 358
    4. in F:\xampp\htdocs\redealnew\trunk\vendor\yiisoft\yii2\di\Container.php – yii\di\Container::build('db', [], []) at line 151
    5. in F:\xampp\htdocs\redealnew\trunk\vendor\yiisoft\yii2\di\Instance.php – yii\di\Container::get('db') at line 154
    6. in F:\xampp\htdocs\redealnew\trunk\vendor\yiisoft\yii2\di\Instance.php – yii\di\Instance::get(null) at line 128
    7. in F:\xampp\htdocs\redealnew\trunk\vendor\yiisoft\yii2\log\DbTarget.php – yii\di\Instance::ensure('db', 'yii\db\Connection') at line 55
    8. in F:\xampp\htdocs\redealnew\trunk\vendor\yiisoft\yii2\base\Object.php – yii\log\DbTarget::init() at line 10"

Please suggest how to integrate the mongodb with this project( YII2-starter-kit).

**Comment by trntv** [comment]
> Please suggest how to integrate the mongodb with this project( YII2-starter-kit).
The same way as in any other yii app. Show me full config.

**Comment by mohdbashir** [comment]
First of all i would like to thanks to make such type of project for developer to start the application.

I just want to know have you any guide to implement the mongodb for http://yii2-starter-kit.terentev.net
Actually i have to use the mongodb as a database. Can we do with built kit by you - http://yii2-starter-kit.terentev.net

Please suggest.

**Comment by trntv** [comment]
this kit is fully compatible with yii2, because it works on top of it. All yii2 docs fit to it:
https://github.com/yiisoft/yii2/blob/master/docs/guide/concept-configurations.md
https://github.com/yiisoft/yii2-mongodb
https://github.com/yiisoft/yii2/blob/master/docs/guide/db-active-record.md
