### ISSUE TITLE
Disable debug mode

### ISSUE THREAD

**Issue by svolga** [trntv/yii2-starter-kit#105]
How to disable debug mode? In the root is .env file with rows:
YII_DEBUG   = true
YII_ENV     = dev

If I wrote 
YII_DEBUG   = false 

in the common/config/web.php file 
this condition still work
if(YII_DEBUG){

}

Thanks in advance for help.

**Comment by trntv** [comment]
can't reproduce. How did you install kit? ``git clone`` or ``composer create-project``?

**Comment by xed** [comment]
I have some problem or bug, when i edit .env file.
my solution, reinitialese app ./init

2015-02-27 23:53 GMT+03:00 Eugene Terentev <notifications@github.com>:

**Comment by trntv** [comment]
@svolga if you have any information - reopen this issue.
