### ISSUE TITLE
Calling unknown method: yii\web\UrlManager::addRules()

### ISSUE THREAD

**Issue by nakarin4350** [trntv/yii2-starter-kit#106]
After composer update,I got this error Calling unknown method: yii\web\UrlManager::addRules().

**Comment by trntv** [comment]
provide more info. Where you got this error? Stacktrace?

**Comment by nakarin4350** [comment]
Unknown Method – yii\base\UnknownMethodException
Calling unknown method: yii\web\UrlManager::addRules()

    1. in /var/www/html/donation2/vendor/yiisoft/yii2/base/Component.php at line 285
    2. in /var/www/html/donation2/vendor/yiisoft/yii2-debug/Module.php – yii\base\Component::__call() at line 128
    3. in /var/www/html/donation2/vendor/yiisoft/yii2-debug/Module.php – yii\web\UrlManager::addRules() at line 128
    4. in /var/www/html/donation2/vendor/yiisoft/yii2/base/Application.php – yii\debug\Module::bootstrap() at line 294
    5. in /var/www/html/donation2/vendor/yiisoft/yii2/web/Application.php – yii\base\Application::bootstrap() at line 62
    6. in /var/www/html/donation2/vendor/yiisoft/yii2/base/Application.php – yii\web\Application::bootstrap() at line 251
    7. in /var/www/html/donation2/vendor/yiisoft/yii2/base/Object.php – yii\base\Application::init() at line 106
    8. in /var/www/html/donation2/vendor/yiisoft/yii2/base/Application.php – yii\base\Object::__construct() at line 190
    9. in /var/www/html/donation2/frontend/web/index.php – yii\base\Application::__construct() at line 32

**Comment by trntv** [comment]
hm. is composer-asset-plugin installed?

**Comment by nakarin4350** [comment]
yes,composer-asset-plugin is installed.

**Comment by trntv** [comment]
What are your yii2 and yii2-starter-kit versions (commits) ?

**Comment by nakarin4350** [comment]
I try to install latest yii2-stater-kit.This is my step
1.git clone https://github.com/trntv/yii2-starter-kit.git
2.run ./init (in dev mode)
3.edit environment/dev/.env (provide my db 's username and password)
4.php console/yii migrate
Exception 'yii\db\Exception' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)'
but I do provide db' s username and password.

**Comment by trntv** [comment]
3. ``environment/dev/.env`` is template. Should edit .env located in
project root.

2015-03-05 8:14 GMT+02:00 nakarin4350 <notifications@github.com>:

**Comment by nakarin4350** [comment]
It works now,thanks for your help.
