### ISSUE TITLE
Call to a member function load() on a non-object.

### ISSUE THREAD

**Issue by nakarin4350** [trntv/yii2-starter-kit#110]
After I log in using  facebook and I click profile,I got this error "Call to a member function load() on a non-object".

1. in /var/www/html/donation2/frontend/modules/user/controllers/DefaultController.php at line 75
2. in /var/www/html/donation2/vendor/yiisoft/yii2/base/InlineAction.php – call_user_func_array() at line 55
3. in /var/www/html/donation2/vendor/yiisoft/yii2/base/Controller.php – yii\base\InlineAction::runWithParams() at line 151
4. in /var/www/html/donation2/vendor/yiisoft/yii2/base/Module.php – yii\base\Controller::runAction() at line 455
5. in /var/www/html/donation2/vendor/yiisoft/yii2/web/Application.php – yii\base\Module::runAction() at line 83
6. in /var/www/html/donation2/vendor/yiisoft/yii2/base/Application.php – yii\web\Application::handleRequest() at line 375
7. in /var/www/html/donation2/frontend/web/index.php – yii\base\Application::run() at line 2

**Comment by nakarin4350** [comment]
I try to reapply migration(php console/yii migrate) then I try to log in using facebook,but I got this error.
"common\models\User has no relation named "profile".
Caused by: Unknown Method – yii\base\UnknownMethodException
Calling unknown method: common\models\User::getprofile()

in /var/www/html/donation2/vendor/yiisoft/yii2/base/Component.php at line 282
"


1. in /var/www/html/donation2/vendor/yiisoft/yii2/db/BaseActiveRecord.php at line 1103
2. in /var/www/html/donation2/vendor/yiisoft/yii2/db/BaseActiveRecord.php – yii\db\BaseActiveRecord::getRelation('profile') at line 1153
3. in /var/www/html/donation2/common/models/User.php – yii\db\BaseActiveRecord::link('profile', common\models\UserProfile) at line 270
4. in /var/www/html/donation2/frontend/modules/user/controllers/SignInController.php – common\models\User::afterSignup() at line 171
5. frontend\modules\user\controllers\SignInController::successOAuthCallback(yii\authclient\clients\Facebook)
6. in /var/www/html/donation2/vendor/yiisoft/yii2-authclient/AuthAction.php – call_user_func([frontend\modules\user\controllers\SignInController, 'successOAuthCallback'], yii\authclient\clients\Facebook) at line 212
7. in /var/www/html/donation2/vendor/yiisoft/yii2-authclient/AuthAction.php – yii\authclient\AuthAction::authSuccess(yii\authclient\clients\Facebook) at line 361
8. in /var/www/html/donation2/vendor/yiisoft/yii2-authclient/AuthAction.php – yii\authclient\AuthAction::authOAuth2(yii\authclient\clients\Facebook) at line 193
9. in /var/www/html/donation2/vendor/yiisoft/yii2-authclient/AuthAction.php – yii\authclient\AuthAction::auth(yii\authclient\clients\Facebook) at line 177
10. yii\authclient\AuthAction::run()

**Comment by nakarin4350** [comment]
I think "$this->link('profile', $profile);" should be "$this->link('userProfile', $profile);".

**Comment by trntv** [comment]
thank you
