### ISSUE TITLE
Only last saved/updated article has attachments

### ISSUE THREAD

**Issue by hcharly** [trntv/yii2-starter-kit#111]
Hi @trntv,
Thanks for the great job you're doing.
While saving or updating any article, all previous attachments are removed from article_attachment.
With the following fix in common/models/Article.php (line 167) it works:
```
/* BOF - fixed a bug where only the latest Article has ArticleAttachment
ArticleAttachment::deleteAll(['not in', 'url', $this->attachments]);
*/
ArticleAttachment::deleteAll(['and', 'article_id = :id', ['not in', 'url', $this->attachments]], [':id' => $this->id]);
// EOF - fixed a bug where only the latest Article has ArticleAttachment
```
Please give it a look to check if it is good for you.
Regards

**Comment by trntv** [comment]
Thanks for report. It's all about a lack of time and tests...
