### ISSUE TITLE
The requested PHP extension ext-intl * is missing from your system

### ISSUE THREAD

**Issue by ksetrin** [trntv/yii2-starter-kit#112]
Делал по инструкции, с помощью композера создал проект, затем запустил composer install и в итоге получил 
C:\xampp\htdocs\trntvyii2starter>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Reading bower.json of bower-asset/jquery (2.1.3)
Reading bower.json of bower-asset/jquery (2.1.2)
Reading bower.json of bower-asset/jquery (2.1.1)
Reading bower.json of bower-asset/jquery (2.1.0)
Reading bower.json of bower-asset/jquery (1.11.2)
Reading bower.json of bower-asset/jquery (1.11.1)
Reading bower.json of bower-asset/jquery (1.11.0)
Reading bower.json of bower-asset/jquery.inputmask (3.1.61)
Reading bower.json of bower-asset/jquery.inputmask (3.1.60)
Reading bower.json of bower-asset/jquery.inputmask (3.1.59)
Reading bower.json of bower-asset/jquery.inputmask (3.1.58)
Reading bower.json of bower-asset/jquery.inputmask (3.1.57)
Reading bower.json of bower-asset/jquery.inputmask (3.1.56)
Reading bower.json of bower-asset/jquery.inputmask (3.1.55)
Reading bower.json of bower-asset/jquery.inputmask (3.1.54)
Reading bower.json of bower-asset/jquery.inputmask (3.1.53)
Reading bower.json of bower-asset/jquery.inputmask (3.1.52)
Reading bower.json of bower-asset/jquery.inputmask (3.1.51)
Reading bower.json of bower-asset/jquery.inputmask (3.1.50)
Reading bower.json of bower-asset/jquery.inputmask (3.1.49)
Reading bower.json of bower-asset/jquery.inputmask (3.1.48)
Reading bower.json of bower-asset/jquery.inputmask (3.1.47)
Reading bower.json of bower-asset/jquery.inputmask (3.1.46)
Reading bower.json of bower-asset/jquery.inputmask (3.1.45)
Reading bower.json of bower-asset/jquery.inputmask (3.1.44)
Reading bower.json of bower-asset/jquery.inputmask (3.1.43)
Reading bower.json of bower-asset/jquery.inputmask (3.1.42)
Reading bower.json of bower-asset/jquery.inputmask (3.1.41)
Reading bower.json of bower-asset/jquery.inputmask (3.1.40)
Reading bower.json of bower-asset/jquery.inputmask (3.1.39)
Reading bower.json of bower-asset/jquery.inputmask (3.1.38)
Reading bower.json of bower-asset/jquery.inputmask (3.1.37)
Reading bower.json of bower-asset/jquery.inputmask (3.1.36)
Reading bower.json of bower-asset/jquery.inputmask (3.1.35)
Reading bower.json of bower-asset/jquery.inputmask (3.1.34)
Reading bower.json of bower-asset/jquery.inputmask (3.1.33)
Reading bower.json of bower-asset/jquery.inputmask (3.1.32)
Reading bower.json of bower-asset/jquery.inputmask (3.1.31)
Reading bower.json of bower-asset/jquery.inputmask (3.1.30)
Reading bower.json of bower-asset/jquery.inputmask (3.1.29)
Reading bower.json of bower-asset/jquery.inputmask (3.1.28)
Reading bower.json of bower-asset/jquery.inputmask (3.1.27)
Reading bower.json of bower-asset/jquery.inputmask (3.1.26)
Reading bower.json of bower-asset/jquery.inputmask (3.1.25)
Reading bower.json of bower-asset/jquery.inputmask (3.1.24)
Reading bower.json of bower-asset/jquery.inputmask (3.1.23)
Reading bower.json of bower-asset/jquery.inputmask (3.1.22)
Reading bower.json of bower-asset/jquery.inputmask (3.1.21)
Reading bower.json of bower-asset/jquery.inputmask (3.1.15)
Reading bower.json of bower-asset/jquery.inputmask (3.1.14)
Reading bower.json of bower-asset/jquery.inputmask (3.1.13)
Reading bower.json of bower-asset/jquery.inputmask (3.1.12)
Reading bower.json of bower-asset/jquery.inputmask (3.1.0)
Reading bower.json of bower-asset/punycode (v1.3.2)
Reading bower.json of bower-asset/punycode (v1.3.1)
Reading bower.json of bower-asset/punycode (v1.3.0)
Reading bower.json of bower-asset/yii2-pjax (v2.0.4)
Reading bower.json of bower-asset/yii2-pjax (v2.0.3)
Reading bower.json of bower-asset/yii2-pjax (v2.0.2)
Reading bower.json of bower-asset/yii2-pjax (v2.0.1)
Reading bower.json of bower-asset/bootstrap (v3.2.0)
Reading bower.json of bower-asset/bootstrap (v3.1.1)
Reading bower.json of bower-asset/bootstrap (v3.1.0)
Reading bower.json of bower-asset/bootstrap (v3.3.2)
Reading bower.json of bower-asset/bootstrap (v3.3.1)
Reading bower.json of bower-asset/bootstrap (v3.3.0)
Reading bower.json of bower-asset/jquery-ui (1.11.4)
Reading bower.json of bower-asset/jquery-ui (1.11.3)
Reading bower.json of bower-asset/jquery-ui (1.11.2)
Reading bower.json of bower-asset/jquery-ui (1.11.1)
Reading bower.json of bower-asset/jquery-ui (1.11.0)
Reading bower.json of bower-asset/ace-builds (v1.1.8)
Reading bower.json of bower-asset/jquery (2.0.3)
Reading bower.json of bower-asset/jquery (2.0.2)
Reading bower.json of bower-asset/jquery (2.0.1)
Reading bower.json of bower-asset/jquery (2.0.0)
Reading bower.json of bower-asset/jquery (1.10.2)
Reading bower.json of bower-asset/jquery (1.10.1)
Reading bower.json of bower-asset/jquery (1.10.0)
Reading bower.json of bower-asset/jquery (1.9.1)
Reading bower.json of bower-asset/jquery (1.9.0)
Reading bower.json of bower-asset/jquery (1.8.3)
Reading bower.json of bower-asset/jquery (1.8.2)
Reading bower.json of bower-asset/jquery (1.8.1)
Reading bower.json of bower-asset/jquery (1.8.0)
Reading bower.json of bower-asset/jquery (1.7.2)
Reading bower.json of bower-asset/jquery (1.7.1)
Reading bower.json of bower-asset/jquery (1.7.0)
Reading bower.json of bower-asset/jquery (1.6.4)
Reading bower.json of bower-asset/jquery (1.6.3)
Reading bower.json of bower-asset/jquery (1.6.2)
Reading bower.json of bower-asset/jquery (1.6.1)
Reading bower.json of bower-asset/jquery (1.6.0)
Reading bower.json of bower-asset/admin-lte (v1.2.1)
Reading bower.json of bower-asset/font-awesome (v4.3.0)
Reading bower.json of bower-asset/font-awesome (v4.2.0)
Reading bower.json of bower-asset/font-awesome (v4.1.0)
Reading bower.json of bower-asset/font-awesome (v4.0.3)
Reading bower.json of bower-asset/font-awesome (v4.0.2)
Reading bower.json of bower-asset/font-awesome (v4.0.1)
Reading bower.json of bower-asset/font-awesome (v4.0.0)
Reading bower.json of bower-asset/icheck (1.0.2)
Reading bower.json of bower-asset/icheck (1.0.1)
Reading bower.json of bower-asset/admin-lte (1.3.1)
Reading bower.json of bower-asset/admin-lte (1.3.0)
Reading bower.json of bower-asset/admin-lte (1.2)
Reading bower.json of bower-asset/admin-lte (1.1)
Reading bower.json of bower-asset/admin-lte (1.0)
Reading bower.json of bower-asset/html5shiv (3.7.2)
Reading bower.json of bower-asset/html5shiv (3.7.1)
Reading bower.json of bower-asset/html5shiv (3.7.0)
Reading bower.json of bower-asset/html5shiv (3.6.2)
Reading bower.json of bower-asset/html5shiv (3.6.1)
Reading bower.json of bower-asset/html5shiv (3.6)
Reading bower.json of bower-asset/html5shiv (3.5)
Reading bower.json of bower-asset/html5shiv (3.4)
Reading bower.json of bower-asset/html5shiv (3.3)
Reading bower.json of bower-asset/html5shiv (3.2)
Reading bower.json of bower-asset/html5shiv (3.1)
Reading bower.json of bower-asset/flot (v0.8.3)
Reading bower.json of bower-asset/flot (v0.8.2)
Reading bower.json of bower-asset/flot (v0.8.1)
Reading bower.json of bower-asset/flot (v0.8.0)
Reading bower.json of bower-asset/typeahead.js (v0.10.5)
Reading bower.json of bower-asset/typeahead.js (v0.10.4)
Reading bower.json of bower-asset/typeahead.js (v0.10.3)
Reading bower.json of bower-asset/typeahead.js (v0.10.2)
Reading bower.json of bower-asset/typeahead.js (v0.10.1)
Reading bower.json of bower-asset/typeahead.js (v0.10.0)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-intl * is missing from your system.

Далее установка не происходит, папку vendor не создает, и как следствие сыпятся ошибки:

Warning: require(C:\xampp\htdocs\trntvyii2starter\frontend\web/../../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\trntvyii2starter\frontend\web\index.php on line 3

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\trntvyii2starter\frontend\web/../../vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\trntvyii2starter\frontend\web\index.php on line 3

До этого устанавливал официальные темплейты от Yii - прекрасно работают. Подскажите, как решить такую неловкость начинающему программисту :)

**Comment by ksetrin** [comment]
Удалил строку "ext-intl": "*", из composer.json и ошибки не произошло при установке
Все установилось, папка с проектом весит 104 мб. Не перебор для приложения "starter-kit" ?

**Comment by ksetrin** [comment]
Все сделал по инструкции. Теперь проблема в следующем
PHP Warning – yii\base\ErrorException
symlink(): Cannot create symlink, error code(1314)
Нашел решение: http://php.net/manual/ru/function.symlink.php#115152
повторил установку заново под админом, не помогло...

**Comment by Beaten-Sect0r** [comment]
>Удалил строку "ext-intl": "*", из composer.json и ошибки не произошло при установке
Откройте свой php.ini и раскомментируйте extension=php_intl.dll - это расширение нужно для работы фреймворка.
>Все установилось, папка с проектом весит 104 мб. Не перебор для приложения "starter-kit" ?
Это содержимое папки vendor, а не yii2-starter-kit и всё равно не перебор.

**Comment by ksetrin** [comment]
Beaten-Sect0r, да благодарю за подсказку. Вернул, строчку и раскомментировал php_intl.dll
Проблема была действительно в админских правах

**Comment by trntv** [comment]
> trntv, может вернуть requirements.php в набор?
пожалуй стоит, лично мне он никогда не нужен был, но зато вот такие вот вопросы возникать не будут.

**Comment by trntv** [comment]
Вообщем, requirements.php нам не нужен, так как ошибка в первом посте возникла именно на этапе проверки системы под требования. Так что по сути без разницы, где система не проходит проверку, в композере или в отдельном инструменте для этого.
