### ISSUE TITLE
Compress asset 

### ISSUE THREAD

**Issue by jomonkj** [trntv/yii2-starter-kit#113]
Compress all css and js files into one file. site need to optimize loading speed

**Comment by trntv** [comment]
This is an application template, not a cms or ready-to-use app. You can optimize loading speed in any way you want.

**Comment by jomonkj** [comment]
can create console for compressing asset?

**Comment by alladas** [comment]
@jomonkj 
I am facing the same question as yours.
My first attempts of combining and compressing assets:
* yii asset/template assets.php generates the template
* yii asset assets.php config/assets-prod.php => creates the js and css file 
* pointing bundles to assets-prod.php => the whole site failed to load with an error
**Object of class 'vendor\path\xxxAssets' could not be converted to string** on all assets class.

I am trying to understand but not sure I am in the right direction.
So wondering if you have succeeded in your case and how.
Hope you don't care to share your experience on this.
In advance Thanks.
