### ISSUE TITLE
Error When login as administrator

### ISSUE THREAD

**Issue by jomonkj** [trntv/yii2-starter-kit#114]
I created a new user from `webmaster` account . username : `administrator` password : `administrator`.
with status active. when log in All pages shows internal server error.

**Comment by trntv** [comment]
>  It shows 500 error not 403 error
Where?

**Comment by jomonkj** [comment]
sorry. i edited issue

**Comment by trntv** [comment]
Thank you for report!

**Comment by nizarhunzai** [comment]
I have the same problem. When I log in using webmaster there is forbidden 403 error?

**Comment by davidjeddy** [comment]
Any other information you can provide? Configuration, etc.
Tried this on a clean install of master (0aed0b1a1fe7e6ecddcc5872e6ac6ca0da02e725) with subdomain + docker:

![screen shot 2017-05-11 at 5 41 27 pm](https://cloud.githubusercontent.com/assets/6232455/25973263/548548ca-3671-11e7-98a8-57ea05c5a2da.png)

![screen shot 2017-05-11 at 5 41 35 pm](https://cloud.githubusercontent.com/assets/6232455/25973267/572ecdf8-3671-11e7-8ee3-102e628cd627.png)

![screen shot 2017-05-11 at 5 42 12 pm](https://cloud.githubusercontent.com/assets/6232455/25973269/59ab5768-3671-11e7-9806-b85c20e70fec.png)

![screen shot 2017-05-11 at 5 42 18 pm](https://cloud.githubusercontent.com/assets/6232455/25973271/5be35454-3671-11e7-8380-4a6b090c5469.png)

![screen shot 2017-05-11 at 5 42 25 pm](https://cloud.githubusercontent.com/assets/6232455/25973273/5dfd5316-3671-11e7-9706-de63048b2be8.png)

If it makes you feel any better, I have a different log in issue as well...
