### ISSUE TITLE
htaccess 

### ISSUE THREAD

**Issue by zqrt** [trntv/yii2-starter-kit#115]
Can i use .htaccess instead of nginx ?

**Comment by zqrt** [comment]
i solve it

**Comment by jackg0h** [comment]
How do you solve it ?

**Comment by GrandMasterX** [comment]
How do you solve it ? :)

**Comment by snapget** [comment]
How do you solve it ?

**Comment by trntv** [comment]
This is a tutorial for Yii1 but it is still compatible with Yii2:
http://www.yiiframework.com/doc/guide/1.1/en/quickstart.apache-nginx-config
