### ISSUE TITLE
Статьи (frontend)

### ISSUE THREAD

**Issue by woffpost** [trntv/yii2-starter-kit#117]
Привет, установил себе сборку, очень нравится. Подскажи пожалуйста что делаю не так: создал категорию статей, создал статью, заполнил все поля и указал категорию, публикую, в админке числится в списке статей, на "морде" - нет её (пишут список статей пуст :( ).

Ну и второй вопрос - хотел бы добавить новый тип материала, и выводить последние публикации на главной..по мануалу с оф. сайта создал с помощью CRUD, а выводить как - пока не могу понять

**Comment by trntv** [comment]
1) Ну как минимум надо проверить дату публикации и стоит ли галочка "Published"
2)  Тут я ничем помочь не могу, придется учиться

**Comment by woffpost** [comment]
1 - стоит галочка, новость стала выводиться в списке статей, но теперь, при заходе на неё, выводится ошибка
"Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: common\models\ArticleAttachment::url"

2. Понял, буду учиться, спасибо :)

P.S. сборка получилась классная

**Comment by trntv** [comment]
> Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: common\models\ArticleAttachment::url
