### ISSUE TITLE
php console/yii migrate

### ISSUE THREAD

**Issue by arslanbutt** [trntv/yii2-starter-kit#120]
When I am going to migrate using this command "php console/yii migrate" I am getting the following error

Fatal Error: Class Dotenv not found 

![error](https://cloud.githubusercontent.com/assets/8137145/7001453/592ead56-dc52-11e4-9929-4f3afad5bbe8.png)

**Comment by trntv** [comment]
Did you install composer packages?

**Comment by arslanbutt** [comment]
Yes I install composer package


BEST REGARDS

Arslan Butt
about.me/arslanbutt
 [image: Arslan Butt on about.me]
Computer (Software) Engineer
Cell: +92 346 4620044 (UTC +5:00)
Skype: engr.arslanbutt
Email: engr.arslanbutt@gmail.com

<http://www.linkedin.com/in/engrarslanbutt>
<https://twitter.com/engr_arslanbutt>
<https://plus.google.com/+ArslanButt786>

    <http://about.me/arslanbutt>






   <http://about.me/arslanbutt>




    <http://about.me/arslanbutt>  <http://google.com/+ArslanButt786>



    <http://about.me/arslanbutt>
------------------------------

**Comment by trntv** [comment]
is there a ``vlucas/phpdotenv`` directory in your ``vendor`` folder?

**Comment by arslanbutt** [comment]
No such directory in the vendor folder

**Comment by trntv** [comment]
```
composer global require "fxp/composer-asset-plugin"
composer update
```
