### ISSUE TITLE
Class 'trntv\filekit\widget\SingleFileUpload' not found

### ISSUE THREAD

**Issue by Kirkan** [trntv/yii2-starter-kit#123]
Hi!
In backend, if create new widget carousel and then create item we had this error:
PHP Fatal Error – yii\base\ErrorException
Class 'trntv\filekit\widget\SingleFileUpload' not found
in C:\OpenServer\domains\localhost\ncr2\ncr2\backend\views\widget-carousel\item\_form.php
\trntv\filekit\widget\SingleFileUpload::className()
But if change SingleFileUpload to Upload work fine

**Comment by trntv** [comment]
fixed. thank you for report

**Comment by zakrot** [comment]
How do I update the project to fix problem...
