### ISSUE TITLE
Article thumbnail. How to show thumbnail in article list.

### ISSUE THREAD

**Issue by dungphanxuan** [trntv/yii2-starter-kit#127]
hello, in backend, i create new article and upload image for thumbnail. Now image saved in @storage/web/source.
In frontend, i show list of article, and article thumbnail url show path in @storage/cache
How can fix that error!

Thanks.

**Comment by trntv** [comment]
Can you provide more information?

Demo:
http://yii2-starter-kit.terentev.net/article/view?id=1

**Comment by dungphanxuan** [comment]
Hi @trntv , are you set image cache in folder @storage/cache when you upload article thumbnail.
When i upload article thumbnail, image will saved on @storage/web/source/1. But i don't see image on storage/cache folder. 
See separate: 

http://storage.yii2-starter-kit.terentev.net/source/1/RtztQp56EOnTUQ1GOTjWDNjlHSN65-JZ.jpg

http://storage.yii2-starter-kit.terentev.net/cache/1/8EaCcnrVzLuHZFt2wpD_JgkjT3qqUjUS.jpg?w=100&s=1ce207d466622fdedb6c601014f7b581

**Comment by trntv** [comment]
It is yii action (glide/index), prettyUrl is generated by UrlManager.

@storage/cache is a system folder, used by ``glide`` component, it isn't available for public.

http://storage.yii2-starter-kit.terentev.net/cache/1/8EaCcnrVzLuHZFt2wpD_JgkjT3qqUjUS.jpg?w=100&s=1ce207d466622fdedb6c601014f7b581

**Comment by dungphanxuan** [comment]
Thank @trntv . That problem. How to user glide component for outputimage after saved image?

**Comment by trntv** [comment]
It do it for you, once images has been modified and saved, glide will use it from cache.

**Comment by Vimal10** [comment]
Its show blank...

http://s15.postimg.org/j0e8867cb/Capture.png

**Comment by dungphanxuan** [comment]
@Vimal10  Just user Yii::$app->glide->getServer()->outputImage($path) component. When i put it on UploadAction once image has been saved. But error.

**Comment by Vimal10** [comment]
I got same problem..

**Comment by trntv** [comment]
1. Try to use latest code from dev-master
2. What http code application returns at http://storage.yii2-starter-kit.dev/cache/1/some-img.jpg ?

**Comment by Vimal10** [comment]
cache folder is empty :(

**Comment by trntv** [comment]
If you'll have more information (http status, error information etc) reopen it.

**Comment by Vimal10** [comment]
even in your demo script.. Thumbnail not seen. :)
http://s2.postimg.org/ca0vffxzt/Capture.png

**Comment by dungphanxuan** [comment]
@Vimal10 . you can use Glide extension. 
https://github.com/trntv/yii2-glide
iT so hard to use. I think must know about design pattern to know.

**Comment by trntv** [comment]
> even in your demo script.. Thumbnail not seen. :)
> http://s2.postimg.org/ca0vffxzt/Capture.png

i`ve forgot to update it. check now.

**Comment by dungphanxuan** [comment]
Hi @trntv , can you update that issues.
![article thumbnail](https://cloud.githubusercontent.com/assets/10725732/7230160/66845372-e795-11e4-8647-c41d31a4a7ee.JPG)

**Comment by trntv** [comment]
it is already fixed, get the latest code.

**Comment by golles** [comment]
Did anyone solve this? Article images are also not visible for me as well.
There are no files in cache folder.
Image path also looks wrong:
```
//localhost/workspace/my-website/storage/workspace/my-website/cache/1/sJILO3V2I97tdnrHJ7HGSUPGO_fEtuoY.jpg?w=100&s=66c407227d6bafd7cce247d330cb7875
```

**Comment by golles** [comment]
If I change the url manually eg:
```
http://localhost/workspace/my-website/storage/workspace/cache/1/sJILO3V2I97tdnrHJ7HGSUPGO_fEtuoY.jpg%3Fw=100&s= 66c407227d6bafd7cce247d330cb7875
```
I get: "Missing required parameters: path"

or when I change it to:
```
http://localhost/workspace/my-website/storage/cache?path=1/sJILO3V2I97tdnrHJ7HGSUPGO_fEtuoY.jpg&w=100&s= 66c407227d6bafd7cce247d330cb7875
```
I get: "Bad Request (#400)", because validate request fails

Help is appreciated.

**Comment by parich** [comment]
Article images

![2559-11-19 09 47 14](https://cloud.githubusercontent.com/assets/10128580/20452473/0af8b424-ae3d-11e6-9ef5-b67fb7cdd478.png)
