### ISSUE TITLE
Hi I want help for PretyUrl config

### ISSUE THREAD

**Issue by Vimal10** [trntv/yii2-starter-kit#128]
I changed article view with slug..
example
http://yii2-starter-kit.dev/article/view?slug=if-youll-leave-this-field-empty
but i want to be like
http://yii2-starter-kit.dev/article/view/f-youll-leave-this-field-empty

--I changed  frontend/config/_urlManager.php // But it's not working how i can change it??I am new in Yii2 :)

**Comment by trntv** [comment]
Check the commit
