### ISSUE TITLE
Exception info

### ISSUE THREAD

**Issue by svolga** [trntv/yii2-starter-kit#129]
Как отключить показ отладочной информации на экране? И при включенном и выключенном debug при срабатывании исключения на экране выводятся переменные окружения $_SERVER, $_COOKIE, $_SESSION, $_ENV. Необходимо отключить их показ в рабочей версии сайта на хостинге. Как это сделать? Нужно чтобы ошибки писались только в лог файл.

**Comment by trntv** [comment]
в ``.env`` должно стоять ``YII_DEBUG = false``, посмотри как сделано в ``environments/prod/.env``

**Comment by svolga** [comment]
Это все стоит ... все равно выбрасываю исключение  в коде для теста и получаю вывод переменных окружения. Вот скриншот:
http://joxi.ru/xAe5ZKQTayRVAy
В рамке видно, что:
 'YII_DEBUG' => 'false',
    'YII_ENV' => 'prod',

**Comment by svolga** [comment]
Не знаю насколько это правильно, установил в файле 
\common\Environment.php 
значение переменной 
public $debugVar = null;
вместо
public $debugVar = 'YII_DEBUG';

После этого debug информацию перестало отображать на экране

**Comment by trntv** [comment]
вообще, если будет возможность, лучше подтянуть последние изменения, я там вообще выкинул и значительно упростил все эту работу - ``common/env.php`` :-)
