### ISSUE TITLE
.htaccess rule for linux server

### ISSUE THREAD

**Issue by mohdbashir** [trntv/yii2-starter-kit#131]
I have changed the URL in .env file after uploaded the file on server.
FRONTEND_URL    = http://mysubdomain.test.com.au 
BACKEND_URL     = http://mysubdomain.test.com.au/admin
STORAGE_URL     = http://mysubdomain.test.com.au/storage

My root .htaccess file :

Options -Indexes
RewriteEngine on
<IfModule mod_rewrite.c>  
RewriteCond %{REQUEST_URI} ^/admin/$
RewriteRule ^(admin)/$ /$1 [R=301,L]
RewriteCond %{REQUEST_URI} ^/admin
RewriteRule ^admin(/.+)?$ /backend/web/$1 [L,PT]
RewriteCond %{REQUEST_URI} ^.*$
RewriteCond %{REQUEST_URI} !storage	
RewriteRule ^(.*)$ /frontend/web/$1
</IfModule>

Added below .htaccess for /backend/.htaccess and /frontend/.htaccess

RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d 
RewriteRule . index.php

Both URL is working fine but when i login in frontend and on the same browser with another tab open admin tab it showing error: "
"exception 'yii\web\ForbiddenHttpException' with message 'You are not allowed to perform this action.' in /home/coupredeal/public_html/vendor/yiisoft/yii2/filters/AccessControl.php:160
Stack trace:
#0 /home/coupredeal/public_html/vendor/yiisoft/yii2/filters/AccessControl.php(142): yii\filters\AccessControl->denyAccess(Object(yii\web\User))
#1 /home/coupredeal/public_html/vendor/yiisoft/yii2/base/ActionFilter.php(71): yii\filters\AccessControl->beforeAction(Object(yii\web\ErrorAction))
#2 [internal function]: yii\base\ActionFilter->beforeFilter(Object(yii\base\ActionEvent))"

**Comment by trntv** [comment]
And all works as expected. Backend and frontend are designed to work as separate apps on different domains, they shoudn't share same cookies. You should separate them, as starter kit advises or take care of cookies and session configuration.

**Comment by mohdbashir** [comment]
Thanks for the reply. As per the client requirement, we need to run front-end and back-end on same domain. Can you suggest me to manage cookies and session for same domain.
