### ISSUE TITLE
Dotnev problem

### ISSUE THREAD

**Issue by nazakar** [trntv/yii2-starter-kit#132]
Fatal error: Class 'Dotenv' not found in C:\wamp\www\yii2-starter-kit\common\env.php on line 5
Pllease help i'm using wamp server on windows 7

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit#before-installation

**Comment by matthybrid** [comment]
I have the same problem, link is missing

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/blob/master/docs/installation.md#before-you-begin
