### ISSUE TITLE
[Bug/Fix] Unknown property exception while adding Carousel Item

### ISSUE THREAD

**Issue by XzAeRo** [trntv/yii2-starter-kit#133]
It was fixed modifying the line 84 in the WidgetCarouselItem.php file in common\models.
From ['file', 'safe'] to ['image', 'safe']

But FileStorage is not saving uploaded files.
This is a fresh install under a nginx/ubuntu environment.

Another wierd thing is that in the $_SERVER params the 'HOME' key shows '/var/www' while the actual home is another folder: /usr/nginx/<site>

**Comment by trntv** [comment]
> Another wierd thing is that in the $_SERVER params the 'HOME' key shows '/var/www' while the actual home is another folder: /usr/nginx/

Do you running application with Vagrant? Then ``/var/www`` is correct path under vagrant VM.

**Comment by XzAeRo** [comment]
I'm not using Vagrant. Should I?

**Comment by trntv** [comment]
> I'm not using Vagrant. Should I?
actually no. I'm talking about ``/var/www``. It is a webroot inside vagrant box, but it shoudn't interfere with your local copy if you don't use vagrant.

**Comment by XzAeRo** [comment]
Oh ok. I will start doing exactly what I was doing with a fresh installation on a fresh DB. If anything like that happens again, I will post full details.
