### ISSUE TITLE
Validation for 'each'

### ISSUE THREAD

**Issue by sam002** [trntv/yii2-starter-kit#137]
Where validation [rule of roles](https://github.com/trntv/yii2-starter-kit/blob/master/backend/models/UserForm.php#L51)?
Exception `Exception 'ReflectionException' with message 'Class each does not exist' ` is catching on http://backend.example.com/user/update?id=1
_Unfortunately, I did not find information of such implementations._

**Comment by trntv** [comment]
it the last dev-master of yii2 there is ``EachValidator``.
