### ISSUE TITLE
AdminLTE frontend

### ISSUE THREAD

**Issue by dudunegrinhu** [trntv/yii2-starter-kit#141]
How can I have the AdminLTE in the frontend as well?

**Comment by dungphanxuan** [comment]
@dudunegrinhu read the doc it helpful for you
http://www.yiiframework.com/doc-2.0/guide-structure-assets.html

**Comment by XzAeRo** [comment]
* Easy way: copy the contents of backend/views/layouts into /frontend/views/laytouts.
 * **Recomended way**: enable adminlte assets in the frontend and then copy the layouts from the backend, but using the frontend assets.

You should also read the guide posted by @dungphanxuan

**Comment by dudunegrinhu** [comment]
@XzAeRo and @dungphanxuan it worked perfect, thank you so much. The only thing is that in the frontend I don't have access to the user object. <?= Yii::$app->user->identity->userProfile ?>

**Comment by trntv** [comment]
@dudunegrinhu backend layout assuming that you are a logged in user, so you should do a ``Yii::$app->user->isGuest`` check before using ``Yii::$app->user->identity``

**Comment by dudunegrinhu** [comment]
@trntv that worked perfect. Thank you.
