### ISSUE TITLE
RBAC roles

### ISSUE THREAD

**Issue by dudunegrinhu** [trntv/yii2-starter-kit#142]
I have another issue but with RBAC now. 

I created several roles called, client1, client2, client3, staff1, staff2, staff3. 
I added in the User model (common/models/User.php) , in the common/rbac/UserGroupRule.php
and also added the roles in the DB table rbac_auth_item.

I created the user as client1 and assign the role and it worked perfect but the problem that I'm having is that I cannot sign out on the website when I'm logged as client1, only manager and administrator. I couldn't find how to add my roles under signout page and other the same roles on another model pages that I created.

**Comment by dudunegrinhu** [comment]
Actually I figured out here by adding my roles in the console rbaccontroller and doing a rbac init
but my new user assigned to other roles still cannot access some pages like the profile page, signout, account and more.

**Comment by trntv** [comment]
those actions are restricted to the special yii group ``@`` that means "all logged users". I have no idea why ``AccessControl`` don't allows you. Try to debug it. If you'll not find answer - ask for help on the yii forum, because this is a yii framework feature. Good luck!
