### ISSUE TITLE
Widget DbCarousel ERROR

### ISSUE THREAD

**Issue by NePeter** [trntv/yii2-starter-kit#143]
В файле DbCarousel.php вместо строки: 

$items[$k]['content'] = Html::img($item->path);

видимо, предполагалась строка:

$items[$k]['content'] = Html::img($item->base_url.'/'.$item->path);

base_url потерялся :-)

**Comment by Rinat-wc** [comment]
автор уже пофиксил этот момент https://github.com/trntv/yii2-starter-kit/commit/5f2f1470a985da16db34bf7a2d4febff409b75c7

**Comment by trntv** [comment]
@Rinat-wc спасибо.

**Comment by NePeter** [comment]
Sorry, I don't see some new code in the file common/components/widgets/DbCarousel.php and images don't appear in Carousel viewport

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/blob/master/common/components/widgets/DbCarousel.php#L59

**Comment by NePeter** [comment]
Sorry, I missed it at once. I'm newbie here :-)
