### ISSUE TITLE
How use Flash in AdminLTE?

### ISSUE THREAD

**Issue by vindective** [trntv/yii2-starter-kit#144]
How set https://github.com/trntv/yii2-starter-kit/blob/master/backend/views/layouts/common.php#L212 and https://github.com/trntv/yii2-starter-kit/blob/master/backend/views/layouts/common.php#L213

Help me please

**Comment by trntv** [comment]
```
Yii::$app->session->setFlash(
    'alert', 
    ['body' => '...some text...', 'options' => ['class' => 'alert alert-success']]
)
```
