### ISSUE TITLE
2.0 release

### ISSUE THREAD

**Issue by trntv** [trntv/yii2-starter-kit#148]
- [x] close opened issues
- [x] improve structure
- [ ] improve docs
- [x] check code quality

**Comment by zakrot** [comment]
hi
how to update older version to 2.0?
I con not find rntv/yii2-starter-kit version in composer.json ...

**Comment by dungphanxuan** [comment]
Hi @zakrot, it simple. You can fetching a remote using git.
https://help.github.com/articles/fetching-a-remote/

**Comment by trntv** [comment]
> hi
how to update older version to 2.0?
I can not find rntv/yii2-starter-kit version in composer.json ...

starter-kit is a project, not a package. You can't update it with composer, but you can try to update it using this method - https://github.com/trntv/yii2-starter-kit#updates

This is not trivial thing anyway...

**Comment by lilcano** [comment]
please can any one assist me, i am new to yii2. i came across yii2-starter-kit installed it successfully.
I have generated CRUD code using gii for one of my DB tables in the backend. i dont know how to make it available in the AdminLTE template used in the backend. Help please with the steps Thanks

**Comment by zakrot** [comment]
HI
Thank dude!
I have updated the files..
Do I need to update the database as well ?
Is it enough running migration command?
Thank you very much for everything

**Comment by trntv** [comment]
yes, running migrations is enough

**Comment by zakrot** [comment]
Is running migrations commands clear data or there is an upgrade parameter?
Thank you for your considerations

**Comment by trntv** [comment]
migration is an upgrade process, it doesn't clear your current data

2015-05-06 12:03 GMT+03:00 zakrot <notifications@github.com>:

**Comment by zakrot** [comment]
آi
Migration did not create new fields...
for example : 
    in user table: logged_at
    in widget_carousel_item: base_url , type

I created this fields manually, but I think Yii2 Migration does not has an good upgrade method
I looked this page:
	http://www.yiiframework.com/doc-2.0/yii-db-migration.html
and only i found `up` and `down` method for it...
In my opinion upgrade can be stronger in yii2
thanks

**Comment by trntv** [comment]
This is not yii issue. This is how migrations work... the reason is that i made some changes into old migrations, that you have already applied
