### ISSUE TITLE
Storage  404

### ISSUE THREAD

**Issue by dungphanxuan** [trntv/yii2-starter-kit#150]
Hi @trntv . I think i missing some config with storage. 
When i access http://storage.yii2-starter-kit.dev/ and recive Bad Request (#400) message.
But i access http://storage.yii2-starter-kit.dev/cache/1/gL5-MxULxgXYlnyWnGMoJ8XfpSbbzLwL.png?w=200&s=a0ddee54e4e19ded4886cdd84464f23c message return 404

![capture](https://cloud.githubusercontent.com/assets/10725732/7341968/2d0824d4-ecd6-11e4-9b29-ccbf6f02f591.JPG)

**Comment by dungphanxuan** [comment]
Hi @trntv  my app here. https://github.com/dungphanxuan/yii2-starter-kit

**Comment by trntv** [comment]
you should trace you app step by step. What path receives storage glide/index action? is it fired at all?

**Comment by thuongqbd** [comment]
Hi @dungphanxuan, I have same error, just copy .htaccess from frontend/web to storage/web

**Comment by trntv** [comment]
Since author has disappeared, I'm closing it

**Comment by dungphanxuan** [comment]
I folow @thuongqbd  and success! thank!
