### ISSUE TITLE
Issues with carousel image path

### ISSUE THREAD

**Issue by dudunegrinhu** [trntv/yii2-starter-kit#151]
I just uploaded an image to the carousel and the image is not showing because it's setting the wrong path:

frontend/web/1/46QCnIV9zbswtSGCXr6Qv7vY9PYWK8C_.jpg

A temporary fix would be to change common/components/widgets/DbCarousel.php
line 59:

$items[$k]['content'] = Html::img('/storage/web/source/'.$item->path);

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/commit/5f2f1470a985da16db34bf7a2d4febff409b75c7
