### ISSUE TITLE
Contents appeared twice

### ISSUE THREAD

**Issue by flrmatjd** [trntv/yii2-starter-kit#152]
Hi

I was setup yii2 starter kit 2.0.
I was just installed and migrate database and run frontend.
Then Frontend shows conetents twice.

**Comment by flrmatjd** [comment]
It is appeared in frontend.
It looks like debug tool bar.
Frontend does not appear debug tool bar and appear page content once again.

**Comment by trntv** [comment]
this is first time such problem appeared. It seems like you didn't configured your application right.
