### ISSUE TITLE
cookieValidationKey must be configured with a secret key

### ISSUE THREAD

**Issue by dbd5** [trntv/yii2-starter-kit#154]
Hello,

Thanks for the work you put into this kit!

I've set it up following your instructions but I've had this error twice now "exception 'yii\base\InvalidConfigException' with message 'yii\web\Request::cookieValidationKey must be configured with a secret key.' in C:\DEV\xampp\htdocs\Yiitrntv\advanced\vendor\yiisoft\yii2\web\Request.php:1212"

The first time I had it I reverted to the cookie validation keys that were generated with .env
FRONTEND_COOKIE_VALIDATION_KEY = gKGxbaDzQu0ZxJRwx_xRGwlAczdRJ5GX
BACKEND_COOKIE_VALIDATION_KEY = Xwp7YMkWVkD0i1_5rv4EojnzlsY3trzD

Please advice how to fix, thanks

Adam

**Comment by trntv** [comment]
I don't know how you changed your config, but by default ``init`` generates cookie validation keys and write them to .env file. Then, in the application config they are used in:
 ```
cookieValidationKey => getenv('FRONTEND_COOKIE_VALIDATION_KEY')
```

**Comment by dungphanxuan** [comment]
I have seen problem with phpdotenv that dotenv can't load .env file.
I think @dbd5 has problem with php dot env. make sure it work.

**Comment by dbd5** [comment]
I've really been scratching my head to fix this thing and to respond to sir @trntv, I made no changes besides adding the required variables. 

The db dsn and other details are stored in the .env so the fact that I'm able to logon and log out of the kit after using composer is evidence that php Dotenv is loading the .env file. On the other hand, I have also seen a cases where php Dotenv can't load the .env file in which case logon won't happen at all.

**Comment by trntv** [comment]
i can't repeat your problem, so i can't help you. try to use xdebug to trace application process. Is there env variables in $_SERVER before application runs?
https://github.com/trntv/yii2-starter-kit/blob/master/frontend/web/index.php#L22

**Comment by dbd5** [comment]
Resolved, thanks

**Comment by zackijack** [comment]
@dbd5 please share how do you solve it?
