### ISSUE TITLE
Set default language

### ISSUE THREAD

**Issue by zakrot** [trntv/yii2-starter-kit#160]
Hi
I am trying to change default language in first visit(before _locale cookie set)
in base config in common:
    'sourceLanguage'=>'fa_IR',
    'language'=>'fa_IR',
and in params set: 
    'availableLocales'=>[
            'fa_IR'=>'فارسی (IR)',
            'en_US'=>'English (US)',
    ],
But default language is en ...
help me
thanks

**Comment by trntv** [comment]
Change this line if you don't want to set browser prefered language as default for your application:
https://github.com/trntv/yii2-starter-kit/blob/master/common/behaviors/LocaleBehavior.php#L45
to something like this:
``: Yii::$app->language``
