### ISSUE TITLE
keyStorage->set() update bug

### ISSUE THREAD

**Issue by zakrot** [trntv/yii2-starter-kit#162]
Hi
After running 
      Yii::$app->keyStorage->set('myArt.lastState',$state);
The first time it works perfectly, but since then not works well while updating but return true.
Thanks

**Comment by trntv** [comment]
Couldn't reproduce such behavior. Copy latest KeyStorage version from here - https://github.com/trntv/yii2-starter-kit/blob/master/common/components/keyStorage/KeyStorage.php

**Comment by andrewpros** [comment]
@trntv 

I can confirm that there was such error, but it was fixed here https://github.com/trntv/yii2-starter-kit/commit/006e2db54ea3881b63deebbc98dc66a743336ed4 then set is no longer setting the key when it exists.
