### ISSUE TITLE
Date Big

### ISSUE THREAD

**Issue by dudunegrinhu** [trntv/yii2-starter-kit#163]
Somehow my date is showing very big on the screen and not working properly. See image:

https://www.dropbox.com/s/448sfk19efthrpp/Screenshot%202015-05-13%2000.05.07.png?dl=0

I noticed that I'm getting the error file not found app.js so I did a search on that file and found at bower folder and copied but it still not working. Any clue of what could be?

**Comment by trntv** [comment]
This problem isn't connected to starter kit. It's about JUI Datepicker and how you use it.

Maybe that file?
https://github.com/trntv/yii2-starter-kit/blob/master/backend/web/js/app.js
