### ISSUE TITLE
Setting minDate for DatetimepickerWidget

### ISSUE THREAD

**Issue by alladas** [trntv/yii2-starter-kit#167]
Hi Eugine,
Can't find a way to set a minDate to the Datetimepicker.
Through options the 'minDate' parameter is correctly parsed for the input field but the widget still enable the user to select a date before the minDate.
Any tips or hints on how to achieve this?
In advance thanks.

**Comment by trntv** [comment]
Have a look at this - https://github.com/trntv/yii2-bootstrap-datetimepicker#examples

**Comment by alladas** [comment]
Many Thanks. 
I missed that.

**Comment by trntv** [comment]
> Many Thanks. 
I missed that.

I've wrote this after your question :-)
