### ISSUE TITLE
Make a list of things that need documenting and help developing

### ISSUE THREAD

**Issue by ddinchev** [trntv/yii2-starter-kit#168]
So I started using `yii2-starter-kit` for a project of mine and I'm pretty happy with it. I intend to translate it to Bulgarian (and make a `PR` with that later). What I'm thinking is that maybe `yii2-starter-kit` needs a plan for what needs to be documented and done, so someone can pick something and do it. Like what kind of articles and features would you like to have in it but haven't been able to complete.

Also, consider creating an actual docs project on a service like https://readthedocs.org/ - the README.md will quickly get messy.

**Comment by trntv** [comment]
Hi, glad to hear that kit is useful for you. I'll try to create some simple todo, but the main problem for me is docs as i'm not a good writer :-)

**Comment by ddinchev** [comment]
I could try helping documenting some stuff I go through, but at least highlight what needs to be documented better.

**Comment by trntv** [comment]
Any help appreciated. If you feel you can help project in any way - do it :-)

**Comment by trntv** [comment]
- [ ] Simple tutorial about runing frontend, backend and storage on a single domain
