### ISSUE TITLE
frontend and backend user authentication

### ISSUE THREAD

**Issue by nazakar** [trntv/yii2-starter-kit#169]
How to make same frontend and backend user authentication. After frontend login, go to backend with frontend logged user

**Comment by dudunegrinhu** [comment]
You will have to copy the user model and user profile and paste in the fronted. Basically everything related to the user that you have in the backend you will have to do in the frontend. 

Best Regards,
Lucas Guilherme
Libiny Solutions

**Comment by nazakar** [comment]
Thanks for fast response, unfortunately still nothing - after login in frontend, login form appears for backend access
Best Regards

**Comment by dudunegrinhu** [comment]
Now I understood what you want. 
You have to understand that backend and frontend are like 2 different apps, different models, view and controller. 

If you login with webmaster which is the super user you won't see the login again in the frontend so it will depend on your roles. 

Best Regards,
Lucas Guilherme
Libiny Solutions

**Comment by trntv** [comment]
Are backend and frontend on different subdomains in your case?
