### ISSUE TITLE
Install app

### ISSUE THREAD

**Issue by svolga** [trntv/yii2-starter-kit#170]
I get the next exception when install via composer:
******************
 [RuntimeException]
  Failed to clone git@github.com:trntv/yii2-bootstrap-datetimepicker.git, git was not found,
   check that it is installed and in your PATH env.
  "git" не является внутренней или внешней
  командой, исполняемой программой или пакетным файлом.

Screen shot:
http://joxi.ru/1A5WEB7CR5WamE
******************
How it can be solved?

**Comment by Kharalampidi** [comment]
У вас гит не установлен :)
[Manual](http://git-scm.com/book/ru/ch1-4.html)

**Comment by svolga** [comment]
Гит у меня точно установлен, поскольку работаю с ним каждый день :) Тем не менее сегодня снова попробовал starter-kit - нормально установился

**Comment by Kharalampidi** [comment]
> "git" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

Ну GIT так ругается, когда не может найти глобальную переменную в системе :santa:
