### ISSUE TITLE
Sign up with email confirmation

### ISSUE THREAD

**Issue by dbd5** [trntv/yii2-starter-kit#172]
Hello,

Is there a way to enable sign up with email confirmation etc?

Regards,

Adam

**Comment by trntv** [comment]
Hello.
No. You should create it.

**Comment by dbd5** [comment]
Ok, thanks

**Comment by dbd5** [comment]
Hi Eugene,

For the sophistication of this project, I think sign up with email confirmation is essential.
dektrium/yii2-user is probably one of the most complete user modules available so I'd like to try to integrate it to this project rather than reinvent the wheel but I think there may be conflicts since it implements some of what you have implemented already (social login, profile?) also the database structures are not the same. 

Do you dektrium/yii2-user will be compatible?

Regards,

Adam
