### ISSUE TITLE
username validate for reserved word

### ISSUE THREAD

**Issue by dungphanxuan** [trntv/yii2-starter-kit#174]
Hi @trntv . How can make rules for username field about validate reserved word.
Example. When user put username is login in register form. Then app alert that username is a reserved word and can't not create.

Thank!

**Comment by Kharalampidi** [comment]
You can create custom validation rule in your model (User).
Check this [manual](http://www.yiiframework.com/doc-2.0/guide-input-validation.html#creating-validators) .

**Comment by trntv** [comment]
https://github.com/yiisoft/yii2/blob/master/docs/guide/tutorial-core-validators.md#yiivalidatorsrangevalidatorin-

**Comment by dungphanxuan** [comment]
Hi thank! it simple that using rangevalidator
