### ISSUE TITLE
Text Widget from static page or article

### ISSUE THREAD

**Issue by svolga** [trntv/yii2-starter-kit#175]
Is it possibly run Text Widget from static page or article?

**Comment by trntv** [comment]
Не совсем понял вопрос.

**Comment by svolga** [comment]
Виджет можно вызвать из php кода. Как встроить его вызов в текстовый редактор страницы, соотвесвенно чтобы этот виджет вызывался на странице.

**Comment by trntv** [comment]
Никак. Для такого надо делать плагины как в цмсках, которые будут разбирать
текст, искать определенные текстовые блоки и выполнять их.

Можете попробовать реализовать через JS. Вставлять в текст что-то типа
``<text-block key="awesome-key" />``, делать экшн который будет по аякс
запросу отдавать текст блока по его ключу и заменять.

25 мая 2015 г., 11:35 пользователь Serge <notifications@github.com> написал:

**Comment by trntv** [comment]
В таком случае лучше всего делать отдельную вьюху для страницы и хранить имя, например в базе.

https://github.com/trntv/yii2-starter-kit/issues/176
