### ISSUE TITLE
How to save user and userprofile model in single form.

### ISSUE THREAD

**Issue by mohdbashir** [trntv/yii2-starter-kit#178]
I would like to save or create user with userprofile on single form. With the below code form is showing and validation is also working but userprofile data not saved. can you please help where i am doing mistake?

UserController.php

     public function actionCreate()
    {
        $model = new UserForm();
        $profileModel = new UserProfile();
        
        $model->setScenario('create');
        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            if ($profileModel->load(Yii::$app->request->post()) && $profileModel->save()) 
              return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'profileModel' => $profileModel,
            'roles' => ArrayHelper::map(Yii::$app->authManager->getRoles(), 'name', 'name')
        ]);
    }

_form.php

    <?php $form = ActiveForm::begin(); ?>
        <?= $form->field($profileModel, 'firstname') ?>
        <?= $form->field($profileModel, 'middlename') ?>
        <?= $form->field($profileModel, 'lastname') ?>
        <?= $form->field($profileModel, 'mobile') ?>
        <?= $form->field($profileModel, 'gender')->dropDownlist([
            \backend\models\UserForm::GENDER_FEMALE => Yii::t('frontend', 'Female'),
            \backend\models\UserForm::GENDER_MALE => Yii::t('frontend', 'Male')
        ]) ?>  
        <?= $form->field($model, 'username') ?>
        <?= $form->field($model, 'email') ?>
        <?= $form->field($model, 'password')->passwordInput() ?>
        <?= $form->field($model, 'status')->label(Yii::t('backend', 'Active'))->checkbox() ?>
        <?= $form->field($model, 'roles')->checkboxList($roles) ?>
        <div class="form-group">
            <?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
        </div>
    <?php ActiveForm::end(); ?>

**Comment by trntv** [comment]
```
if ($model->load(Yii::$app->request->post()) && $model->save()) {
        $profileModel->user_id = $model->id;
        if ($profileModel->load(Yii::$app->request->post()) && $profileModel->save()) 
          return $this->redirect(['index']);
    }
```

**Comment by mohdbashir** [comment]
Showing error:
Getting unknown property: backend\models\UserForm::id

**Comment by mohdbashir** [comment]
I have also added attribute id in UserForm but still showing error.

**Comment by trntv** [comment]
```php
if ($model->load(Yii::$app->request->post()) && $model->save()) {
        $profileModel->user_id = $model->getModel()->id;
        if ($profileModel->load(Yii::$app->request->post()) && $profileModel->save()) 
          return $this->redirect(['index']);
    }
```

**Comment by mohdbashir** [comment]
still showing error: -

Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '44' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `user_profile` (`user_id`, `firstname`, `middlename`, `lastname`, `mobile`, `gender`, `location`, `locale`, `avatar_path`, `avatar_base_url`) VALUES (44, 'dame888', '', 'smithttt333', NULL, 2, '', 'en-US', NULL, NULL)

Error Info: Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry '44' for key 'PRIMARY'
)

**Comment by trntv** [comment]
Because you already have user_profile for this user. delete it before creating new.

**Comment by mohdbashir** [comment]
Yes it is working.  Thanks

     if ($model->load(Yii::$app->request->post()) && $model->save()) { 
              $profileDeleteModel =  UserProfile::findOne($model->getModel()->id);
              $profileDeleteModel->delete();
             
            $profileModel->user_id = $model->getModel()->id;
            if ($profileModel->load(Yii::$app->request->post()) && $profileModel->save()) 
            return $this->redirect(['index']);
        }

One more question, is it correct way to do this. Can we have another solution?

**Comment by trntv** [comment]
yep, whe have - https://github.com/trntv/yii2-starter-kit#multimodel
