### ISSUE TITLE
session problems for multiple application in single domain 

### ISSUE THREAD

**Issue by sasiarjun** [trntv/yii2-starter-kit#182]
We configured like /var/www/app1 and /var/www/app2 , Both are logging in single session...how can i make this different session.

I tried with following  solution from yii2 wiki...But its doesn't workout  here..
'identityCookie' => [
          'name' => '_backendUser', // unique for backend
          'path'=>'/advanced/backend/web'  // correct path for the backend app.
      ]

Please give solutions for this..

**Comment by trntv** [comment]
To be honest, i didn't face this problem for now. 
Try to change default ``idParam`` in user config

**Comment by sasiarjun** [comment]
for changing the id param also not working. my application is in ubuntu server only, Is there any other way to configure yii2 multi apps in single domain

**Comment by trntv** [comment]
i have no idea. Let me try, and i'll describe the whole proccess

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/issues/188

**Comment by alvarolordelo** [comment]
I've faced the same issue - One domain and multiple Yii2 apps so I've added on each app on WEB config file:
On components array 
'session' => [
'name' => 'PHP_YOURIDHERE_ID',
'savePath' => sys_get_temp_dir(),
],
The problem disapearred!
