### ISSUE TITLE
Update key stroage bug

### ISSUE THREAD

**Issue by andrewpros** [trntv/yii2-starter-kit#183]
The issue https://github.com/trntv/yii2-starter-kit/issues/162 should be reopened.

The description is in https://github.com/trntv/yii2-starter-kit/issues/162, to recap, a key "app.key" won't work, value of 1 or 0, test with 0, then change the test to 1, won't work.

    public function testKeyStorageSet()
    {
        \Yii::$app->keyStorage->set('app.key', '0');
        $this->assertEquals('0', \Yii::$app->keyStorage->get('app.key', null, false));
    }

then 

    public function testKeyStorageSet()
    {
        \Yii::$app->keyStorage->set('app.key', '1');
        $this->assertEquals('1', \Yii::$app->keyStorage->get('app.key', null, false));
    }

**Comment by trntv** [comment]
As i can see, tests works fine. 
Update your local KeyStorage.php to current version:
https://github.com/trntv/yii2-starter-kit/blob/master/common/components/keyStorage/KeyStorage.php

**Comment by andrewpros** [comment]
@trntv I have the latest version.

I found the problem, no sure why it happens.

Here is the path from debugger, calling Yii::$app->keyStorage->set('app.key', 'ok');

Goes save(false) on model here https://github.com/trntv/yii2-starter-kit/blob/master/common/components/keyStorage/KeyStorage.php#L45

Then in save it goes to update here  https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L591

Then updateInternal here https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L650

Then it tries to get old primary key here https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L710

But the value of $id here https://github.com/yiisoft/yii2/blob/master/framework/db/BaseActiveRecord.php#L1040 will be always null

because of not getting the id in KeyStorage.php https://github.com/trntv/yii2-starter-kit/blob/master/common/components/keyStorage/KeyStorage.php#L158

i have changed it to 

    protected function getModel($key) {
        $query = call_user_func($this->modelClass . '::find');
        return $query->where(['key' => $key])->one();//select(['key', 'value'])->one();
    }

and now it works

What you think about it?

**Comment by andrewpros** [comment]
@trntv Any input on this?
