### ISSUE TITLE
Preserve article attachements file names

### ISSUE THREAD

**Issue by trntv** [trntv/yii2-starter-kit#184]

**Comment by shuvaevsb** [comment]
function actionAttachmentDownload return file with correct file name, but without extension.
I get extension by code (add to actionAttachmentDownload  function)
$ext = explode ('.',$model->path)[1];

return \Yii::$app->response->sendStreamAsFile(
            \Yii::$app->fileStorage->getFilesystem()->readStream($model->path),
            ($model->name.".".$ext)
);

**Comment by trntv** [comment]
update ``yii2-file-kit``, names will be saved with extension.
