### ISSUE TITLE
The requested PHP extension ext-intl * is missing from your system.

### ISSUE THREAD

**Issue by i-coder** [trntv/yii2-starter-kit#186]
Пробую ставить через composer install все хорошо ставится н ов конце выдает "The requested PHP extension ext-intl * is missing from your system." http://joxi.ru/82Qp77wSax67md 
Работаю на OS X сервер MAMP PRO 3.2 Спасибо за помощь

**Comment by Beaten-Sect0r** [comment]
И что не ясно? Раскомментируйте в php.ini ext-intl.

**Comment by i-coder** [comment]
что расскоментировать такой строчки нету в php.ini MAMP PRO

**Comment by i-coder** [comment]
http://joxi.ru/DmB1EE9SkLYzrP

**Comment by amstr1k** [comment]
@i-coder попробуйте http://stackoverflow.com/questions/20630085/mamp-pro-install-extension-intl-doesnt-work или

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/issues/188
