### ISSUE TITLE
Timeline Event

### ISSUE THREAD

**Issue by dudunegrinhu** [trntv/yii2-starter-kit#187]
Eugene,
How can I use the timeline event? I tried to find any documentation but no lucky.
I have my application in the backend and I have a form that creates something for the user which has access to my frontend app. When I create that form I want to send an Application Timeline Event to this user so next time that he login (in the frontend) he would see the notification at the top right corner of the page and when click it would go to the timeline page with the event information.

Is it possible to do that with your Timeline application?
Thanks for the great starting kit.

**Comment by trntv** [comment]
Hi there is an example:
https://github.com/trntv/yii2-starter-kit/blob/master/common/models/User.php#L262

But i plan to create docs for this starter kit, but don't know when i'll have enough time for it
