### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by trntv** [trntv/yii2-starter-kit#188]
Subjects to cover:
- [x] Requirements 
- [x] Regular installation
- [x] Single domain installation
- [x] Command bus
- [x] Timeline
- [ ] UserToken

Please, leave your requests for docs here.

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/issues/187

**Comment by XzAeRo** [comment]
@trntv What do you think about translated docs? Or do you want to avoid that path?

**Comment by trntv** [comment]
Тут с документацией вообще проблемы. Я не особо красноречив даже по-русски, но в любом случае документации было бы намного больше если бы она не нужна была по английски. 

Так что решил писать хотя бы один вариант. А так, я боюсь что если начну ее вести на двух языках, то английский вариант будет постоянно расссинхронизирован :-)

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/issues/358
