### ISSUE TITLE
Getting unknown property: common\models\Page::view

### ISSUE THREAD

**Issue by Kharalampidi** [trntv/yii2-starter-kit#191]
При создании и редактирование лезет ошибка 
```
Getting unknown property: common\models\Page::view
```
Не видит поле такое у модели, хотя всё хорошо вроде..

**Comment by Kharalampidi** [comment]
В БД нет такого поля... И миграций для него нет.. :disappointed:

**Comment by Kharalampidi** [comment]
Во монолог то) Нашёл, где оно спряталось)

**Comment by trntv** [comment]
:-)
