### ISSUE TITLE
Internal Server Error in endBody()

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#193]
Commit: b99ad83810fba54b01b2d12b90015fd58876b723
View file calls to $this->endBody() cause an internal error when the application is installed without the RBAC migration being run.

"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, webmaster@vagrant.host.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log."

**Comment by trntv** [comment]
how this commit can be connected with such error?
Show your error.log.
