### ISSUE TITLE
Article tag feature

### ISSUE THREAD

**Issue by dungphanxuan** [trntv/yii2-starter-kit#194]
Hi @trntv . are you plan for article taggable feature
Link
https://github.com/creocoder/yii2-taggable

**Comment by amstr1k** [comment]
@dungphanxuan but to take the problem and do it yourself instead of asking trntv implement what you need? I think the installation process is not that difficult

**Comment by dungphanxuan** [comment]
Yes, it not difficult to install, I just suggest a feature for this starter kit.

**Comment by amstr1k** [comment]
@dungphanxuan Implement, I think no one will be against. Pull requests are welcomed

**Comment by trntv** [comment]
Once again - this project is not a CMS or something like that. This is an application template. 
So the main purpose of it not to implement all possible features but create a starting point for your own application, where you can create everything you want.
