### ISSUE TITLE
Ошибка в tests/bootstrap.php

### ISSUE THREAD

**Issue by Kharalampidi** [trntv/yii2-starter-kit#195]
https://github.com/trntv/yii2-starter-kit/blob/master/tests/bootstrap.php#L9
```
Dotenv::load( __DIR__ );
```
Нужно сделать импорт Dotenv + передать в конструктор __DIR__ 
```
new Dotenv(__DIR__)
```

**Comment by trntv** [comment]
спасибо, надо бы CI подключить, но смысла особого нет, так как тестов совсем немного - чисто для примера, а нормально покрывать тестами и потом за ними следить - банально нет времени.
