### ISSUE TITLE
missingTranslation

### ISSUE THREAD

**Issue by loveorigami** [trntv/yii2-starter-kit#197]
Very useful auto-complete lack of translation as Zelenin module:

https://github.com/zelenin/yii2-i18n-module/blob/master/Module.php#L21
and add to config
```php
                '*'=> [
                    'class' => 'yii\i18n\DbMessageSource',
                    'sourceMessageTable'=>'{{%i18n_source_message}}',
                    'messageTable'=>'{{%i18n_message}}',
                    'enableCaching' => YII_ENV_DEV,
                    'cachingDuration' => 3600,

                    'langueges' => ['ru-Ru', 'uk-Uk'],
                    'on missingTranslation' => ['\backend\modules\i18n\Module', 'missingTranslation']
                 ],
```

**Comment by golles** [comment]
@trntv and @loveorigami  Please review my pull request: https://github.com/trntv/yii2-starter-kit/pull/240

**Comment by trntv** [comment]
Sorry for not close this issue early, but i don't think it is right behavior to create a translation stub in this case. The main goal of this functionality is to let administrator know about missing translation.
