### ISSUE TITLE
Website not working well

### ISSUE THREAD

**Issue by msanchezt** [trntv/yii2-starter-kit#198]
Hi, I have the following problem:

Website looks working well when accessing to this URL:
http://vector5.raspctl.com/yii2-starter-kit/frontend/web/

But when I navegate to any menu (connect, articles,...) I get the following error:

The requested URL /yii2-starter-kit/frontend/web/user/sign-in/login was not found on this server.

For example, this URL:
http://vector5.raspctl.com/yii2-starter-kit/frontend/web/user/sign-in/login

Any idea about which could be the problem?

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/blob/master/docs/installation.md#configure-your-web-server

**Comment by msanchezt** [comment]
Sorry, but I already did this and problem persist.

The think is main pages works: http://vector5.raspctl.com/yii2-starter-kit/frontend/web/

But not subapges: http://vector5.raspctl.com/yii2-starter-kit/frontend/web/page/about

I can't see the problem...

**Comment by ockor** [comment]
Hi, it don't working well too.
Only index page can work well.
