### ISSUE TITLE
Updating via upstream merge would only work if it's applied on top of a fork

### ISSUE THREAD

**Issue by ddinchev** [trntv/yii2-starter-kit#199]
It should be noted in the [updated section](https://github.com/trntv/yii2-starter-kit#updates) that it would only work if the developer that's using `yii2-starter-kit` has started via fork and not using the way described in the install section. Otherwise his history probably has initial commit that doesn't include the whole history and that will mess everything up.

**Comment by trntv** [comment]
I think we should remove update section at all. This is not a package that meant to be updated

**Comment by ddinchev** [comment]
I would suggest I add another installation option that uses a fork and a short "guide" how would one keep up-to-date with the changes.

**Comment by trntv** [comment]
you are welcome ^_^
