### ISSUE TITLE
Backend Login

### ISSUE THREAD

**Issue by dudunegrinhu** [trntv/yii2-starter-kit#200]
My app has backend and frontend.
How can I block backend access for manager and user and only enable backend login for the webmaster?

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/blob/master/backend/config/web.php#L44
https://github.com/trntv/yii2-starter-kit/blob/master/console/controllers/RbacController.php#L28
https://github.com/yiisoft/yii2/blob/master/docs/guide/security-authorization.md#role-based-access-control-rbac-
