### ISSUE TITLE
Can't Request user's acctoken from Rest Api http://site.com/api/v1/user?username=webmaster&password=webmaster 

### ISSUE THREAD

**Issue by crfeng** [trntv/yii2-starter-kit#201]
response message:
{
    "name": "Unauthorized",
    "message": "You are requesting with an invalid credential.",
    "code": 0,
    "status": 401
}

**Comment by trntv** [comment]
There is no way to authentificate with username and password params, only with access-token

Check this out https://github.com/yiisoft/yii2/blob/master/docs/guide/rest-authentication.md
