### ISSUE TITLE
Problem with nginx and vagrant, nginx return http500

### ISSUE THREAD

**Issue by ajmrive** [trntv/yii2-starter-kit#203]
Hi!

after all, thanks for this great starter kit.

I have a problem when I access to http://backend.yii2-starter-kit.dev or http://yii2-starter-kit.dev/, nginx always return HTTP 500 but not show anything else, and the error log doesn´t show anything neither.

I didn´t change anything in the config file for vagrant and the same for nginx.

could someone help me, please?

Thanks so much

**Comment by trntv** [comment]
but vagrant support will be deprecated in a favor of docker in a nearest future
https://github.com/trntv/yii2-starter-kit/issues/192

**Comment by ajmrive** [comment]
thanks for you help!! but I still have the same problem.. even worst because in http://yii2-starter-kit.dev/ I have now the welcome nginx page.

any suggestion?

**Comment by trntv** [comment]
1. connect to your vagrant box
2. restart nginx
3. If nothing changed, write here output of the ``cat /etc/nginx/sites-enabled/yii2-starter-kit.dev`` and ``ls -la /var/www``

**Comment by ajmrive** [comment]
Hi!

here the output:

vagrant@yii2-starter-kit:~$ sudo service nginx restart
 * Restarting nginx nginx
   ...done.
vagrant@yii2-starter-kit:~$ cat /etc/nginx/sites-enabled/yii2-starter-kit.dev
## PHP-FPM Servers ##
upstream php-fpm {
    server unix:/var/run/php5-fpm.sock;
}

## FRONTEND ##
server {
        listen 80;

        root /var/www/frontend/web;
        index index.php index.html;

        server_name yii2-starter-kit.dev;

        charset utf-8;

        # location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|pdf|ppt|txt|bmp|rtf|js)$ {
        #       access_log off;
        #       expires max;
        # }

        location / {
                try_files $uri $uri/ /index.php?$args;
        }

    client_max_body_size 32m;

        location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass php-fpm;
                fastcgi_index index.php;
                include fastcgi_params;

                ## Cache
                # fastcgi_pass_header Cookie; # fill cookie valiables, $cookie_p
hpsessid for exmaple
                # fastcgi_ignore_headers Cache-Control Expires Set-Cookie; # Use
 it with caution because it is cause SEO problems
                # fastcgi_cache_key "$request_method|$server_addr:$server_port$r
equest_uri|$cookie_phpsessid"; # generating unique key
                # fastcgi_cache fastcgi_cache; # use fastcgi_cache keys_zone
                # fastcgi_cache_path /tmp/nginx/ levels=1:2 keys_zone=fastcgi_ca
che:16m max_size=256m inactive=1d;
                # fastcgi_temp_path  /tmp/nginx/temp 1 2; # temp files folder
                # fastcgi_cache_use_stale updating error timeout invalid_header
http_500; # show cached page if error (even if it is outdated)
                # fastcgi_cache_valid 200 404 10s; # cache lifetime for 200 404;

                # or fastcgi_cache_valid any 10s; # use it if you want to cache
any responses
        }
}

## BACKEND ##
server {
        listen 80;

        root /var/www/backend/web;
        index index.php index.html;

        server_name backend.yii2-starter-kit.dev;

        charset utf-8;

        client_max_body_size 16m;

        location / {
                try_files $uri $uri/ /index.php?$args;
        }

    # location ~* ^.+\.(jpg|jpeg|gif|png|ico|css|pdf|ppt|txt|bmp|rtf|js)$ {
        #       access_log off;
        #       expires max;
    # }

        location ~ \.php$ {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                fastcgi_pass php-fpm;
                fastcgi_index index.php;
                include fastcgi_params;
        }

}

## STORAGE ##
server {
        listen 80;
        server_name storage.yii2-starter-kit.dev;

        root /var/www/storage/web;
        index index.html;
        # expires max;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-fpm;
        include fastcgi_params;
    }
}

## MISC ##

### WWW Redirect ###
#server {
#    listen       80;
#    server_name  www.yii2-starter-kit.dev;
#    return       301 http://yii2-starter-kit.dev$request_uri;
#}vagrant@yii2-starter-kit:~$ ls -la /var/www
total 206
drwxrwxrwx  1 www-data www-data   4096 Jun 11 11:09 .
drwxr-xr-x 14 root     root       4096 Jun 11 10:32 ..
-rwxrwxrwx  1 www-data www-data    778 Jun 11 11:09 .env
-rwxrwxrwx  1 www-data www-data    252 Jun 10 10:50 .gitignore
drwxrwxrwx  1 www-data www-data      0 Jun 11 10:32 .vagrant
-rwxrwxrwx  1 www-data www-data   3439 Jun 10 10:50 CHANGELOG.md
-rwxrwxrwx  1 www-data www-data   1622 Jun 10 10:50 LICENSE.md
-rwxrwxrwx  1 www-data www-data   8691 Jun 10 10:50 README.md
-rwxrwxrwx  1 www-data www-data   1537 Jun 10 10:50 Vagrantfile
-rwxrwxrwx  1 www-data www-data   1655 Jun 10 10:50 autocompletion.php
drwxrwxrwx  1 www-data www-data   4096 Jun 10 11:45 backend
-rwxrwxrwx  1 www-data www-data    231 Jun 10 10:50 codeception.yml
drwxrwxrwx  1 www-data www-data   4096 Jun 10 10:50 common
-rwxrwxrwx  1 www-data www-data   1987 Jun 10 10:50 composer.json
-rwxrwxrwx  1 www-data www-data 146431 Jun 11 11:05 composer.lock
drwxrwxrwx  1 www-data www-data      0 Jun 10 10:50 console
drwxrwxrwx  1 www-data www-data   4096 Jun 10 10:50 docs
drwxrwxrwx  1 www-data www-data   4096 Jun 10 10:50 frontend
drwxrwxrwx  1 www-data www-data      0 Jun 10 11:48 nbproject
drwxrwxrwx  1 www-data www-data      0 Jun 10 10:50 storage
drwxrwxrwx  1 www-data www-data   4096 Jun 10 10:50 tests
-rwxrwxrwx  1 www-data www-data   2764 Jun 10 10:50 vagrant.sh
-rwxrwxrwx  1 www-data www-data    141 Jun 11 10:27 vagrant.yaml
drwxrwxrwx  1 www-data www-data   4096 Jun 11 11:09 vendor
-rwxrwxrwx  1 www-data www-data   2471 Jun 11 11:09 vhost.conf
-rwxrwxrwx  1 www-data www-data   2471 Jun 10 10:50 vhost.conf.dist
vagrant@yii2-starter-kit:~$
