### ISSUE TITLE
Assets 

### ISSUE THREAD

**Issue by svolga** [trntv/yii2-starter-kit#209]
Здравствуйте! Установил последнюю версию yii2-starter-kit. Backend и Frontend работают, но не подключаются стили и js файлы. 
В файле .env прописаны Urls для FRONTEND_URL, BACKEND_URL, STORAGE_URL

На странице About в отладчике вижу: http://joxi.ru/eAOD89PhVk86ro
Т.е. например, путь к bootstrap.css выглядит:
http://yii2-referat/frontend/web/assets/2f0a7509/css/bootstrap.css

Но внутри assets нет каталога вида 2f0a7509 со всем содержимым.
В чем может быть причина?

**Comment by Kharalampidi** [comment]
Причина скорее в настройке веб-сервера. Подозреваю, что нет прав на создание симулинков для assets. У вас apache?

**Comment by svolga** [comment]
Apache-2.4, работает из-под OpenServer. Где раздаются эти права?

**Comment by svolga** [comment]
В общем все понятно. При включенных ошибках также может появиться сообщение symlink(): Cannot create symlink, error code(1314). Такая ситуация происходит когда OpenServer запущен не с правами админа. Счас все нормально работает.
