### ISSUE TITLE
Modified Widget Menus with kartik-v/yii2-tree-manager

### ISSUE THREAD

**Issue by adiramardiani** [trntv/yii2-starter-kit#210]
I think would be better to configure menu widget with [this](http://demos.krajee.com/tree-manager-demo/tree-view) extension

And can get with ```php <?= DbMenu::widget(['key' => 'key-from-backend']) ?> ``` from menu under root nodes

Thanks

**Comment by trntv** [comment]
DbMenu is a simple example how to create a db stored menu. You can extend it or reuse with any third-party extensions you want
