### ISSUE TITLE
composer.json has outdated dependencies?

### ISSUE THREAD

**Issue by Icedroid** [trntv/yii2-starter-kit#211]
when I  run this:
```
composer create-project --prefer-dist --stability=dev trntv/yii2-starter-kit
```
I get warning as follow:
```
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
```

**Comment by Icedroid** [comment]
In the install document it says:
```
1. Copy .env.dist to .env in the project root
```
but I can't find .env.dist in project root

**Comment by trntv** [comment]
composer.json hasn't. 
This is normal situation using composer.lock to lock specific dependencies versions. You can run ``composer update`` after project has been installed.
