### ISSUE TITLE
AdminLTE table not auto fixed

### ISSUE THREAD

**Issue by Icedroid** [trntv/yii2-starter-kit#212]
When I have long content, I can't see the whole table content.
![table_not_auto_fixed](https://cloud.githubusercontent.com/assets/674647/8144833/cb0828da-1221-11e5-97fc-9d66d9e3c465.png)

**Comment by Icedroid** [comment]
I edited Frontend maintenance mode to enable, But I also to visit the frontend website.

**Comment by trntv** [comment]
About AdminLTE, i just use it, i didn't write it, but i think we can remove some columns from long tables.

About maintenance mode. Do you use latest yii2-starter-kit version? we've fix this bug several weeks ago

**Comment by Icedroid** [comment]
@trntv 
AdminLTE did't have the problem, because I found the article list table is normal.
About maintenance mode. I already know the problem is, I am used it in the dev mode.

**Comment by trntv** [comment]
admitLTE don't have such long strings without any whitespaces. They should add ``word-break`` to their tables to show them correct ^_^

Do you think i should add this to backend stylesheet?

**Comment by XzAeRo** [comment]
It's not a AdminLTE problem. The backend is using the default Yii2 GridView, which uses the default Bootstrap 3 tables design. (The AdminLTE stylesheets are doing just minor style-tweaking to the tables).

I believe it'll be great to have this solved in the backend stylesheet, specially since this problem is very specific to this implementation, and probably won't be addressed by AdminLTE nor by Bootstrap.

**Comment by trntv** [comment]
it's already there. enjoy ;-)

**Comment by Icedroid** [comment]
Thank you. I am add yii2-starter-kit to my own github project. Now How could I upgrade yii2-starter-kit  to new version?

**Comment by XzAeRo** [comment]
From the old docs:

First, go to the project root. Then, add remote repository `upstream`.
```
git remote add upstream https://github.com/trntv/yii2-starter-kit.git
```
Fetch latest changes from it
```
git fetch upstream
```
Merge these changes into your repository
```
git merge upstream/master
```

When you merge the changes, probably a lot of warnings will appear, indicating that some files have unresolved conflicts. Those file will have this kind of messages:

```
<<<<<<< HEAD
    This line was added from the 'master' branch.
=======
   The 'local' branch version is here.
>>>>>>> local
```

Whatever is between `<<<<<<< HEAD` and `=======`, will be the changes done by the master project (trntv/yii2-master-kit). And whatever is between `=======` and `>>>>>>> local`, will be the old version of the file **or the changes you made**.

You will have to **manually** edit each of the conflicted files and decide if you want to keep `This line was added from the 'master' branch.` or `The 'local' branch version is here.`.

Have a happy merging!
