### ISSUE TITLE
Relative/absolute URLs, problems with img

### ISSUE THREAD

**Issue by msanchezt** [trntv/yii2-starter-kit#213]
Hi,

I've the website deployed, but I believe some paths are not correctly set.

The main problem I have is that the path of images is not correctly displayed. For example, image 'anonymous.jpg' in backend is not being displayed because the path is "http://mywebsite.com/img/anonymous.jpg" instead of: "http://mywebsite.com/backend/web/img/anonymous.jpg"

Where can I edit the path and fix this? Already tried everything I could...

Thanks!

**Comment by XzAeRo** [comment]
The Yii2-Starter-Kit is not ready to work in a single-domain installation.

The [installation guide](https://github.com/trntv/yii2-starter-kit/blob/master/docs/installation.md), specifies this, and every problem regarding a single-domain installation, is a problem you must resolve on your own.

In this case, you should add `<?php echo Yii::getAlias('@backendUrl') ?>` in the `common.php` layout in the backend. And also you will have to set in your `.env` file the `BACKEND_URL` to `http://mywebsite.com/backend/web/`.

Even better, you can [use this guide](https://github.com/mickgeek/yii2-advanced-one-domain-config), to setup your single-domain installation (remember that the yii2-starter-kit also uses the storage folder!).

Have a great week.

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/blob/master/docs/installation.md#single-domain
