### ISSUE TITLE
'Calling unknown method: yii\console\Application::getSecurity()'

### ISSUE THREAD

**Issue by loveorigami** [trntv/yii2-starter-kit#216]
Then I install - I have error
```php
'Calling unknown method: yii\console\Application::getSecurity()'
```
![0001](https://cloud.githubusercontent.com/assets/98164/8210987/51c10ae2-151d-11e5-863d-492b3b603464.jpg)

**Comment by XzAeRo** [comment]
Are you using the latest yii2-starter-kit version?

**Comment by loveorigami** [comment]
yes, only downloading
```php
git fetch origin master
git rev-list HEAD...origin/master --count
git merge origin/master
git log origin/master -10 --oneline
```
![0001](https://cloud.githubusercontent.com/assets/98164/8214340/3927f694-1531-11e5-95a6-3f220f2d1b6b.jpg)

**Comment by XzAeRo** [comment]
I will verify.
Are you using a WAMP stack?

**Comment by loveorigami** [comment]
I am delete all and re-downloading.
Now it is work!
