### ISSUE TITLE
Backend menu widget only active with actionIndex

### ISSUE THREAD

**Issue by adiramardiani** [trntv/yii2-starter-kit#219]
Hello
The menu only active/expand for actionIndex, create or update is not active

**Comment by trntv** [comment]
this is the way ``\yii\widget\sMenu`` works. If you wan't you override ``isItemActive`` method.

**Comment by adiramardiani** [comment]
Sorry, did you know the method to override `isItemActive` ?
To activate the all of method in controller, so the create, update or view still *active* ?

**Comment by XzAeRo** [comment]
You can use [`activateParents`](http://www.yiiframework.com/doc-2.0/yii-widgets-menu.html#$activateParents-detail) option.

**Comment by adiramardiani** [comment]
Still same :(

**Comment by adiramardiani** [comment]
@trntv and @XzAeRo actualy in https://github.com/trntv/yii2-starter-kit/blob/master/backend/views/layouts/common.php#L129 use 
```php
'activateParents'=>true,
```

But has no effect, for example in page/index is active and collapse in menu, but not for page/create etc
