### ISSUE TITLE
Использование CPU

### ISSUE THREAD

**Issue by Afinogen** [trntv/yii2-starter-kit#220]
Под windows не корректно отображает загрузку ЦПУ в отчете - данные завышены, в js скрипте есть строчка (# 26)
data[k]["data"][setLength - 1] = ([setLength, v * 100])
именно умножение на 100 портит вывод

**Comment by Afinogen** [comment]
проверил под линуксом, там вывод идет в виде 0.34, виндовс выводит целое число 34

**Comment by trntv** [comment]
проблема в том что я не могу проверить под виндой, так как у меня ее под рукой нет, можете уточнить, это баг https://github.com/trntv/probe ?

**Comment by Afinogen** [comment]
Да, нужно  привести вывод к 1 виду, в комменте выше я описал в чем разница
P.S. написал здесь так как под линуксом на тот момент не тестировал вывод ЦПУ
