### ISSUE TITLE
Use Dotnet is bad idea

### ISSUE THREAD

**Issue by zxczxc12** [trntv/yii2-starter-kit#226]
Hello 

Look 
https://github.com/vlucas/phpdotenv/issues/76#issuecomment-87252126

And i have some troubles with Dotenv too:
http://www.yiiframework.ru/forum/viewtopic.php?f=19&t=30332

**Comment by ddinchev** [comment]
I think this issue is irrelevant - here `.env` is already part of `.gitignore` and is never suggested as a way to deploy production applications.

**Comment by trntv** [comment]
@ddinchev thanks
