### ISSUE TITLE
Inconsistency of naming of timeline data?

### ISSUE THREAD

**Issue by ddinchev** [trntv/yii2-starter-kit#227]
Is there a particular reason for the different case of timeline `json` data?
https://github.com/trntv/yii2-starter-kit/blob/master/common/models/User.php#L267-L269

There is `userId` and `publicIdentity` but `created_at`. Shouldn't we stick to either `camelCase` or `underscore` case?

**Comment by trntv** [comment]
``publicIdentity`` and ``userId`` named after corresponding methods, while ``created_at`` after standart field name.
I don't see a big problem here, but if you want you can create a PR and i'll merge it into next version.
