### ISSUE TITLE
Add support for header items in AdminLTE sidebar menu

### ISSUE THREAD

**Issue by XzAeRo** [trntv/yii2-starter-kit#229]
The idea is to enable this item style in the Backend application:
![navigation](https://cloud.githubusercontent.com/assets/1656037/8626680/3b3c4fd2-271c-11e5-853e-382c5fb8c809.PNG)

Currently, when the class `header` is added to the item via `options.class`, the output is this:
![current](https://cloud.githubusercontent.com/assets/1656037/8626850/6f276a42-271d-11e5-843d-e6443e3396e8.PNG)

This happens due to the templates used in the Menu Widget.

**Comment by maxji777** [comment]
the fix actually works

**Comment by trntv** [comment]
I'm thinkng about implementing it using standard ``Menu::labelTemplate``
