### ISSUE TITLE
Not able to access user settings 

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#231]
{domain}/user/default/index is rendering a blank view.

Looks like an issue in frontend/modules/user/controllers/DefaultController actionIndex() usage of Yii::$app->user->identity->userProfile.

**Comment by trntv** [comment]
what issue do you mean?

**Comment by davidjeddy** [comment]
When accessing http://(domain).moffitt/user/default/index the VW renders a blank white page.

**Comment by XzAeRo** [comment]
I have the latest version installed in a fresh environment, and that view is loading properly.
Are you using the debug tools under a dev environment? Do they throw any error or exception?

**Comment by davidjeddy** [comment]
Was able to narrow it down. this happens when the ENV is running PHP5.4 instead of the required 5.5

Go ahead and close. Not really an issue.
