### ISSUE TITLE
storage SSL url problem

### ISSUE THREAD

**Issue by maxji777** [trntv/yii2-starter-kit#232]
Hey Eugene, 

thanks for all the hard work!

when using SSL, all images are shown using http connection, cause image url is taken from database.
so workaround would be saving the url without http scheme prefix, fastest way to do it - is to configure the .env file without http: prefix

FRONTEND_URL    = //yii2-starter-kit.dev
BACKEND_URL     = //backend.yii2-starter-kit.dev
STORAGE_URL     = //storage.yii2-starter-kit.dev

this way browser will not display any ssl problems.

**Comment by trntv** [comment]
Thank you for the PR, but it would be better if you'll create a fix for a docs, not for a .env.dist
``.env.dist`` is an example, so it should be as obvious as possible
