### ISSUE TITLE
Backend template exposed to users

### ISSUE THREAD

**Issue by golles** [trntv/yii2-starter-kit#242]
Reproduce:
-logout
-login (in frontend) as user (user - user)
-go to backend url by typing in the address bar.

You'll see a Forbidden (#403) page inside the backend template (including menu items)

I think it should show a full page 403 error.
(behavior when not logged in is fine: showing the login form)

**Comment by XzAeRo** [comment]
I can't reproduce the problem. Are you using the latest version?

**Comment by golles** [comment]
I'll try to reproduce on a fresh installation, but this is what I get in my custom installation:

![scnrsht](https://cloud.githubusercontent.com/assets/2211503/8917884/20cbacbe-34b5-11e5-835a-3e479c06c0ae.png)

**Comment by golles** [comment]
confirmed on a fresh installation
![schermafbeelding 2015-07-28 om 21 31 47](https://cloud.githubusercontent.com/assets/2211503/8941486/218d6c1c-3570-11e5-8673-ffc918a3acd9.png)

**Comment by XzAeRo** [comment]
What environment are you using?

**Comment by golles** [comment]
as in `YII_ENV`? both prod and dev give me the above result.

**Comment by XzAeRo** [comment]
I give up. I can't reproduce the problem.

Even with cleared cookies and no cache, I can't reproduce the problem. Maybe this is a system-dependent problem.

**Comment by golles** [comment]
https://github.com/yiisoft/yii2/blob/master/framework/filters/AccessControl.php#L146-L153

I think it's that.
the user is logged in, so the framework throws 403 in the default template.
What I need to know; how can I let that exception happen in another template?

**Comment by trntv** [comment]
in standard installation non manager user can't log into backend at all

template is set here:
https://github.com/trntv/yii2-starter-kit/blob/master/backend/controllers/SiteController.php#L26

**Comment by golles** [comment]
Ok, then is is easy to fix:
change that line to:
```
$this->layout = Yii::$app->user->can('loginToBackend') ? 'common' : 'base';
```

The current line won't handle an authenticated user because it isn't a guest anymore. So checking on the users permission is the only right thing.
