### ISSUE TITLE
cannot create symlinks

### ISSUE THREAD

**Issue by des1roer** [trntv/yii2-starter-kit#245]
для запуска на OpenServer нужно запускать OpenServer с админ правами. почему так?

**Comment by trntv** [comment]
Не видел windows в общем и openserver уже года 3-4, но для вас погуглил. 
Функция symlink() которая используется в AssetManager yii2, возвращает false если интерпретатор не запущен с права администратора.

**Comment by des1roer** [comment]
спасибо

**Comment by makeloo** [comment]
Такая же проблема. Запустил опенсервер с правами админа. И все заработало.
