### ISSUE TITLE
Caches in the same cache folder?

### ISSUE THREAD

**Issue by golles** [trntv/yii2-starter-kit#247]
I'm wondering why the frontend/backend cache is stored into common/runtime?
Shouldn't it be in their own runtime folders?

https://github.com/trntv/yii2-starter-kit/blob/master/common/config/base.php#L161

I think it should be changed to:
```
'cachePath' => '@app/runtime/cache'
```

**Comment by trntv** [comment]
Why is should be different folders? What advantages it gives? Or what problems solve?

**Comment by golles** [comment]
I don't think either options has any advantage or disadvantage. default value is 
```
'@runtime/cache'
```
https://github.com/yiisoft/yii2/blob/master/framework/caching/FileCache.php#L35-L39

I think it does makes sense because frontend and backend are theoretically different applications.
Or will the default value break the backend cache controller?

**Comment by trntv** [comment]
> Or will the default value break the backend cache controller?
yep. common/runtime is an easiest way to control frontend cache from backend or console and for most use cases only frontend cache matters

**Comment by golles** [comment]
@trntv check this: https://github.com/phemellc/yii2-settings/issues/1#issuecomment-57094094

**Comment by trntv** [comment]
yes, i'm using such components for urlManager - https://github.com/trntv/yii2-starter-kit/blob/master/common/config/base.php#L127

I said it was an easiest way, not a best one, but i'll think about the way to improve it.

**Comment by golles** [comment]
Ok, just wanted to make sure that you are aware of it.
