### ISSUE TITLE
Use Ansible to deploy a standard system environment

### ISSUE THREAD

**Issue by XzAeRo** [trntv/yii2-starter-kit#249]
Just a suggestion.

Ansible is a tool that, with a proper configuration, will allow to install, check and deploy for a specific environment installation (even launching Vagrant). [See here for a brief example](https://www.digitalocean.com/community/tutorials/how-to-deploy-a-basic-php-application-using-ansible-on-ubuntu-14-04).

I believe is a good idea to add this to the project, because this will allow to download, install and deploy the application "in a single click", which is ideal for a "starter kit".

What do you think?
I will be testing this and I can create a PR if you want.

Happy coding!

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/issues/192
