### ISSUE TITLE
[Type Doc] How config suffix urlmanager

### ISSUE THREAD

**Issue by dungphanxuan** [trntv/yii2-starter-kit#252]
Hi, i try to config suffix with syntax  'suffix' => '.html', on _urlManager file. So it not work.
How can i ifx it.

**Comment by trntv** [comment]
It works fine on clean installation. Just add ``'suffix' => '.html'`` suffix here:
https://github.com/trntv/yii2-starter-kit/blob/master/frontend/config/_urlManager.php#L5
