### ISSUE TITLE
Using Docker -  Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No route to host'  in /app/vendor/yiisoft/yii2/db/Connection.php:534

### ISSUE THREAD

**Issue by rowasc** [trntv/yii2-starter-kit#258]
Hi, I am facing this error while running 

``docker-compose run cli app/setup``

I would like to know if I am supposed to change the database info in the .env file, or what I should do to make the setup work . 

This is how mine looks like (with the .env file copied from .env.docker.dist)

DB_DSN           = mysql:host=db;port=3306;dbname=yii2-starter-kit
DB_USERNAME      = root
DB_PASSWORD      = root
DB_TABLE_PREFIX  =

My docker-compose ps output is: 
         Name                   Command           State                  Ports              
-------------------------------------------------------------------------------------------
yii2starterkit_cli_1     /app/console/yii        Exit 255                                   
yii2starterkit_db_1      /entrypoint.sh mysqld   Up         127.0.0.1:33060->3306/tcp       
yii2starterkit_fpm_1     php-fpm                 Up         9000/tcp                        
yii2starterkit_nginx_1   nginx -g daemon off;    Up         443/tcp, 127.0.0.1:8000->80/tcp 

Additional info: I cannot access the app in the 8000 port either.
Netstat output: 

``sudo netstat -tulpn|grep 80``
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      12971/docker-proxy  
tcp6       0      0 :::80                   :::*                    LISTEN      3094/httpd         

Thanks!

**Comment by rowasc** [comment]
Additional info: 
``mysql -uroot -proot --host 127.0.0.1 --port 33060``
This works, so mysql is running.

**Comment by rowasc** [comment]
I changed 
DB_DSN = mysql:host=db;port=3306;dbname=yii2-starter-kit
to 
DB_DSN = mysql:host=127.0.0.1;port=3306;dbname=yii2-starter-kit

And now I am getting SQLSTATE[HY000] [2002] Connection refused

Which I assume is because of the bind mysql configuration, but I don't know how to change it with docker.

**Comment by trntv** [comment]
you should leave ```host=db``` because cli container is linked to db here:
https://github.com/trntv/yii2-starter-kit/blob/master/docker-compose.yml#L10

Try to rebuild images: ``docker-compose build``

What OS dou you use?

**Comment by rowasc** [comment]
Hi, thanks but this is not working. I've got the latest version of the docker compose, 
Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] No route to host'
I'm on Fedora  20 (Heisenbug)
Regards, 
Romina

**Comment by trntv** [comment]
show result of ``docker-compose ps``

**Comment by rowasc** [comment]
Sure: 

``$ docker ps``
``CONTAINER ID        IMAGE                      COMMAND                CREATED             STATUS              PORTS                             NAMES``
``0b7c712d32f6        nginx:latest               "nginx -g 'daemon of   31 seconds ago      Up 29 seconds       443/tcp, 127.0.0.1:8000->80/tcp   yii2starterkitrowasc_nginx_1   ``
``91fc4641c1f8        yii2starterkitrowasc_fpm   "php-fpm"              38 seconds ago      Up 36 seconds       9000/tcp                          yii2starterkitrowasc_fpm_1     ``
``f2cb1cf6d4ae        mysql:5.6                  "/entrypoint.sh mysq   51 seconds ago      Up 49 seconds       127.0.0.1:33060->3306/tcp         yii2starterkitrowasc_db_1      ``
