### ISSUE TITLE
Ошибка 400

### ISSUE THREAD

**Issue by svolga** [trntv/yii2-starter-kit#261]
При попытке в backend записать в статьи тексты размером, например, 100Kb, появляется ошибка 400.
Пришлось в конфиге отключить валидацию csrf. 

        'request' => [
            'cookieValidationKey' => getenv('BACKEND_COOKIE_VALIDATION_KEY'),
//
            'enableCsrfValidation' => false,
            'enableCookieValidation' => true
//
        ],
Как можео пофиксить эту ошибку, но не отключать csrf?

**Comment by trntv** [comment]
Это ошибка от неправильной установки или конфигурации, так что чтобы фиксить надо сначала понять как у вас все установлено? Без поддоменов я так понимаю?

**Comment by trntv** [comment]
Так как тут тишина - закрываю

**Comment by sokollondon** [comment]
Аналогична проблема.  Только ошибка появляется не всегда. Если появлялась приходилось нажимать в браузере кнопку назад и отправлять форму заново. 
Помогло решение @svolga

Установлено без поддоменов.
Yii v2.0.10
