### ISSUE TITLE
Fail to composer update to install packages

### ISSUE THREAD

**Issue by heartshare** [trntv/yii2-starter-kit#264]
In yii2 starter kit 
I added to require but fail to install 
   "itzen/yii2-setting": "*"

But 
Default yii2-app template ok 
yii2-app-advanced]# composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing itzen/yii2-setting (dev-master 3cc79b0)
    Cloning 3cc79b096a31827407982bc0f14a441703e90f68

Any setting need to update for install packages in yii2-starter-kit? thanks

**Comment by trntv** [comment]
default settings should be ok.

By the way:
https://github.com/trntv/yii2-starter-kit/blob/master/backend/controllers/SiteController.php#L30
https://github.com/trntv/yii2-starter-kit/blob/master/backend/views/site/settings.php
http://backend.yii2-starter-kit.terentev.net/site/settings
