### ISSUE TITLE
PDO Error - Null sent to Probe

### ISSUE THREAD

**Issue by dbd5** [trntv/yii2-starter-kit#266]
Hi,

I've got a curious error I can't figure out. 

I get  the following error when I click system-information from the backend control panel

'Argument 1 passed to probe\provider\AbstractProvider::getDbType() must be an instance of PDO' , null given, called in /var/localhost/backend/views/system-information/index.php on line 116 and defined.

The offending code seems to be the following;

                        <dt><?php echo Yii::t('backend', 'DB Type') ?></dt>
                        <dd><?php echo $provider->getDbType(Yii::$app->db->pdo) ?></dd>

                        <dt><?php echo Yii::t('backend', 'DB Version') ?></dt>
                        <dd><?php echo $provider->getDbVersion(Yii::$app->db->pdo) ?></dd>

My DB connection code is as follows;

    'components' => [
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => getenv('DB_DSN'), // Disable this and enable the next line for codeception tests
            // 'dsn' => 'mysql:host=localhost;dbname=eng1_tests',
            'username' => getenv('DB_USERNAME'),
            'password' => getenv('DB_PASSWORD'),
            'tablePrefix' => getenv('DB_TABLE_PREFIX'),
            'charset' => 'utf8',
            'enableSchemaCache' => YII_ENV_PROD,
        ], 
    ....

According to the manual (http://www.yiiframework.com/doc-2.0/guide-db-dao.html), once a DB connection is made as an application component, you can access it using Yii::$app->db

Also Yii::$app->db has a pdo object, it's not clear why the expression returns null.

Any help will be appreciated

Regards,

Adam

**Comment by rowasc** [comment]
Hi, I was not able to reproduce this locally. Can you post the results of  var_dump(Yii::$app->db->pdo);  ? Also, what version of the repo and of probe are you on? 

Thanks

**Comment by dbd5** [comment]
Hi @rowasc,

The results of var_dump(Yii::$app->db->pdo); 
object(PDO)[72]

Probe Version
0.2

Not sure repo version. I installed with the usual 
composer create-project --prefer-dist --stability=dev trntv/yii2-starter-kit

Regards,

Adam

**Comment by trntv** [comment]
What is your OS?

**Comment by dbd5** [comment]
Ubuntu Linux 14.04 hosted in a Vagrant/Virtualbox VM on a Mac - so Linux

**Comment by trntv** [comment]
To be honest, i can't repeat your problem on any confugiration i tried. Sorry.

**Comment by dbd5** [comment]
Ok, thanks

**Comment by dbd5** [comment]
Hi Eugene,

Just to leave a note to say that there might be something to this issue so you can have another look when you have time.

With my new installation, the curious thing is that this issue happens now only mostly in Chrome browser, it has happened once in Microsoft edge and Zero times in Safari.  All in the same client machine

Regards,


A

**Comment by nedarta** [comment]
I replicated this: Log out, try access Probe without login (In my case /admin/information path) and this happens (still in 2020). If you're not logged in - "Argument 1 passed to Probe\Provider\AbstractProvider::getDbType() must be an instance of PDO"
