### ISSUE TITLE
Проблемы nginx-конфигурации при запуске под вагрантом

### ISSUE THREAD

**Issue by rugabarbo** [trntv/yii2-starter-kit#274]
При запуске под вагрантом nginx отказывается воспринимать эту строчку конфигурации:
https://github.com/trntv/yii2-starter-kit/blob/master/vhost.conf.dist#L99

Под вагрантом используется Ubuntu, а поэтому более работоспособным вариантом является:
```server unix:/var/run/php5-fpm.sock;```

Тем не менее я не решаюсь вносить это исправление в общий репозиторий. Я не знаю, как поведут себя другие виды окружения с этой строчкой (docker, ручная установка). Если нежелательно использовать сокеты для всех окружений, то решением может стать отдельная конфигурация nginx для вагранта.

Как лучше сделать?

**Comment by trntv** [comment]
Этот конфиг написан под docker.
