### ISSUE TITLE
internal server error

### ISSUE THREAD

**Issue by meizoev** [trntv/yii2-starter-kit#276]
picture not load,and i check the inspect element in chrome i got this msg:

http://storage.starter.anke/cache/1/sR1XI6o0zXFAeKkMUn0gEPf2AEicnEcx.jpg?w=200&s=4160d02a2f7c892784f1f31f9bdd901c Failed to load resource: the server responded with a status of 500 (Internal Server Error)
 and when i open that link. i got msg "Not Supported – yii\base\NotSupportedException"

i think the problem is in server, but i dunno how to clear the problem. would you help me?

**Comment by trntv** [comment]
run application in dev mode and give me a stack trace for this error. I'll try to figure out why this is happen.

**Comment by meizoev** [comment]
the app run in dev mode. i dunno how to show the stack trace.. but there is no stacktrace in admin log in backend, neither in front page.  than i check the thumbnail file in the storage/cache/   , there is no one file in there, its mean the thumbnail doesnt exist... sorry for your time

**Comment by trntv** [comment]
Check that you have ``exif`` extension installed

**Comment by meizoev** [comment]
you mean php extension right? ok solved... thanks
