### ISSUE TITLE
filekit не удаляет файл изображения после сохранения модели

### ISSUE THREAD

**Issue by jekaspekas** [trntv/yii2-starter-kit#277]
Приветствую, спасибо за удобный загрузчик аватарок!
Опишу на примере http://backend.yii2-starter-kit.terentev.net/article/update.
Удаление файла и записей в полях БД (thumbnail_base_url и thumbnail_path) работает до сохранения модели, однако после сохранения модели удаляется лишь запись в БД а сам файл остается.
Прошу прощения за обращение не на английском.

**Comment by denoll** [comment]
Добрый день, такая же проблема, но при множественном сохранении картинок/файлов
строки из БД удаляются, а файлы физически не удаляются, после того как записи были сохранены.
