### ISSUE TITLE
In Backend: Not able to allow access on actions [ Issued #217 opened on Jun 18]

### ISSUE THREAD

**Issue by mohdbashir** [trntv/yii2-starter-kit#282]
I have installed fresh starter-kit for new project and made the test module to check permission issue for module is working or not. Still i am facing same problem [Issued #217 opened on Jun 18].

My concern is i would like to create a new module in the backend and want to apply the access on action of module controller.

Please give me example of code to achieve the same.

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/blob/master/backend/config/web.php#L64

```
[
     'controllers' => ['your-module/module-controller'],
     'allow' => false,
     'roles' => ['manager'],
]
```

but you have to write rules for every controller in your module, because AccessRule doesn't support ``module`` rule.

**Comment by mohdbashir** [comment]
My module name : holidays
Controller Name: HolidayController

Want to do: Only administrator having access to holidays module.

I write rule below code in controller but not working.

      namespace backend\modules\holidays\controllers;
     class HolidayController extends Controller
    {
        public function behaviors()
        {
     return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            
            'access' => [
                'class' => AccessControl::className(),                
                'rules' => [                   
                    [
						'actions' => ['index'],
						'allow' => true,
						'roles' => ['@'],
						'matchCallback' => function ($rule, $action) {
							return Yii::$app->user->can('administrator');
						}                      
                    ],                   
                    
                ],
            ],
            
        ];
   }
---------------

As you mentioned above try this below code also in file : backend/config/web.php
It is also not working.

                   [
				 'controllers' => ['holidays/holiday'],
				 'actions'=>['index'],
				 'allow' => false,
				 'roles' => ['manager'],
			]


Please advice me how to write rule in module-controller. See also my previous issue detail for help [Issued #217 opened on Jun 18]

**Comment by trntv** [comment]
You don't need to write anything inside your module.

This rule:
```
[
             'controllers' => ['holidays/holiday'],
             'actions'=>['index'],
             'allow' => false,
             'roles' => ['manager'],
 ]
```
will disallow manager to use this module but you still needs to allow it to administrator explicity:
```
[
             'controllers' => ['holidays/holiday'],
             'actions'=>['index'],
             'allow' => false,
             'roles' => ['manager'],
 ],
[
             'controllers' => ['holidays/holiday'],
             'allow' => true,
             'roles' => ['administrator'],
 ]
```
