### ISSUE TITLE
The file or directory to be published does not exist

### ISSUE THREAD

**Issue by dbd5** [trntv/yii2-starter-kit#285]
Hi Eugene, All;

Not sure - Has there been a rename of bower to bower-asset in vendors folder?

I just did a fresh install per instructions and on attempting to run the application, I get the following error:

Invalid Parameter – yii\base\InvalidParamException
The file or directory to be published does not exist: /var/www/trntv/vendor/bower/bootstrap/dist

On checking, I see there is rather /vendor/bower-asset instead of /vendor/bower.
I did a quick fix by making a copy of /vendor/bower-asset and renaming to /vendor/bower

Not a big deal but I'm reporting this because this has never happened with previous installs of trntv/yii2-starter-kit

Regards,

Adam

**Comment by trntv** [comment]
thank you, i'll check it, but this string should do all the magic:
https://github.com/trntv/yii2-starter-kit/blob/master/composer.json#L68

**Comment by dbd5** [comment]
Hi Eugene,

Yes - the referenced string is exactly what I have in the composer.json right after a clean install.

Regards
