### ISSUE TITLE
Article thumbnail not visible in frontend

### ISSUE THREAD

**Issue by golles** [trntv/yii2-starter-kit#286]
Hi,

I'm having the same problem as described here https://github.com/trntv/yii2-starter-kit/issues/127
But I'm not able to reopen that issue.

This is what I see in html img element:
```
http://localhost/my-website/storage/my-website/cache/1/T_3kxQWwPVnhtscRUuMAh0uQUHro6D5c.jpg?w=200&s=99e2e1ea6681db5a8e81fb2ae29adae7
```
If I open that link I get this response:
```
Bad Request (#400)

Missing required parameters: path
The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.
```

If  I change it to:
```
http://localhost/workspace/my-website/storage/cache?path=1/T_3kxQWwPVnhtscRUuMAh0uQUHro6D5c.jpg&w=100&s= 99e2e1ea6681db5a8e81fb2ae29adae7
```
I get the following response:
```
Bad Request (#400)

The above error occurred while the Web server was processing your request.

Please contact us if you think this is a server error. Thank you.
```

I have really no clue why it isn't working, let me know if you need more details.

**Comment by meizoev** [comment]
show the env file.  and check the php extensions that required was installed

**Comment by golles** [comment]
I've changed urls in .env slightly, I have it like this:
```
# Urls
# ----
DOMAIN          = //localhost/
FRONTEND_PATH   = my-website
BACKEND_PATH    = my-website/backend
STORAGE_PATH    = my-website/storage
FRONTEND_URL    = ${DOMAIN}${FRONTEND_PATH}
BACKEND_URL     = ${DOMAIN}${BACKEND_PATH}
STORAGE_URL     = ${DOMAIN}${STORAGE_PATH}
```

What extensions should I check?

**Comment by meizoev** [comment]
extension "exif" , "fileinfo"

**Comment by yiioverflow** [comment]
What about path to storage/web ?

**Comment by golles** [comment]
@meizoev exif 1.4 is enabled.

@yiioverflow I'm not sure what setting you are revering too, so I'll post some where storage is mentioned.

frontend/config
-nothing

common/config/base.php
```
        'glide' => [
            'class' => 'trntv\glide\components\Glide',
            'sourcePath' => '@storage/web/source',
            'cachePath' => '@storage/cache',
            'urlManager' => 'urlManagerStorage',
            'maxImageSize' => getenv('GLIDE_MAX_IMAGE_SIZE'),
            'signKey' => getenv('GLIDE_SIGN_KEY')
        ],
...
        'fileStorage' => [
            'class' => '\trntv\filekit\Storage',
            'baseUrl' => '@storageUrl/source',
            'filesystem' => [
                'class' => 'common\components\filesystem\LocalFlysystemBuilder',
                'path' => '@storage/web/source'
            ],
            'as log' => [
                'class' => 'common\behaviors\FileStorageLogBehavior',
                'component' => 'fileStorage'
            ]
        ],
```

common/config/bootstrap.php
```
// Path aliases
Yii::setAlias('@base', realpath(__DIR__.'/../../'));
Yii::setAlias('@common', realpath(__DIR__.'/../../common'));
Yii::setAlias('@frontend', realpath(__DIR__.'/../../frontend'));
Yii::setAlias('@backend', realpath(__DIR__.'/../../backend'));
Yii::setAlias('@console', realpath(__DIR__.'/../../console'));
Yii::setAlias('@storage', realpath(__DIR__.'/../../storage'));
Yii::setAlias('@tests', realpath(__DIR__.'/../../tests'));

// Url Aliases
Yii::setAlias('@frontendUrl', getenv('FRONTEND_URL'));
Yii::setAlias('@backendUrl', getenv('BACKEND_URL'));
Yii::setAlias('@storageUrl', getenv('STORAGE_URL'));
```

storage/config/base.php
```
    'id' => 'storage',
    'basePath' => dirname(__DIR__),
    'defaultRoute' => 'glide/index',
    'controllerMap' => [
        'glide' => '\trntv\glide\controllers\GlideController'
    ],
    'components' => [
        'urlManager'=>require(__DIR__.'/_urlManager.php'),
        'glide' => [
            'class' => 'trntv\glide\components\Glide',
            'sourcePath' => '@storage/web/source',
            'cachePath' => '@storage/cache',
            'maxImageSize' => getenv('GLIDE_MAX_IMAGE_SIZE'),
            'signKey' => getenv('GLIDE_SIGN_KEY')
        ]
    ]
```

**Comment by golles** [comment]
Update:

If I change the storage url manager to not have pretty urls ('enablePrettyUrl'=>false)
it does no longer complain about the missing path argument but it throws an exception on this line: https://github.com/trntv/yii2-glide/blob/master/src/actions/GlideAction.php#L37
It happens when I go to this url:
http://localhost/my-website/storage/my-website/frontend/web/index.php?r=glide%2Findex&path=1%2FT_3kxQWwPVnhtscRUuMAh0uQUHro6D5c.jpg&w=200&s=9a201aede0aeb8408e0e2990ff50f8ef

I've looked a bit deeper into the code and I found out that it goes wrong on validating the request.
It throws an exception because the following if is failing:
/home/x/my-website/vendor/league/glide/src/Http/Signature.php
```
if ($request->get('s') !== $this->generateSignature($request->getPathInfo(), $request->query->all())) {
    throw new SignatureException('Signature is not valid.');
}
```

**Comment by Insolita** [comment]
has similar problem, when tried to use as
```php
 $imgurl= \Yii::$app->glide->createSignedUrl([
     'glide/index',
     'path' => $path,
     'w' => 140
 ], true); //with false - fail too
echo Html::img($imgurl,  ['class' => 'thumbnail']);
```
Signature validation fail, 
But this - work well
```php
$imgurl = \Yii::$app->urlManagerStorage->createAbsoluteUrl([
            'glide/index',
            'path' => $path,
            'w' => 140
        ]);
echo Html::img(\Yii::$app->glide->signUrl($imgurl), ['class' => 'thumbnail']);
```

**Comment by golles** [comment]
Your suggestions still fails for me, because the following if statement in
 
/home/x/my-website/vendor/league/glide/src/Http/Signature.php
```
if (is_null($request->get('s'))) {
    throw new SignatureException('Signature is missing.');
}
````

**Comment by Insolita** [comment]
so..try set in your config SIGN KEY directly 
in storage/config/base.php  and common/config/base.php
```php
 'glide' => [
            'class' => 'trntv\glide\components\Glide',
            'sourcePath' => '@storage/web/source',
            'cachePath' => '@storage/cache',
            'maxImageSize' => getenv('GLIDE_MAX_IMAGE_SIZE'),
            'signKey' => 'MyRandomKey'  // instead of getenv('GLIDE_SIGN_KEY') 
        ]
```
put in any view 
```php
<?php
$imgurl = \Yii::$app->urlManagerStorage->createAbsoluteUrl([
            'glide/index',
            'path' => $path,
            'w' => 140
        ]);
echo \Yii::$app->glide->signUrl($imgurl).'<br/>';
echo \yii\helpers\VarDumper::dumpAsString(Yii::$app->glide->getHttpSignature())
?>
```
what you see ? Is 's' parameter present in generated signed url?

**Comment by golles** [comment]
That didn't help.

I've been debugging the Signature generateSignature method.

This is what I get when the image is being verified (enablePrettyUrl=false)
(http://localhost/my-website/storage/web/index.php?r=glide%2Findex&path=1%2FT_3kxQWwPVnhtscRUuMAh0uQUHro6D5c.jpg&w=200&s=39914f10fec14693d474c06ccbf8c07f)
```
generateSignature('/my-website/storage/web/index.php', Array ( [r] => glide/index [path] => 1/T_3kxQWwPVnhtscRUuMAh0uQUHro6D5c.jpg [w] => 200 [s] => 39914f10fec14693d474c06ccbf8c07f ))
````

When I have enablePrettyUrl=true
It complains that var path is not set
HTTP400, Bad Request:"Missing required parameters: path" (in GlideAction run($path))

Next when the signed url is generated:

This is with enablePrettyUrl=false
```
generateSignature('/index.php', Array ( [path] => 1/T_3kxQWwPVnhtscRUuMAh0uQUHro6D5c.jpg [w] => 200 ))
```

This is with enablePrettyUrl=true
```
generateSignature('/my-website/storage/my-website/cache/1/T_3kxQWwPVnhtscRUuMAh0uQUHro6D5c.jpg', Array ( [w] => 200 ))
```

Any more suggestions?

**Comment by meizoev** [comment]
show me your .env file, and the htdocs setting

**Comment by meizoev** [comment]
can you show me your .env file and a stack trace for this error...

**Comment by meizoev** [comment]
i suggest you should try virtual host and configure the env. based on your vhost document root... but before that you may show us your stack trace

**Comment by trntv** [comment]
I didn't test glide signatures with enablePrettyUrl=false, and as i remember, they would not work because of Glide sign algorithm. The only thing i can help, to add an ability to turn of signature verification at all.

**Comment by dungphanxuan** [comment]
Hello, how can i redirect 403 when access /source folder in storage.
Example: http://storage.yii2-starter-kit.terentev.net/source/1/
My app when access in source. will return list file. So i want to fix it. thank

**Comment by trntv** [comment]
```
'components' => [
    ...
    'glide' => [
        'class' => 'trntv\glide\components\Glide',
        ...
        'signKey' => false // "false" if you do not want to use HTTP signatures
    ],
    ...
]
```

**Comment by Nurpeyis** [comment]
Yii::$app->glide->createSignedUrl([
                'glide/index',
                'path' => $this->thumbnail_path,
                'w' => 50,
                'h' => 50,
                'fit' => 'crop'
            ], true)

returns incorrect url. 
/storage/**backend/web/**cache/1/7cNGTANuB0asis-wxd_ofBb3L0c4P_6m.png?w=50&h=50&fit=crop&s=31293a69b7ed3136a08e4212a4706b5a
who is know where to change to fix.
