### ISSUE TITLE
Facebook Connect without email results in 'broken' account

### ISSUE THREAD

**Issue by iadj** [trntv/yii2-starter-kit#290]
It's possible to disable the email permission in the Facebook Connect prompt (and other oAuth prompts).
When you disable email (or username) retrieval through any oAuth network and click Connect, you get an error and you'll be unable to use the website, or log in or out.

Registering with an oAuth provider without email/username should have a following step where you must enter an email/username so as not to break the authentication process.

**Comment by yiioverflow** [comment]
Me too had the same issue. It's possible to solve. But I think it's better to disable email request.

**Comment by iadj** [comment]
@yiioverflow Disabling emails would disable the ability to reset your password or receive newsletters etc. You could always make it a non-requirement, but as for the default set-up it would be good to solve the issue and let users set their username/email if it couldn't be retrieved by oAuth.

**Comment by trntv** [comment]
i cannot cover all use cases for all OAuth providers. You can change any logic in SignInController::successOAuthCallback to fit your needs. 

btw, PRs are always welcome ;-)
