### ISSUE TITLE
how can i add permissions to role?

### ISSUE THREAD

**Issue by sasiarjun** [trntv/yii2-starter-kit#292]
Is there any option to add permissions and assign permissions to role using front end? how can i integrate the front end for rbac? please help me to do the frontend for roles and permissions

**Comment by sasiarjun** [comment]
is there any solution please help me to add front end for rbac?

**Comment by trntv** [comment]
```php console/yii rbac-migrate/create some_new_permission_migration```
Then you should describe your new permissions in the created file, then run
```php console/yii rbac-migrate```
