### ISSUE TITLE
Ошибка при создании статьи

### ISSUE THREAD

**Issue by porcelanosa** [trntv/yii2-starter-kit#294]
После установки захожу в раздел статей. Пытаюсь добавить новую статью.
ReflectionException
...
Class trntv\yii\datetimepicker\MomentAsset does not exist
1. in D:\OpenServer\OpenServer\domains\starter-kit.local\vendor\yiisoft\yii2\di\Container.php at line 415
406407408409410411412413414415416417418419420421422423424     * @return array the dependencies of the specified class.
     */
    protected function getDependencies($class)
    {
        if (isset($this->_reflections[$class])) {
            return [$this->_reflections[$class], $this->_dependencies[$class]];
        }
 
        $dependencies = [];
        $reflection = new ReflectionClass($class);
 
        $constructor = $reflection->getConstructor();
        if ($constructor !== null) {
            foreach ($constructor->getParameters() as $param) {
                if ($param->isDefaultValueAvailable()) {
                    $dependencies[] = $param->getDefaultValue();
                } else {
                    $c = $param->getClass();
                    $dependencies[] = Instance::of($c === null ? null : $c->getName());
2. in D:\OpenServer\OpenServer\domains\starter-kit.local\vendor\yiisoft\yii2\di\Container.php at line 415 – ReflectionClass::__construct('trntv\yii\datetimepicker\MomentA...')
...

**Comment by trntv** [comment]
Давно устанавливали приложение? Попробуйте выполнить ``composer update``
