### ISSUE TITLE
Ошибка в разделе "Информация о системе" 

### ISSUE THREAD

**Issue by soulhunter1987** [trntv/yii2-starter-kit#295]
Undefined index: kern.boottime

Trace:
exception 'yii\base\ErrorException' with message 'Undefined index: kern.boottime' in /Users/dmitry/Development/Projects/StarterKit/vendor/trntv/probe/src/provider/AbstractBsdProvider.php:137
Stack trace:
#0 /Users/dmitry/Development/Projects/StarterKit/vendor/trntv/probe/src/provider/AbstractBsdProvider.php(137): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/Users/dmitry/D...', 137, Array)
#1 /Users/dmitry/Development/Projects/StarterKit/backend/views/system-information/index.php(154): probe\provider\AbstractBsdProvider->getUptime()
#2 /Users/dmitry/Development/Projects/StarterKit/vendor/yiisoft/yii2/base/View.php(325): require('/Users/dmitry/D...')
#3 /Users/dmitry/Development/Projects/StarterKit/vendor/yiisoft/yii2/base/View.php(247): yii\base\View->renderPhpFile('/Users/dmitry/D...', Array)
#4 /Users/dmitry/Development/Projects/StarterKit/vendor/yiisoft/yii2/base/View.php(149): yii\base\View->renderFile('/Users/dmitry/D...', Array, Object(backend\controllers\SystemInformationController))
#5 /Users/dmitry/Development/Projects/StarterKit/vendor/yiisoft/yii2/base/Controller.php(374): yii\base\View->render('index', Array, Object(backend\controllers\SystemInformationController))
#6 /Users/dmitry/Development/Projects/StarterKit/backend/controllers/SystemInformationController.php(35): yii\base\Controller->render('index', Array)
#7 [internal function]: backend\controllers\SystemInformationController->actionIndex()
#8 /Users/dmitry/Development/Projects/StarterKit/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#9 /Users/dmitry/Development/Projects/StarterKit/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#10 /Users/dmitry/Development/Projects/StarterKit/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction('index', Array)
#11 /Users/dmitry/Development/Projects/StarterKit/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction('system-informat...', Array)
#12 /Users/dmitry/Development/Projects/StarterKit/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#13 /Users/dmitry/Development/Projects/StarterKit/backend/web/index.php(23): yii\base\Application->run()
#14 {main}

OSX 10.9, PHP 5.5

**Comment by trntv** [comment]
Вообще ошибка в библиотеке которая получает данные о системе: 
https://github.com/trntv/probe

Если бы у меня был Mac под рукой, я бы возможно и смог найти причину, но в его отсутствие вам придется попытатся отдебажить код самому и поделится фиксом :-)

**Comment by trntv** [comment]
https://github.com/trntv/probe/issues/7
