### ISSUE TITLE
New OAuth2 client redirect_uri

### ISSUE THREAD

**Issue by alladas** [trntv/yii2-starter-kit#298]
Hi @trntv,
This is rather a question. Not an issue.
I am trying to add a new OAuth Client for Twitch.
Everything seems working fine apart of Twitch not allowing the redirect_uri to be http://[my-domain]**/user/sign-in/oauth?client=twitch**. With this url Twicth is sending back a redirect_mismatch error.
Changing the redirect_uri to http://[my-domain]**/user/sign-in/oauth** seems to work but this leads to a 404 error.
I wonder what you would advice to sort this out.
In advance thanks.

**Comment by trntv** [comment]
Twitch doesn't allow query params in uri?

BTW, you can always remove them, by writing a simple rule to transform url to something like this:
``http://[my-domain]/user/sign-in/oauth/twitch``

Current url rules:
https://github.com/trntv/yii2-starter-kit/blob/master/frontend/config/_urlManager.php

Docs about writing them:
https://github.com/yiisoft/yii2/blob/master/docs/guide/runtime-routing.md#url-rules-
