### ISSUE TITLE
How to update yii2-starter-kit?

### ISSUE THREAD

**Issue by keltstr** [trntv/yii2-starter-kit#301]
Hi, well done!
I installed yii2-starter-kit month ago, and
How to update yii2-starter-kit now?
"composer update" updated /vendor only.
I need implement some changes, for example https://github.com/trntv/yii2-starter-kit/issues/289
Thanks.

**Comment by golles** [comment]
This is how I do it:

Go to the commit history: https://github.com/trntv/yii2-starter-kit/commits/master
Right click on the commit hash (2nd button of each commit).
Copy it to your browser, and add ".patch" to the end of the url.
Download the patch file and import that eg. with your IDE.
https://github.com/trntv/yii2-starter-kit/commit/3bcde7ba87a01c536f7abee55bbde171101e42d0.patch

If anyone has a better solution, please share.

**Comment by keltstr** [comment]
Thanks, i'll try it;
After Import patch, should appear conflicts in git ? (if I make changes)

**Comment by rowasc** [comment]
Hi. I usually run a "git pull trntv master" in the command line, it's much easier than patching by hand. 

To do this, you can modify your .git remotes so you have a "trntv" remote different from your private/public forks of this repo . 
 
Example: go to .git/config and edit to have a list like this (change it to your own repos and needs, of course) : 

[remote "trntv"]
        url = https://github.com/trntv/yii2-starter-kit.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[remote "gitfork"]
        url = https://github.com/rowasc/yii2-starter-kit.git
        fetch = +refs/heads/*:refs/remotes/origin/*

Hope this helps. 
Romina

**Comment by golles** [comment]
Thanks rowasc, I'm going to try that as well, but I have so many local changes that I'm not sure if that will work out for me.

**Comment by ddinchev** [comment]
I personally do something similar to @rowasc. I have added trntv/yii2-starter-kit as "upstream" remote. Instead of pull however, I do `git cherry-pick shaSART..shaEND`. The cherry pick will start wherever you have conflicts, you will fix them manually, `add` the changes and do `git cherry-pick --continue`.

You can also cherry pick only commits that you need, not everything, especially ones over files you know that they are sure to mess your things.

**Comment by davidjeddy** [comment]
@golles ideally your changes do not over write the starter kit canonical files, but rather over ride or extend them. This why when you pull the changes from the repo you can simply merge the changes into your code base.

**Comment by davidjeddy** [comment]
@trntv can we close this out please. Issue resolved.
