### ISSUE TITLE
published_at

### ISSUE THREAD

**Issue by Beaten-Sect0r** [trntv/yii2-starter-kit#304]
https://github.com/trntv/yii2-starter-kit/blob/master/common/models/Article.php#L116
Если не задать время публикации - то strtotime из NULL делает 0 и в базе сохраняется 0, а не дефолтное значение.

**Comment by trntv** [comment]
перед этим же задается текущее время?
https://github.com/trntv/yii2-starter-kit/blob/master/common/models/Article.php#L115

**Comment by Beaten-Sect0r** [comment]
Да.

**Comment by Beaten-Sect0r** [comment]
Вроде как не помогло.

**Comment by Beaten-Sect0r** [comment]
А если в сам виджет добавить дефолтное значение?

**Comment by trntv** [comment]
Спасибо за наводку. Суть была в том что ``strtotime(_timestamp_)`` возвращает false. Как-то сразу не учел этот момент.
