### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by dudunegrinhu** [trntv/yii2-starter-kit#307]
Hi I did the git clone and after composer install but I'm getting this error:

Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.    

  Problem 1
    - The requested package yiisoft/yii2 could not be found in any version, there may be a typo in the package name.
  Problem 2
    - Installation request for asofter/yii2-imperavi-redactor dev-master@dev -> satisfiable by asofter/yii2-imperavi-redactor[dev-master].
    - asofter/yii2-imperavi-redactor dev-master requires yiisoft/yii2 * -> no matching package found.
  Problem 3
    - Installation request for trntv/yii2-aceeditor ^2.0 -> satisfiable by trntv/yii2-aceeditor[2.0.0].
    - trntv/yii2-aceeditor 2.0.0 requires yiisoft/yii2 ~2.0 -> no matching package found.
  Problem 4
    - Installation request for trntv/yii2-glide ^1.0.0 -> satisfiable by trntv/yii2-glide[1.0.0].
    - trntv/yii2-glide 1.0.0 requires yiisoft/yii2 ~2.0.0 -> no matching package found.
  Problem 5
    - yiisoft/yii2-bootstrap 2.0.5 requires yiisoft/yii2 >=2.0.6 -> no matching package found.
    - yiisoft/yii2-bootstrap 2.0.4 requires yiisoft/yii2 >=2.0.4 -> no matching package found.
    - yiisoft/yii2-bootstrap 2.0.3 requires yiisoft/yii2 * -> no matching package found.
    - yiisoft/yii2-bootstrap 2.0.2 requires yiisoft/yii2 * -> no matching package found.
    - yiisoft/yii2-bootstrap 2.0.1 requires yiisoft/yii2 * -> no matching package found.
    - yiisoft/yii2-bootstrap 2.0.0 requires yiisoft/yii2 * -> no matching package found.
    - Installation request for yiisoft/yii2-bootstrap ^2.0.0 -> satisfiable by yiisoft/yii2-bootstrap[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
-bash-4.1$ /usr/local/bin/composer self-update

**Comment by Lordfef** [comment]
I have the same error during installation.
I try to solve by myself (not sure is correct but for me it works). I edited composer.json and substitute for example:
"yiisoft/yii2": "^2.0.7",
with
"yiisoft/yii2": "*",

and so on for each package that give error.
After that i save the composer.json modified and then i re-launch the command: composer install
and at the end it works.

**Comment by trntv** [comment]
wow, have no idea why i add 2.0.7 to composer json... it is not released yet

**Comment by alladas** [comment]
I had the same problem yesterday but got it work modifying the composer.json:
```
"minimum-stability": "dev",
"require": {
....
"asofter/yii2-imperavi-redactor": "^0.0.2",
....
```
0.0.2 is the latest release of imperavi-redactor.
Not sure it is a definitive fix but at least should help.
