### ISSUE TITLE
Retrieving first_name & last_name from Facebook Oauth2

### ISSUE THREAD

**Issue by iadj** [trntv/yii2-starter-kit#310]
The profile attributes `first_name` and `last_name` should be filled on Facebook authorization.
How would you most efficiently integrate it in in `vendor/yii2-authclient/clients/Facebook.php` (or the Sign In controller)?

**Comment by trntv** [comment]
there is an https://github.com/yiisoft/yii2-authclient repository. It is a separate official yiisoft package.

Required scope:
https://developers.facebook.com/docs/facebook-login/permissions/v2.5#reference-public_profile

**Comment by iadj** [comment]
i know, it would just be a nice feature to have in the starter kit considering the `first_name` and `last_name` attributes are already there.
