### ISSUE TITLE
Glide and filestorage. Namespace & Path

### ISSUE THREAD

**Issue by alladas** [trntv/yii2-starter-kit#311]
Hi @trntv 
After a fresh install yesterday, I could not upload any image. 
Error => exception 'yii\base\ErrorException' with message 'Class 'League\Glide\Http\SignatureFactory' not found' in /srv/www/htdocs/project.dev/vendor/trntv/yii2-glide/src/components/Glide.php:210.
Fixed the namespaces.
```
/* Begin fix - namespace
use League\Glide\Http\SignatureException;
use League\Glide\Http\SignatureFactory;
use League\Glide\Http\UrlBuilder;
use League\Glide\Http\UrlBuilderFactory;
*/
use League\Glide\Signatures\SignatureException;
use League\Glide\Signatures\SignatureFactory;
use League\Glide\Urls\UrlBuilder;
use League\Glide\Urls\UrlBuilderFactory;
/* End fix */
```

After this I found that the upload proceed to save images but their preview was leading to a 404 error. The GET seems to invoke a wrong path 
/srv/www/htdocs/project.dev/storage/source/1/abc.jpg
After extensive research without success, I ended up changing in common/config/base.php, the 'fileStorage'.
From  'baseUrl' => '@storageUrl/source' to  'baseUrl' => '@storageUrl/web/source' and it works.
```
'fileStorage' => [
            'class' => '\trntv\filekit\Storage',
            'baseUrl' => '@storageUrl/web/source', 
            'filesystem' => [
                'class' => 'common\components\filesystem\LocalFlysystemBuilder',
                'path' => '@storage/web/source'
            ],
```
That is just a report to you since my install has been hard because of Yii2 2.0.7. ;)

You are doing a great job there.
A success stories page is missing for yii2-starter-kit.

**Comment by trntv** [comment]
Hi, thank you for your report.
As i said many times, starter-kit isn't designed to work as single domain
application. That's why you are facing these problems.

Happy coding. Eugene

2015-10-27 18:37 GMT+02:00 alladas <notifications@github.com>:
