### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by uaBirder** [trntv/yii2-starter-kit#318]
Hey guys .. Tell me please how install database ... sorry, but this is my first yii install ...

**Comment by trntv** [comment]
``php console/yii app/setup`` will fill it for you. All you need is to create an empty database.

**Comment by uaBirder** [comment]
> php console/yii app/setup
Could not open input file: console/yii

What is the problem ?

**Comment by trntv** [comment]
isn't error message clear enough?
``console/yii`` is a file - https://github.com/trntv/yii2-starter-kit/tree/master/console
You should run this command from the project root.
