### ISSUE TITLE
ownModelRule example?

### ISSUE THREAD

**Issue by iadj** [trntv/yii2-starter-kit#321]
`ownModelRule` seems really useful, but I can't find any documentation on how to use it. I've also looked at generic Yii2 RBAC tutorials but couldn't get it to work. Is there an example or documentation on how to use the `ownModelRule` to easily restrict certain actions to the creator of the model (i.e. author can only edit their own post)?

**Comment by trntv** [comment]
i'll add an example to the docs

**Comment by iadj** [comment]
Thanks @trntv looking forward to it

**Comment by iadj** [comment]
Hey @trntv, is there any update on this? I'm currently using `if(Model::findOne(['user_id']=>Yii::$app->user->identity->id)` on every controller but I feel like the ownModelRule would be much more straightforward, except that I don't know how to implement it :tongue:

**Comment by trntv** [comment]
1. Copy and run rbac migration
2. Use ```Yii::$app->user->can('editOwnModel', ['model' => $model])```
