### ISSUE TITLE
How to add water mark when upload image

### ISSUE THREAD

**Issue by chonder** [trntv/yii2-starter-kit#324]

**Comment by trntv** [comment]
There will be watermarking support in glide 1.0, but now you can use the way i've added to file-kit readme

**Comment by zhewlakow** [comment]
Hello! First of all, thank you for your awesome kit! I've found some helpfull thing, Replace $img = Intervention\Image\ImageManager::make($file->read()); in example with $img = Intervention\Image\ImageManagerStatic::make($file->read());
