### ISSUE TITLE
Getting error when using mongodb

### ISSUE THREAD

**Issue by manishkumar-dsi** [trntv/yii2-starter-kit#327]
Not Supported – yii\base\NotSupportedException
Connection does not support reading schema information for 'mongodb' DBMS.

Steps to reproduce : 

1) I installed yii2-starter-kit
2) Installed Yii2-mongodb (yiisoft/yii2-mongodb)
3) Open Common/config/web.php file and put 
'mongodb' => [
            'class' => '\yii\mongodb\Connection',
            'dsn' => 'mongodb://developer:password@localhost:27017/mydatabase',
        ],
under components section.

Now the above mentioned issue will come.

Another approach 

I changed the .env file from Project Directory
1) Hided the default DB connection for Mysql and changed it to Mongodb

DB_DSN           = mongodb://localhost:27017/test
DB_USERNAME      = 
DB_PASSWORD      = 
DB_TABLE_PREFIX  =  

Still same issue.

Can you please suggest?

**Comment by trntv** [comment]
Did you remove ``db`` component from your config? Yii try to connect to your DB_DSN with ``yii\db\Connection`` which doesn't support mongodb
