### ISSUE TITLE
backend avatar upload issue

### ISSUE THREAD

**Issue by gish94** [trntv/yii2-starter-kit#328]
I am manually installed Yii2 starter-kit and after uploading avatar to the profile in backend i  received error in browser console  

"http://storage.yiistart.dev/source/1/hh8K5iVZACfFicREYyMJdlGKgX6YHNXl.png 404 (Not Found)" and there is no directory source/1/ in storage directory. 
![capture](https://cloud.githubusercontent.com/assets/8583056/11607965/968e7216-9b75-11e5-9da6-47e1f6a27a42.JPG)
Thanks

**Comment by hdushku** [comment]
Did you find a solution of this because I'am having the same problem.
Thanks

**Comment by gish94** [comment]
You need to add path to the storage/web folder in hosts. I added path to storage folder that's why i had this problem
