### ISSUE TITLE
Just a question about send mail settings

### ISSUE THREAD

**Issue by keltstr** [trntv/yii2-starter-kit#332]
Just a question.
There are 3 server (Linux) on any mail is not sent. The log letters fall. YII_ENV = prod.
What needs to be done to make the settings to send mail?
Do I need to robot email coincides with the domain server?

**Comment by trntv** [comment]
``prod`` environment should be enough. What about mail logs?

try to comment out this line:
https://github.com/trntv/yii2-starter-kit/blob/master/common/config/base.php#L49

**Comment by keltstr** [comment]
Where can I see the mail log ?
In debug panel I can see just sended mail and no errors or warning.
I tried to comment out and set it to false too ('useFileTransport' => false,),  but nothing happens.

**Comment by trntv** [comment]
/var/log/mail.log
10 дек. 2015 г. 19:15 пользователь "keltstr" <notifications@github.com>
написал:
