### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by robov** [trntv/yii2-starter-kit#335]
I am having trouble with the installation, 
I have uploaded all files, set the .env settings, but the next instruction is
" php console/yii app/setup" 

I cannot seem to find that file ?
Am I missing some simple but crucial knowledge (newbie to yii) ?

I would love to run the setup from the browser

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/tree/master/console

**Comment by robov** [comment]
Yes, that dir is on my server... but there is no setup file
And when I go there, it just shows the directory content (have not disabled that yet)
