### ISSUE TITLE
Account Activation by e-mail

### ISSUE THREAD

**Issue by nazakar** [trntv/yii2-starter-kit#348]
How easier create Account Activation by email ?

**Comment by XzAeRo** [comment]
+1

Also, the email template should try to follow [some simple rules](http://mailchimp.com/resources/guides/how-to-avoid-spam-filters/html/) to avoid being recognized as spam.

@trntv What do you think? Maybe a module or even a separate extension should be a good solution. Do you mind if I develop a solution around email-related activities?

**Comment by trntv** [comment]
Hi @XzAeRo, any extensions are welcome.

@nazakar, i'll add email activation this week.

**Comment by trntv** [comment]
done
