### ISSUE TITLE
Bad usage of phpdotenv

### ISSUE THREAD

**Issue by lichunqiang** [trntv/yii2-starter-kit#350]
> phpdotenv is made for development environments, and generally should not be used in production. In production, the actual environment variables should be set so that there is no overhead of loading the .env file on each request.

So what's the solution of the production mode? Still using the dotenv to load avariables?

**Comment by trntv** [comment]
It is your choice. You can use ``source .env`` in production mode if you want.

**Comment by lichunqiang** [comment]
I can understand you.

**Comment by trntv** [comment]
1. Change the [clear_env](http://php.net/manual/en/install.fpm.configuration.php#clear_env) setting for your php-fpm
2. remove everything from your ``.env`` file
3. run ``source .env`` in application root
4. restart fpm

**Comment by lichunqiang** [comment]
thank you :+1:
