### ISSUE TITLE
backend ArticleController   _form  When switching to Chinese Does not work

### ISSUE THREAD

**Issue by havoe** [trntv/yii2-starter-kit#351]
I ask you about

redactor.js:5770 Uncaught TypeError: Cannot read property 'html' of undefined

added zh.js 

当我切换到中文时 from 表单不能正常 工作 指示以下错误信息:
redactor.js:5770 Uncaught TypeError: Cannot read property 'html' of undefined

其他语言可以正常 工作

**Comment by trntv** [comment]
It's an imperavi redactor widget issue, but this quickfix will help:
```php
echo $form->field($model, 'body')->widget(
        \yii\imperavi\Widget::className(),
        [
            'options' => [
                ...
                'lang' => 'zh_cn'
                ...
            ]
        ]
    ) 
```
