### ISSUE TITLE
Datetimepicker widget formating

### ISSUE THREAD

**Issue by dbd5** [trntv/yii2-starter-kit#353]
Hi Eugene,

I'm trying to set the date format to DD.MM.YYYY of the Datetimepicker widget to match use in my locale but when I do, I get the error "Please set momentjs datetime format" so after looking at the code of the widget, I tried the following config;

        'phpDatetimeFormat' => dd-MM-'yyyy\'T\'HH:mm:ssZZZZZ',
        'momentDatetimeFormat' => 'dd-MM-yyyy\'T\'HH:mm:ssZZZZZ',

However after the change, I find that the widget no longer opens the picker for the user to select a date interactively. 
 
Could you please let me know what I doing wrong?

Regards,

Adam

**Comment by trntv** [comment]
momentjs has another format. Check out moment.js docs.
Meanwile i'll add your format to mappings - https://github.com/trntv/yii2-datetime-widget/issues/6

**Comment by dbd5** [comment]
Thanks
