### ISSUE TITLE
demo site gives error 403

### ISSUE THREAD

**Issue by gucluaydogan** [trntv/yii2-starter-kit#355]
Hi,

Trying to reach the demo site but I get 403 after logging in.

regards

**Comment by XzAeRo** [comment]
Are you using Vagrant or Docker? Or just normal installation?

Try to check the file permissions. They should be readable by the nginx process (usually `www-data`).

Go to the project root folder, in the console type `ls -l` and paste here the results.

**Comment by gucluaydogan** [comment]
Sorry, I tried to mean the demo link http://backend.yii2-starter-kit.terentev.net/sign-in/login.

Regards

**Comment by XzAeRo** [comment]
Oh ok. I'm hitting the same problem. This is an exclusive work for @trntv

**Comment by trntv** [comment]
Fixed
