### ISSUE TITLE
VKontakte auth not working.

### ISSUE THREAD

**Issue by ROIEX** [trntv/yii2-starter-kit#358]
При попытке авторизации через вконтакте идёт ругань на пустой email: Column 'email' cannot be null..

**Comment by trntv** [comment]
Да, для вконтакте надо править вот тут:
https://github.com/trntv/yii2-starter-kit/blob/master/frontend/modules/user/controllers/SignInController.php#L167

Необходимо добавить дополнительный scope и вытягивать из аттрибутов email при сохранении:
```php
'authClientCollection' => [
            'class' => 'yii\authclient\Collection',
            'clients' => [
                'vk' => [
                    'class' => 'yii\authclient\clients\VKontakte',
                    'scope' => 'email',
                    ...
                ]
            ]
],
```
```php
user->email = ArrayHelper::getValue($attributes, 'email');
```
