### ISSUE TITLE
Make PHP7.0 default

### ISSUE THREAD

**Issue by ddinchev** [trntv/yii2-starter-kit#359]
I'm already using PHP7 for my yii2-starter-kit based project and would contribute changed Vagrant setup based on that, given it makes sense for this app template. However this is highly restrictive for projects that don't have access to the latest PHP version.

**Comment by appcodr** [comment]
Do you have the changed vagrant setup on a branch to use php7? Can you share it please?

**Comment by trntv** [comment]
I've made PHP7 default for docker images
@ddinchev if you want, you can make pull request for vagrant, i'll accept it.
