### ISSUE TITLE
File-Kit widget ignoring >1MB file uploads

### ISSUE THREAD

**Issue by XzAeRo** [trntv/yii2-starter-kit#367]
Even with the `maxFileSize` option set to 10MB, the widget throws a `413 Request Entity Too Large` error for files larger than 1MB. Even happening in the demo page.

**Comment by XzAeRo** [comment]
Probably related to trntv/yii2-file-kit#61

**Comment by trntv** [comment]
It is web server (nginx) limitation

**Comment by XzAeRo** [comment]
Indeed. The wierd thing is that I was uploading >1mb files before without a problem. Maybe a nginx update changed something.
