### ISSUE TITLE
defaultRoute

### ISSUE THREAD

**Issue by dudunegrinhu** [trntv/yii2-starter-kit#373]
When I set my defaultRoute to another page, the address in the bar doesn't change.
For example, I have this:

'defaultRoute' => 'job/create',

so after user Login it should go to:
http://mysite.com/frontend/web/job/create
but instead it shows http://mysite.com/frontend/web/ on my address bar but it loads the content of job/create.

And than the problem is that every POST that I'm making in the job/create page is not working because it has the wrong path.

**Comment by trntv** [comment]
default route is the route that will serve request at '/'. So that's the correct behavior. Check yii2 docs.
