### ISSUE TITLE
Question regarding Fileupload.

### ISSUE THREAD

**Issue by yiioverflow** [trntv/yii2-starter-kit#375]
I can change the base url and, saving path according to the needs dynamicaly by setting from controller actin as follows.

    public function actions()
    {
        $params = $_REQUEST;        
        $directory = $params[1]['directory'];
        
        
        $filesystem =   [
                            'class' => 'app\components\filesystem\LocalFlysystemBuilder',
                            'path' => '@app/web/uploads/source/'.$directory
                        ];
        
        Yii::$app->fileStorage->setBaseUrl('/uploads/source/'.$directory) ;
        Yii::$app->fileStorage->setFilesystem($filesystem); 
        Yii::$app->fileStorage->init();

But here, the upload works fine. But when i delete, I also need to pass the argument, "directory from the widget" how its possbile ?

**Comment by trntv** [comment]
How ``fileStorage`` will know where you've stored your file? In this directory or that? Of course you need to save directory from request somehow.
