### ISSUE TITLE
Реализация OAuth2

### ISSUE THREAD

**Issue by vindective** [trntv/yii2-starter-kit#376]
Реализовать OAuth2 регистрацию и авторизацию.

**Comment by amstr1k** [comment]
@vindective is meant oauth-server?

**Comment by vindective** [comment]
@amstr1k yes, with the possibility updates and the creation of entities

**Comment by trntv** [comment]
oauth server is not so common thing that needs to be done in almost any project. If i'll find free time i'll publish my [thephpleague/oauth2-server](https://github.com/thephpleague/oauth2-server) -> yii2 integration
