### ISSUE TITLE
Possible issue with single app vhost config.

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#378]
I am trying out Cloud9's PaaS IDE service. One of the features is the ability to spin up a Ubuntu server with pre-installed LAMP stack. I clone the starter-kit repo, follow through the manual install directions, then edit the .env and apache vhost as directed for a single domain application. Even checked the Apache config was loading the vHost file correctly (it is).

The issue:
When visiting the site the header and footer load from the template but the content and css/js returns a 404. What am I doing incorrectly here?

/etc/apache2/sites-enabled/testing.conf vhost contents

> <VirtualHost *:80>
>     ServerName testing-davidjeddy.c9users.io
> 
>     RewriteEngine on
>     # the main rewrite rule for the frontend application
>     RewriteCond %{HTTP_HOST} ^testing-davidjeddy.c9users.io$ [NC]
>     RewriteCond %{REQUEST_URI} !^/(backend/web|admin|storage/web)
>     RewriteRule !^/frontend/web /frontend/web%{REQUEST_URI} [L]
>     # redirect to the page without a trailing slash (uncomment if necessary)
>     #RewriteCond %{REQUEST_URI} ^/admin/$
>     #RewriteRule ^(/admin)/ $1 [L,R=301]
>     # disable the trailing slash redirect
>     RewriteCond %{REQUEST_URI} ^/admin$
>     RewriteRule ^/admin /backend/web/index.php [L]
>     # the main rewrite rule for the backend application
>     RewriteCond %{REQUEST_URI} ^/admin
>     RewriteRule ^/admin(.*) /backend/web$1 [L]
> 
>     DocumentRoot /home/ubuntu/workspace
>     <Directory />
>         Options FollowSymLinks
>         AllowOverride None
>         AddDefaultCharset utf-8
>     </Directory>
>     <Directory "/home/ubuntu/workspace/frontend/web">
>         RewriteEngine on
>         # if a directory or a file exists, use the request directly
>         RewriteCond %{REQUEST_FILENAME} !-f
>         RewriteCond %{REQUEST_FILENAME} !-d
>         # otherwise forward the request to index.php
>         RewriteRule . index.php
> 
>         Require all granted
>     </Directory>
>     <Directory "/home/ubuntu/workspace/backend/web">
>         RewriteEngine on
>         # if a directory or a file exists, use the request directly
>         RewriteCond %{REQUEST_FILENAME} !-f
>         RewriteCond %{REQUEST_FILENAME} !-d
>         # otherwise forward the request to index.php
>         RewriteRule . index.php
> 
>         Require all granted
>     </Directory>
>     <Directory "/home/ubuntu/workspace/storage/web">
>         RewriteEngine on
>         # if a directory or a file exists, use the request directly
>         RewriteCond %{REQUEST_FILENAME} !-f
>         RewriteCond %{REQUEST_FILENAME} !-d
>         # otherwise forward the request to index.php
>         RewriteRule . index.php
> 
>         Require all granted
>     </Directory>
>     <FilesMatch \.(htaccess|htpasswd|svn|git)>
>         Require all denied
>     </FilesMatch>
> </VirtualHost>

File path:

> user:~/workspace (2016_master) $ pwd
> /home/ubuntu/workspace
> user:~/workspace (2016_master) $ ll
> total 272
> drwxr-xr-x 13 ubuntu ubuntu   4096 Mar 10 14:07 ./
> drwxr-xr-x 21 ubuntu ubuntu   4096 Mar 10 14:29 ../
> drwxr-xr-x  3 ubuntu ubuntu   4096 Mar 10 13:50 .c9/
> -rw-r--r--  1 ubuntu ubuntu    184 Mar 10 13:52 .dockerignore
> -rw-r--r--  1 ubuntu ubuntu    838 Mar 10 14:06 .env
> -rw-r--r--  1 ubuntu ubuntu    861 Mar 10 13:52 .env.dist
> -rw-r--r--  1 ubuntu ubuntu    799 Mar 10 13:52 .env.docker.dist
> drwxr-xr-x  8 ubuntu ubuntu   4096 Mar 10 13:52 .git/
> -rwxr-xr-x  1 ubuntu ubuntu    291 Mar 10 13:52 .gitignore*
> -rwxr-xr-x  1 ubuntu ubuntu   4064 Mar 10 13:52 CHANGELOG.md*
> -rw-r--r--  1 ubuntu ubuntu   1261 Mar 10 13:52 Dockerfile
> -rwxr-xr-x  1 ubuntu ubuntu   1622 Mar 10 13:52 LICENSE.md*
> -rwxr-xr-x  1 ubuntu ubuntu  11263 Mar 10 13:52 README.md*
> -rw-r--r--  1 ubuntu ubuntu   1650 Mar 10 13:52 autocompletion.php
> drwxr-xr-x 12 ubuntu ubuntu   4096 Mar 10 13:52 backend/
> -rw-r--r--  1 ubuntu ubuntu    231 Mar 10 13:52 codeception.yml
> drwxr-xr-x 18 ubuntu ubuntu   4096 Mar 10 13:52 common/
> -rwxr-xr-x  1 ubuntu ubuntu   1971 Mar 10 13:52 composer.json*
> -rw-r--r--  1 ubuntu ubuntu 151726 Mar 10 14:01 composer.lock
> drwxr-xr-x  5 ubuntu ubuntu   4096 Mar 10 13:52 console/
> drwxr-xr-x  3 ubuntu ubuntu   4096 Mar 10 13:52 docker/
> -rw-r--r--  1 ubuntu ubuntu    940 Mar 10 13:52 docker-compose.yml
> drwxr-xr-x  3 ubuntu ubuntu   4096 Mar 10 13:52 docs/
> drwxr-xr-x 11 ubuntu ubuntu   4096 Mar 10 13:52 frontend/
> drwxr-xr-x  5 ubuntu ubuntu   4096 Mar 10 13:52 storage/
> drwxr-xr-x  3 ubuntu ubuntu   4096 Mar 10 13:52 tests/
> drwxr-xr-x 28 ubuntu ubuntu   4096 Mar 10 14:01 vendor/
> -rw-r--r--  1 ubuntu ubuntu   3341 Mar 10 13:52 vhost.conf.dist
> -rw-r--r--  1 ubuntu ubuntu   2665 Mar 10 13:52 vhost.conf.docker.dist

Domain:
https://testing-davidjeddy.c9users.io/frontend/web/

Thanks for you help.

PS @trntv you have done an very awesome job making my life easier, please keep being aswesome.

**Comment by trntv** [comment]
Try to change basePath in your AssetManager config

**Comment by davidjeddy** [comment]
Unable to complete testing as development ENV has changed. Thank you for the input @trntv hopefully it helps someone out.
