### ISSUE TITLE
Use BootstrapInterface instead of phpdotenv for global parameters

### ISSUE THREAD

**Issue by iadj** [trntv/yii2-starter-kit#380]
Suggested solution for the issue reported at https://github.com/trntv/yii2-starter-kit/issues/377

`phpdotenv` doesn't always work. Env variables sometimes return null on page load. Laravel has also stopped using phpdotenv variable loading for this particular reason. See issues:
https://github.com/vlucas/phpdotenv/issues/109 
https://github.com/vlucas/phpdotenv/issues/76#issuecomment-167806230

I think we should use Yii2's `BootstrapInterface` to load global variables. It's good to use as many 'vanilla' Yii2 features as possible to decrease dependencies on third party packages, and it will work 100% of the time rather than 90% of the time compared to phpdotenv.

See top answer for integration: http://stackoverflow.com/questions/27778477/how-to-make-custom-settings-data-available-globally-in-yii-2

**Comment by trntv** [comment]
We can't use yii bootstrap process here, because it is invoked after config file has been loaded.
We need our settings **inside** config file, so they should be set before execution enters it.

**Comment by iadj** [comment]
@trntv Good point. Dotenv also appears to work properly when on a webserver. It only has issues locally. Is there some sort of fix we can implement i.e. setting a timeout or refresh period until dotenv is read?
