### ISSUE TITLE
Vagrant installation problems

### ISSUE THREAD

**Issue by XzAeRo** [trntv/yii2-starter-kit#382]
- The mysql user/pass in the `.env.dist` is different from what `vagrant.sh` installs.
  - The .env is set to `user:root pass:<nothing>`, but the vagrant.sh file installs a mysql server with the credentials `user:root pass:root` 
- The command `console/yii app/setup` failed in a fresh install. Solved ssh'ing into the machine and running `sudo console/yii app/setup`.

The one that is worrying, is the `sudo console/yii app/setup`. How should that be solved?

SW | Version 
--- | ---
Host OS | Mac OSX El Capitan 10.11.3 (15D21)
Guest OS | Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-83-generic x86_64) (everything up-to-date)
Yii2-Starter-Kit Version | Pointing at c30c8eb
Vagrant | 1.8.1
VirtualBox | 5.0.16 r105871

**Comment by XzAeRo** [comment]
Just an update. The `console/yii app/setup` command failed due to the lack of database connection, so the issue just relates to the faulty initial configuration of Vagrant files.

**Comment by trntv** [comment]
fixed
