### ISSUE TITLE
Using admin panel, placing application into 

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#384]
..after installation, before any other modifications are added, I used the backend `Frontend maintenance mode` and set it to 'enabled`. Reloading the frontend had not change.

**Comment by verstoff** [comment]
```
if (YII_ENV_PROD) {
    // Maintenance mode
    $config['bootstrap'] = ['maintenance'];
    $config['components']['maintenance'] = [
        'class' => 'common\components\maintenance\Maintenance',
        'enabled' => function ($app) {
            return $app->keyStorage->get('frontend.maintenance') === 'enabled';
        }
    ];
}
```
This works only in production environment out of the box

**Comment by trntv** [comment]
thank you @verstoff for answer.
I think i'll change this behavior. maintenance mode should work equally on all environments
