### ISSUE TITLE
Rest API

### ISSUE THREAD

**Issue by dudunegrinhu** [trntv/yii2-starter-kit#385]
Hi,

I'm trying to create a rest api for my backend but I see that you already implemented that in the frontend so I'm trying to replicate in the backend but the problem is that the frontend doesn't work. I'm getting this error:

http://mysite.com/frontend/web/api/v1/user

<response><name>Unauthorized</name><message>You are requesting with an invalid credential.</message><code>0</code><status>401</status><type>yii\web\UnauthorizedHttpException</type></response>

How can I login via the API?

**Comment by sivarajd** [comment]
Hi,

Please use a rest client like https://addons.mozilla.org/en-US/firefox/addon/restclient/ or web based client like https://resttesttest.com

If using Firefox addon, set Basic authentication and user id/password as user/user.

**Comment by Dezinger** [comment]
https://www.getpostman.com/
![postman 2016-03-29 18-51-41](https://cloud.githubusercontent.com/assets/432272/14114441/a1a982de-f5df-11e5-93dd-14957eef3920.jpg)

**Comment by trntv** [comment]
@dudunegrinhu this is the right behavior for api. You should authenticate your requests with one of available methods - https://github.com/yiisoft/yii2/blob/master/docs/guide/rest-authentication.md#authentication
