### ISSUE TITLE
Why use own command bus instead of league/tactitian?

### ISSUE THREAD

**Issue by ddinchev** [trntv/yii2-starter-kit#389]
I was wondering why would you use your own command bus pattern implementation instead of relying on existing library like https://github.com/thephpleague/tactician? I do not criticise your implementation at all, it is out of curiosity if you found any problems with the existing one or else!

**Comment by trntv** [comment]
1. I don't really like tactician. Don't know why :-)
2. It don't have "self-handling" commands out of the box
3. Tactician looks organic in symfony or laravel but very strange in Yii2 without Service Provider and with all those adapters
4. Command Bus pattern is not so complicated. So why not to create almost "native" yii2 realization?

**Comment by ddinchev** [comment]
Fair enough :)
