### ISSUE TITLE
use of eval

### ISSUE THREAD

**Issue by gouchaoer** [trntv/yii2-starter-kit#395]
Look at this line:https://github.com/trntv/yii2-starter-kit/blob/master/console/controllers/ExtendedMessageController.php#L66

hi, trntv.
I don't know why you use a eval here, could you explain it?
thanks!

**Comment by trntv** [comment]
This is a copy-paste code block from old native message controller :-)

**Comment by gouchaoer** [comment]
well, i finally understand... there is no choice but use eval.
thank you!
