### ISSUE TITLE
Suggestion: Use Docker provider for Vagrant

### ISSUE THREAD

**Issue by XzAeRo** [trntv/yii2-starter-kit#399]
Since the discussion in #360, I was thinking it would make more sense to use Vagrant with Docker as a provider instead of Virtualbox.

What do you think @trntv?

**Comment by trntv** [comment]
I don't know nothing about docker provider in Vagrant. What benefits it have?

**Comment by ddinchev** [comment]
I actually think it could be a very good idea. Using Vagrant's docker provider, we will get rid of the vagrant shell script. Vagrant will start a VM based on the Dockerfile and run the containers there. 

I'll try to do it for a project that uses yii2-starter-kit and will make a PR if it works fine.

**Comment by trntv** [comment]
@ddinchev nice idea, waiting for your PR!

**Comment by XzAeRo** [comment]
Any updates @ddinchev? :)
I liked the idea, but I can't find the time to actually do the implementation.
