### ISSUE TITLE
Change password method

### ISSUE THREAD

**Issue by adiramardiani** [trntv/yii2-starter-kit#403]
Actually the current change password method is only with password repeat in `password confirm`

I think this is not secure because sometimes if comp/laptop/device is borrowed and application not sign out, anyone can change this password just for a joke example.

For best practice, `change password` feature is separated between edit account, and have own form
For security user must write old password before change password.

`oldpass`
`newpass`
`newpassrepeat`

I think `reset password` in login feature is something nice too
And random string generator (and copy/paste option) for password in create user form

**Comment by trntv** [comment]
You are right, but not in this case.  This kit is a "base" or "skeleton" for your application. I'm trying to balance between to cover as much cases as possible and keeping it as simple as possible at the same time.
