### ISSUE TITLE
Frontend/web subdirectories shouldn't be indexed

### ISSUE THREAD

**Issue by iadj** [trntv/yii2-starter-kit#412]
Currently, accessing `http://frontend-url.dev/css` or any other directory inside the `frontend/web` folder will let you list all files and subdirectories. Users shouldn't be able to index files/folders in these directories.

**Comment by XzAeRo** [comment]
This is related to the configuration of your web server (Apache or Nginx), rather than a project related issue.
Also, the `frontend/web` folder is intended to be publicly accessible, so if you're storing sensitive data in that folder, don't.

To disable the directory listing in Nginx [check this](http://nginx.org/en/docs/http/ngx_http_autoindex_module.html), and for Apache [check this](https://wiki.apache.org/httpd/DirectoryListings#Directory_Listings).

ps: Directory listing is disabled by default in Nginx. For example: http://yii2-starter-kit.terentev.net/css/

**Comment by iadj** [comment]
I know it's for public files, but the directories shouldn't be indexed by default nonetheless in my opinion.

**Comment by XzAeRo** [comment]
This isn't happening in my case. What is your setup?

**Comment by iadj** [comment]
I'm on Ubuntu with Apache2. It seems like the .htaccess files aren't being used on my server, because it is working on my localhost windows set-up.

**Comment by iadj** [comment]
```
<VirtualHost *:80>
  ServerName my-website.com
  #ServerAlias 127.0.0.1
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/acces.log combined
    DocumentRoot /var/www/my-website.com/frontend/web/
    <Directory "/var/www/my-website.com/frontend/web/">
        AllowOverride All
        # use mod_rewrite for pretty URL support
        RewriteEngine on
        # If a directory or a file exists, use the request directly
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        # Otherwise forward the request to index.php
        RewriteRule . index.php
        # ...other settings...
    </Directory>
</VirtualHost>
```

This is my virtual host configuration. I also set `AllowOverride All` in my `apache2.conf` file

**Comment by iadj** [comment]
Turns out configuring it that way did indeed fix it haha. Thanks for letting me know it was working on your end @XzAeRo. That allowed me to look at my server conf :)

**Comment by XzAeRo** [comment]
Haha, great that you got that figured out!
Btw, you should add `Options -Indexes` directive in your configuration to prevent directory listings in Apache.

For example:

```
<VirtualHost *:80>
  ServerName my-website.com
  #ServerAlias 127.0.0.1
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/acces.log combined
    DocumentRoot /var/www/my-website.com/frontend/web/
    <Directory "/var/www/my-website.com/frontend/web/">
        # Disable directory listings
        Options -Indexes
        # Enable .htaccess files
        AllowOverride All
        # use mod_rewrite for pretty URL support
        RewriteEngine on
        # If a directory or a file exists, use the request directly
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        # Otherwise forward the request to index.php
        RewriteRule . index.php
        # ...other settings...
    </Directory>
</VirtualHost>
```

Or in the `.htaccess` in `frontend/web/`:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . index.php

Options -Indexes
```
