### ISSUE TITLE
Feature Request: Add web interface for RBAC administration

### ISSUE THREAD

**Issue by senguttuvang** [trntv/yii2-starter-kit#414]

**Comment by yanhuixie** [comment]
You may simply composer require "mdmsoft/yii2-admin": "^2.5"?

**Comment by senguttuvang** [comment]
That's what I did now. But I doubt whether that extension and this starterkit are compatible.

**Comment by yanhuixie** [comment]
As I know, both yii2-starter-kit (access control part) and mdmsoft/yii2-admin implements the standard yii2 rbac interfaces.
Just follow mdmsoft/yii2-admin installation instruction and usage documentation, try it. :-)

**Comment by desaikalpesh34** [comment]
@yanhuixie 
i have tried this [https://github.com/desaikalpesh34/yii2-kit](https://github.com/desaikalpesh34/yii2-kit) here

**Comment by davidjeddy** [comment]
Duplicate of https://github.com/trntv/yii2-starter-kit/issues/325
PR available https://github.com/trntv/yii2-starter-kit/pull/586

**Comment by dungphanxuan** [comment]
My case not need RBAC interface, because when design system, all info about RBAC will description detal, so you need config once at first time.

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/pull/586
