### ISSUE TITLE
Column 'email' cannot be null when trying to login with github

### ISSUE THREAD

**Issue by hdushku** [trntv/yii2-starter-kit#415]
Integrity constraint violation – yii\db\IntegrityException

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null

**Comment by iadj** [comment]
We need to deal with it in the same way as Facebook, redirecting to the registration page where people are still required to enter their email.

**Comment by trntv** [comment]
scope should deal with it. I'll check if it is still working as expected with new api versions
