### ISSUE TITLE
Backend $this->redirect() always goes to 'http' instead of the currently used protocol

### ISSUE THREAD

**Issue by iadj** [trntv/yii2-starter-kit#416]
If I'm on my back-end in HTTPS i.e. `https://admin.dev/create-page` and I submit a form that results in a `$this->redirect`, I get redirected to the non-https URL i.e. `http://admin.dev`

**Comment by XzAeRo** [comment]
This looks like a configuration issue.

Yii2 redirects using [`\yii\web\Request::getIsSecureConnection()`](https://github.com/yiisoft/yii2/blob/master/framework/web/Request.php#L827-L831).

If you take a look at the implementation, it checks for the `$_SERVER['HTTPS']` value, or `$_SERVER['HTTP_X_FORWARDED_PROTO']`. This is set by PHP based on your server (Apache, Nginx, etc.), on service start.

In Nginx, you can set this by using `proxy_set_header X-Forwarded-Proto $scheme;` in your `vhost.conf`file, and in Apache using [this setup](https://httpd.apache.org/docs/2.4/ssl/ssl_howto.html).

Hope this helps.

**Comment by iadj** [comment]
Great advice @XzAeRo.  It was indeed a configuration issue with virtual hosts (again!).
