### ISSUE TITLE
Как отключить bootstrap стили?

### ISSUE THREAD

**Issue by actorius** [trntv/yii2-starter-kit#417]
Перерыл везде, не могу найти где подключаются.
В frontend/assets/FrontEndAsset.php отключи, но в head всеравно вставляется подключение bootstrap.css и в стилях видно что берутся из файлов *.less

**Comment by Beaten-Sect0r** [comment]
виджеты подтягивают

**Comment by trntv** [comment]
можешь полностью выключить bootstrap в [[yii\web\AssetManager::bundles]]
https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L57
