### ISSUE TITLE
invalid configuration when trying to access admin

### ISSUE THREAD

**Issue by hdushku** [trntv/yii2-starter-kit#418]
When I try to access
https://xxxxxxx.c9users.io/admin
In cloud9

Invalid Configuration – yii\base\InvalidConfigException

Unable to determine the path info of the current request.
1. in /home/ubuntu/workspace/vendor/yiisoft/yii2/web/Request.php

**Comment by trntv** [comment]
Single-domain installation isn't officialy supported, but i'll try to create a doc about c9.io setup

**Comment by vrtc** [comment]
@hdushku  Hi, I only had to specify the Alias.
See my configuration file. And it works.
```
<VirtualHost *:80>
	ServerName yarit.my
	AssignUserID vrtc users
	ServerAdmin webmaster@localhost
	DocumentRoot /home/vrtc/Website/yarit/frontend/web
        Alias /admin /home/vrtc/Website/yarit/backend/web
        Alias /storage /home/vrtc/Website/yarit/storage/web
</VirtualHost>
```

**Comment by hdushku** [comment]
Hello @vrtc 
When I access /admin gives me the error but when I put slash at the end /admin/ works good
Thanks

**Comment by vrtc** [comment]
@hdushku maybe we have different versions of apache or configuration. I was glad to help you
