### ISSUE TITLE
Add multi-tenancy support

### ISSUE THREAD

**Issue by senguttuvang** [trntv/yii2-starter-kit#421]
I'm building a multi-tenancy app on top of the starter-kit, but got stuck due to unsupported single domain installation.

URL structure of the app is,

<tenant1>.myapp.com - frontend of tenant1
<tenant1>.myapp.com/admin - backend of tenant2

<tenant2>.myapp.com - frontend of tenant2
<tenant2>.myapp.com/admin - backend of tenant2

I do have dedicated server to run this app, but I prefer to give single sub-domain for my tenants within which they can access both front end and backend. 

Do you have any suggestions or recommendations on how I can achieve this?

**Comment by dungphanxuan** [comment]
Single domain config example: 
https://github.com/kartik-v/yii2-app-practical-a
