### ISSUE TITLE
composer install can't find packages!!!

### ISSUE THREAD

**Issue by YKXMall** [trntv/yii2-starter-kit#422]
$ composer install
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/admin-lte could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package bower-asset/font-awesome could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package bower-asset/html5shiv could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package bower-asset/jquery-slimscroll could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package bower-asset/flot could not be found in any version, there may be a typo in the package name.
  Problem 6
    - Installation request for trntv/yii2-aceeditor ^2.0 -> satisfiable by trntv/yii2-aceeditor[2.0.0].
    - trntv/yii2-aceeditor 2.0.0 requires bower-asset/ace-builds ~1.1.8 -> no matching package found.
  Problem 7
    - yiisoft/yii2 2.0.8 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 ^2.0.6 -> satisfiable by yiisoft/yii2[2.0.6, 2.0.7, 2.0.8].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by odai-alali** [comment]
Have you installed the Yii2 asset plugin? you can install it by using the following command
```
php composer.phar global require "fxp/composer-asset-plugin:~1.1.1"
```

**Comment by trntv** [comment]
@YKXMall, @odai-alali gave you an answer

**Comment by RichardTMiles** [comment]
https://packagist.org/packages/fxp/composer-asset-plugin
For the sake of connecting the internet, look at his ^ repo and see where the internet is going below 
https://github.com/fxpio/foxy
