### ISSUE TITLE
The message file for category 'filekit/widget' does not exist

### ISSUE THREAD

**Issue by zvinger** [trntv/yii2-starter-kit#424]
I see it always in log every time I use UploadWidget.

Screenshot: http://joxi.ru/12MpnMLs4yaglm

**Comment by XzAeRo** [comment]
This bug has been going on for a while (it's not critical, but very annoying).
For some reason, this Issue trntv/yii2-file-kit#51 didn't solve the problem.

**Comment by XzAeRo** [comment]
I sent a pull request in the extension repository trntv/yii2-file-kit#96.
This fixes the problem.

**Comment by zvinger** [comment]
Nice. Thanks you very much)

**Comment by trntv** [comment]
fixed

**Comment by sankaest** [comment]
Is it fixed?
I see `public $messagesCategory = 'filekit/widget';` in the code. 
Changed as #96 and there is no errors after that.
