### ISSUE TITLE
Using starter kit with material design 

### ISSUE THREAD

**Issue by fortm** [trntv/yii2-starter-kit#432]
Thanks for very helpful starter kit for Yii 2 👍 
Can we use this starter kit with materializecss instead of bootstrapcss ?
Mainly concerned about look and feel for plugins that are part of kit when placed along with material design framework and what files will need changing to swap out bootstrap.

**Comment by ddinchev** [comment]
I imagine you should start by using composer to install this:
https://github.com/FezVrasta/bootstrap-material-design

And then include the material design files by creating a new assets file here:
https://github.com/trntv/yii2-starter-kit/tree/master/frontend/assets

From there on, check to see what is needed to make it working.

**Comment by trntv** [comment]
Hi, starter kit is not focused on how it looks but how it works. Any design can't satisfy everyone so it is your choice and responsibility.
