### ISSUE TITLE
The 404 error has occurred when opening the file in elfinder.

### ISSUE THREAD

**Issue by yanhuixie** [trntv/yii2-starter-kit#433]
A new installed y2sk app (default settings follow the instruction). 
http://backend.y2sk.dev/file-manager/index
Thumbnails appear normal, but can not open the file (double click or right click/open).
And, right click/download is OK.
I find the download address is "http://backend.y2sk.dev/file-manager-elfinder/connect?cmd=file&target=blabla...".
And, the open address is "http://storage.y2sk.dev/web/source/1/blabla...".
Problem is the extra **web** between root and **source**.
How can I fix it?
Any suggestion is appreciated. Thanks.

**Comment by dimm-nn** [comment]
I have the same problem!

**Comment by dimm-nn** [comment]
Ooh, I think it is fixed. It is necessary to correct a config file "backend/config/web.php" (parameter 'basePath'):
```php
    'controllerMap'=>[
        'file-manager-elfinder' => [
            'class' => 'mihaildev\elfinder\Controller',
            'access' => ['manager'],
            'disabledCommands' => ['netmount'],
            'roots' => [
                [
                    'baseUrl' => '@storageUrl',
                    'basePath' => '@storage/web', // Vlaue '@storage'
                    'path'   => '/',
                    'access' => ['read' => 'manager', 'write' => 'manager']
                ]
            ]
        ]
    ],
```

**Comment by yanhuixie** [comment]
Wow~ Thank you @dimm-nn ! I have just solved the problem follow your instruction. :-)
