### ISSUE TITLE
A suggestion about the symlink ErrorException of assetManager

### ISSUE THREAD

**Issue by yanhuixie** [trntv/yii2-starter-kit#434]
Perhaps you may use this code to avoid the symlink ErrorException in Windows, and no need to care about the OS from now on. 
common/config/web.php
```php
'linkAssets' => PATH_SEPARATOR==':' ? true : false,

**Comment by manuelmanco** [comment]
@yanhuixie  This is an excellent proposal ! Did you already made a pull request?

**Comment by gouchaoer** [comment]
in windows, you need to run your xampp/wamp as administrator to use symlink.

**Comment by yanhuixie** [comment]
Hi manuelmanco, I just think that it's too minor to make a pull request... :-)
Hi gouchaoer, thanks for your attention, that's an alternative way.
