### ISSUE TITLE
Docker installation direction outdated...

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#439]
...specifically for OSX/Win as native clients have been released. The following is the current error code as of #2.2.1

```
root@9a2c2192a6c2:/app# app/setup
bash: app/setup: No such file or directory
root@9a2c2192a6c2:/app# php app/setup
Failed loading /usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so:  /usr/local/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so: cannot open shared object file: No such file or directory
Could not open input file: app/setup
root@9a2c2192a6c2:/app# exit
exit
➜  truefriend.dev git:(st/master) ✗ docker-compose run cli app/setup
ERROR: oci runtime error: exec: "app/setup": executable file not found in $PATH
```

**Comment by ddinchev** [comment]
I'll make sure to address those today finally in a PR.

**Comment by davidjeddy** [comment]
@ddinchev thank you. It will go a long way towards getting my org to move to docker.

**Comment by ddinchev** [comment]
There were quite few things to change to get this going properly. Right now you can start by doing:
```bash
docker-compose run cli /bin/bash
/app/console/yii app/setup
```

I have no idea how `docker-compose run cli app/setup` was ever supposed to work.

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/commit/d70022cd6364d61a28a9934dda0218ff31d51e7c
