### ISSUE TITLE
BUG: Search validation error message

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#444]
![screen shot 2016-07-08 at 9 02 05 am](https://cloud.githubusercontent.com/assets/6232455/16689330/7067031c-44f0-11e6-8a31-b22104234a73.png)

**Comment by trntv** [comment]
It is not a bug, ``created_at`` is ``INT``column with timestamps. You should convert it to timestamp before quering DB.

**Comment by davidjeddy** [comment]
Agreed, but this is initial install CRUD interface.
Enh suggestion: add stated data conversion to admin CRUD forms.

**Comment by dungphanxuan** [comment]
I agree, you need customize as you need.
