### ISSUE TITLE
I encountered some errors when installing it by composer install

### ISSUE THREAD

**Issue by pzzrudlf** [trntv/yii2-starter-kit#448]
![error](https://cloud.githubusercontent.com/assets/3185502/16759477/a8b731e0-4849-11e6-874e-90f1ed97c53f.png)

**Comment by haoliang-gao** [comment]
Did you have executed the following command ? If not, then try it.

`$ composer global require "fxp/composer-asset-plugin:^1.2.0"`

**Comment by gouchaoer** [comment]
you need a good network

**Comment by pzzrudlf** [comment]
There are still some errors.

**Comment by pzzrudlf** [comment]
![screenshot from 2016-07-14 11-50-55](https://cloud.githubusercontent.com/assets/3185502/16827445/475391b6-49b9-11e6-9aa0-fe4fc3a2a701.png)

**Comment by pzzrudlf** [comment]
This is my php's environment.  http://121.42.156.237/p.php

**Comment by sim2github** [comment]
Composer install work fine. 'PHP error: php_network_getaddresses: getaddrinfo failed' -  you can't resolve the host name Maybe DNS problems, host is unreachable...

**Comment by pzzrudlf** [comment]
Thank you. I've got it.
