### ISSUE TITLE
how to escape from class container when echo $content

### ISSUE THREAD

**Issue by SerikK** [trntv/yii2-starter-kit#450]
I have this code in layouts/base.php: <?php echo $content; ?>. But it generates `<div class="container">content...</div>`. I don't need additional div. How I can escape it?

**Comment by sim2github** [comment]
Mayby modifying [page/view](https://github.com/trntv/yii2-starter-kit/blob/master/frontend/views/page/view.php) can help? Or search where `class="container"` used in `views` folders.

**Comment by SerikK** [comment]
In page/view there is div with class content. I searched in view folders and I did not find. I have no idea where class container is generating.

**Comment by sim2github** [comment]
`frontend/views/layouts/main.php`

**Comment by SerikK** [comment]
Oh, I'm so blind. Thanks @sim2github .
