### ISSUE TITLE
Single domain config appearse out dated

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#451]
Following the directions for the manual install. When visiting `app-domain.com/admin`  the user is redirected to `http://app-domain.com/admin/sign-in/login` but receives a 404.

``` .env
# Urls
# ----
FRONTEND_URL    = /
BACKEND_URL     = /admin
STORAGE_URL     = /storage/web

```

``` .htaccess
    RewriteEngine on
    # the main rewrite rule for the frontend application
    RewriteCond %{HTTP_HOST} ^zeroforksgiven.com$ [NC]
    RewriteCond %{REQUEST_URI} !^/(backend/web|admin|storage/web)
    RewriteRule !^/frontend/web /frontend/web%{REQUEST_URI} [L]
```

*Using the provided .htaccess throws an apache error about no VHosts allowed.

Edited both the frontend and backend baseUrl values. Frontend works great, backend 404's.

**Comment by davidjeddy** [comment]
For anyone interested this worked for my single domain setup on CentOS, Apache2.4.
```.htaccess
 RewriteEngine on
    # the main rewrite rule for the frontend application
    RewriteCond %{HTTP_HOST} ^zeroforksgiven.com$ [NC]
    RewriteCond %{REQUEST_URI} !^/(backend/web|admin|storage/web)
    RewriteRule !^/frontend/web /frontend/web%{REQUEST_URI} [L]
```

```.env
FRONTEND_URL    = /
BACKEND_URL     = /
STORAGE_URL     = /storage/web
```

and finally backend config
```php
        'request' => [
            'cookieValidationKey' => env('BACKEND_COOKIE_VALIDATION_KEY'),
            'baseUrl' => '/backend/web'
        ],
```

Hope this helps out.

**Comment by zlfoxy** [comment]
I am using  single domain,too. I use this project's all the codes as my project's  skeleton， but when i set `FRONTEND_URL    = /`   , the  Alias @frontendUrl  and $homeUrl will be  null,  and this will cause some problem strange. 
I use  `FRONTEND_URL = example.com` `BACKEND_URL   = /admin` now.

**Comment by dungphanxuan** [comment]
here is my setting

![d6624e119657495690df46859904b3ef](https://cloud.githubusercontent.com/assets/10725732/17687857/17f62db2-63a3-11e6-8af3-6c5a1d0b9c00.png)

**Comment by davidjeddy** [comment]
@zlfoxy What is the contents of your `.htaccess`?
