### ISSUE TITLE
how use myself UserProfile ?

### ISSUE THREAD

**Issue by wblbird** [trntv/yii2-starter-kit#466]
In order to use myself UserProfile table.
  I modified the UserProfile associated data table, modify the common \ models \ User  hasOne, and backend \ views \ sign-in \ profile, but does not run.

error messages：
**Invalid argument supplied for foreach()**
    * found in the [[rules()]]. Each scenario will be associated with the attributes that
     * are being validated by the validation rules that apply to the scenario.
     *
     * @return array a list of scenarios and the corresponding active attributes.
     */
    public function scenarios()
    {
        $scenarios = [self::SCENARIO_DEFAULT => []];
        foreach ($this->getValidators() as $validator) {
            foreach ($validator->on as $scenario) {
                $scenarios[$scenario] = [];
...............

Thank you first！

**Comment by trntv** [comment]
Have no idea what is going on with your code, debug it ;-) Good luck

**Comment by wblbird** [comment]
thank you for your Good LUCK
