### ISSUE TITLE
How to remove Google font references?

### ISSUE THREAD

**Issue by ciniran** [trntv/yii2-starter-kit#468]
Because the Google font reference speed becomes slow
I found the CSS file, has the @import to point to the connection of Google removed, but still have a place can not find, still in the Google font, how can I remove clean?

**Comment by XzAeRo** [comment]
If I'm not wrong, the only asset that uses Google Fonts is [AdminLTE in this file](https://github.com/almasaeed2010/AdminLTE/blob/master/build/less/AdminLTE.less#L9).

There was [a discussion about it in the AdminLTE repo](https://github.com/almasaeed2010/AdminLTE/issues/498), but nothing actually came out of it, even though the mantainer told that he would move it out of the files.

How to fix this? Well, you will have to do it manually! Either by compiling the `less` files, or just modifying the adminlte css file directly.

**Comment by ciniran** [comment]
Thank you very much for your guidance
