### ISSUE TITLE
prevent login twice and error filter i18n

### ISSUE THREAD

**Issue by mysoundmagic** [trntv/yii2-starter-kit#471]
hello,

application need enhancement because still able to log in twice from a different computer or different browser. And error in index i18n gridview filter source/language.

**Comment by XzAeRo** [comment]
>still able to log in twice from a different computer or different browser

What do you mean?
It's supposed to work like that. I mean, you have to login to every computer or browser, even if you're in the same network. Are you implying the application login should be associated to the user IP?

**Comment by mysoundmagic** [comment]
no, I mean users who have logged in can not log in again. if log in again the first login session should be expired or forcefully logout.
