### ISSUE TITLE
Problem migration, creaate unique index for varchar 1024

### ISSUE THREAD

**Issue by VicVicos** [trntv/yii2-starter-kit#473]
Problem migration m140703_123803_article, on lines 59, 60. Create Index for article and article_category for slug.
Cause error MuSQL:
Specified key was too long; max key length is 767 bytes.
Inquiry:
ALTER TABLE `kj1j_article` ADD UNIQUE INDEX`idx_article_slug` ( `slug`).
It is actually clear to varhar 1024.

**Comment by gouchaoer** [comment]
https://github.com/trntv/yii2-starter-kit/issues/470
