### ISSUE TITLE
Error when run command :php console/yii app/setup

### ISSUE THREAD

**Issue by clarencerank** [trntv/yii2-starter-kit#478]
Creating migration history table "system_db_migration"...Done.
Total 15 new migrations to be applied:
        m140703_123000_user
        m140703_123055_log
        m140703_123104_page
        m140703_123803_article
        m140703_123813_rbac
        m140709_173306_widget_menu
        m140709_173333_widget_text
        m140712_123329_widget_carousel
        m140805_084745_key_storage_item
        m141012_101932_i18n_tables
        m150318_213934_file_storage_item
        m150414_195800_timeline_event
        m150725_192740_seed_data
        m150929_074021_article_attachment_order
        m160203_095604_user_token

Apply the above migrations? (yes|no) [no]:
Yii Migration Tool (based on Yii v2.0.9)

Creating migration history table "system_rbac_migration"...Done.
Total 3 new migrations to be applied:
        m150625_214101_roles
        m150625_215624_init_permissions
        m151223_074604_edit_own_model

Apply the above migrations? (yes|no) [no]:y
**\* applying m150625_214101_roles
Exception 'yii\db\Exception' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yii2-starter-kit.rbac_auth_assignment' doesn't exist
The SQL being executed was: DELETE FROM `rbac_auth_assignment`'

in C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\db\Schema.php:633

Error Info:
Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'yii2-starter-kit.rbac_auth_assignment' doesn't exist
)

Stack trace:
#0 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\db\Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'DELETE FROM `rb...')
#1 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\rbac\DbManager.php(918): yii\db\Command->execute()
#2 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\rbac\DbManager.php(844): yii\rbac\DbManager->removeAllAssignments()
#3 C:\xampp\htdocs\yii2-starter-kit\common\migrations\rbac\m150625_214101_roles.php(10): yii\rbac\DbManager->removeAll()
#4 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(509): m150625_214101_roles->up()
#5 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m150625_214101_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#8 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('up', Array)
#10 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('up', Array)
#11 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('rbac-migrate/up', Array)
#12 C:\xampp\htdocs\yii2-starter-kit\console\controllers\AppController.php(40): yii\console\Application->runAction('rbac-migrate/up', Array)
#13 [internal function]: console\controllers\AppController->actionSetup()
#14 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#15 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('setup', Array)
#17 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('setup', Array)
#18 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('app/setup', Array)
#19 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('app/setup', Array)
#20 C:\xampp\htdocs\yii2-starter-kit\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#21 C:\xampp\htdocs\yii2-starter-kit\console\yii(26): yii\base\Application->run()
#22 {main}

**Comment by Kharalampidi** [comment]
Скорее всего причина в #470 
Просто clarencerank не заметил, что app/setup вывел ему ошибку :-)

**Comment by sim2github** [comment]
```
Apply the above migrations? (yes|no) [no]:
```

You skip previous part of migrations.

**Comment by davidjeddy** [comment]
I have a PR in that changes the install process to add `--interactive=0` to the commands; thus ensuring this type of mistake is not as common.
