### ISSUE TITLE
Can not run application without install `require-dev` dependencies.

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#482]
Issue: Installing the application from scratch using restricte composer command (see screenshot)
Actual: application errors when attempting to run setup command
Expected: application should be capable of setting up and running w/ development dependencies.

![screen shot 2016-10-26 at 2 19 58 pm](https://cloud.githubusercontent.com/assets/6232455/19739010/70b990e4-9b87-11e6-94de-9a536f5def32.png)

**Comment by trntv** [comment]
when YII_DEBUG is enabled you should install yii2-debug module. it is listed in ``require-dev`` section.

**Comment by davidjeddy** [comment]
It's an issue with the migrations not being able to run w/o Gii, but Gii is part of require-dev. Application install should be possible without using dev dependancies.
