### ISSUE TITLE
Class 'trntv\aceeditor\AceEditor' not found

### ISSUE THREAD

**Issue by shuijingwan** [trntv/yii2-starter-kit#483]
http://backend.yii2-starter-kit.dev/widget-text/create
PHP Fatal Error – yii\base\ErrorException
Class 'trntv\aceeditor\AceEditor' not found
in E:\wwwroot\yii2-starter-kit\backend\views\widget-text_form.php at line 20

<div class="text-block-form">

```
<?php $form = ActiveForm::begin(); ?>

<?php echo $form->field($model, 'key')->textInput(['maxlength' => 1024]) ?>

<?php echo $form->field($model, 'title')->textInput(['maxlength' => 512]) ?>

<?php echo $form->field($model, 'body')->widget(
    **trntv\aceeditor\AceEditor::className(),**
    [
        'mode' => 'html'
    ]
) ?>

<?php echo $form->field($model, 'status')->checkbox() ?>

<div class="form-group">
    <?php echo Html::submitButton(
```

**Comment by fromage9747** [comment]
I am experiencing the exact same issue and found your post on: http://www.shuijingwanwq.com/2016/10/27/1381/

Searching online for the same issue I found the below link:
https://github.com/trntv/yii2-aceeditor/issues/4

However I did what was said to do in the above link but the error persists! 

Help anyone?

**Comment by trntv** [comment]
This issue was fixed in yii2-aceeditor
