### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by ztdan4ik** [trntv/yii2-starter-kit#488]
Hi!
I found one problem with authorization
After logout, when I trying to login again application redirecting me to /user/sign-in/logout with message "Method Not Allowed (# 405)" It's happen because in session storage __redirect_url stored /user/sign-in/logout after logout
I tested it on cloned yii2-starter-kit without any changes 
Look please short screen video of my issue http://i.de-v.net/1478867817.webm

**Comment by trntv** [comment]
it's weird. we don't set any return url, except those set by AccessControl...

**Comment by ztdan4ik** [comment]
Yes, I didn't found where it's setting... But also didn't found solution. For temporary solution i did like this http://i.de-v.net/1484138244.png

Did you reproduce this problem?

**Comment by XzAeRo** [comment]
I tried to reproduce the problem and is working properly.
Are you using the latest yii2-framework version?

**Comment by ztdan4ik** [comment]
Yes, I using latest yii2-framework.
And I see some difference. After logging on my local starter kit it redirecting me to profile page, but in your demo site it redirection to homepage.

**Comment by XzAeRo** [comment]
Now I could reproduce the problem.
But this looks like a problem with the framework rather than the project.

The culprit is the  [`goBack` function](https://github.com/yiisoft/yii2/blob/081ee7c5b13ba3735e8376394b1f016eb30a68e5/framework/web/Controller.php#L242). It seems that the session is not being flushed properly after logout.

**Comment by ztdan4ik** [comment]
@XzAeRo yes, that is. But i wasn't sure it framework problem or this project.

**Comment by XzAeRo** [comment]
You should leave a bug report in the [yii2 project](https://github.com/yiisoft/yii2) repo.

**Comment by ztdan4ik** [comment]
[Issue](https://github.com/yiisoft/yii2/issues/13371) in yii2 project repo

**Comment by SilverFire** [comment]
Can not reproduce neither on the local yiisoft/yii2-app-basic installation, nor on the demo installation of this started kit (https://github.com/trntv/yii2-starter-kit#demo)

**Comment by XzAeRo** [comment]
It turns out, in my case, I was able to reproduce it changing manually the `FRONTEND_URL` from the `.env` file to something different from the URL where I'm accessing the website. But even then, the behavior is erratic, and worked after some furious messing with the `.env` configuration.
