### ISSUE TITLE
config glide default image,when load a error image

### ISSUE THREAD

**Issue by awebc** [trntv/yii2-starter-kit#489]
some time. glide load a not exist image or a eeror image , then show a default image.when config the glide , can set the defualt image paththank you

**Comment by trntv** [comment]
if images not exists - 404. Your should handle 404s on client side

**Comment by awebc** [comment]
client side? how to config?

**Comment by trntv** [comment]
its up to you, depends on your js code. there ia nothing about it in starter kit
