### ISSUE TITLE
Migrations use non-standard mysql-specific syntax, so yii2-starter-kit only works with MySQL.

### ISSUE THREAD

**Issue by sentientnebula** [trntv/yii2-starter-kit#49]
This project would be much more useful if it were database agnostic, as yii itself is database agnostic.  I greatly prefer PostgreSQL over MySQL.  It would probably work with almost any database if the migrations were not written to be specific to MySQL.

**Comment by Nurpeyis** [comment]
Не работают миграции при установке на windows (openserver). 
Ошибка *** applying m140703_123803_article
    > create table {{%article_category}} ... done (time: 0.391s)
    > create table {{%article}} ... done (time: 0.352s)
    > create table {{%article_attachment}} ... done (time: 0.310s)
    > add foreign key fk_article_attachment_article: {{%article_attachment}} (article_id) references {{%article}} (id) ... done (time: 0.780s)
    > add foreign key fk_article_author: {{%article}} (created_by) references {{%user}} (id) ... done (time: 0.693s)
    > add foreign key fk_article_updater: {{%article}} (updated_by) references {{%user}} (id) ... done (time: 0.642s)
    > add foreign key fk_article_category: {{%article}} (category_id) references {{%article_category}} (id) ... done (time: 1.555s)
    > add foreign key fk_article_category_section: {{%article_category}} (parent_id) references {{%article_category}} (id) ... done (time: 1.082s)
    > create unique index idx_article_slug on {{%article}} (slug) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
The SQL being executed was: ALTER TABLE `article` ADD UNIQUE INDEX `idx_article_slug` (`slug`) (D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\db\Schema.php:633)
#0 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\db\Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `ar...')
#1 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\db\Migration.php(444): yii\db\Command->execute()
#2 D:\openserver\domains\yii2-starter-kit\common\migrations\db\m140703_123803_article.php(59): yii\db\Migration->createIndex('idx_article_slu...', '{{%article}}', 'slug', true)
#3 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\db\Migration.php(93): m140703_123803_article->safeUp()
#4 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(509): yii\db\Migration->up()
#5 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m140703_123803_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#8 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('', Array)
#10 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('', Array)
#11 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\console\Application.php(180): yii\base\Module->runAction('migrate', Array)
#12 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\console\Application.php(147): yii\console\Application->runAction('migrate', Array)
#13 D:\openserver\domains\yii2-starter-kit\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 D:\openserver\domains\yii2-starter-kit\console\yii(26): yii\base\Application->run()
#15 {main}
*** failed to apply m140703_123803_article (time: 5.838s)

**Comment by zhanglianchengdotcom** [comment]
@Nurpeyis 

From the error message: key length should <= 768bytes
uft8 = 3 byte = 1 character
255 * 3 = 765bytes < 768bytes

It works for me:

```
diff --git a/common/migrations/db/m140703_123803_article.php b/common/migrations/db/m140703_123803_article.php
index d70aee7..63a2f94 100755
--- a/common/migrations/db/m140703_123803_article.php
+++ b/common/migrations/db/m140703_123803_article.php
@@ -14,7 +14,7 @@ class m140703_123803_article extends Migration

         $this->createTable('{{%article_category}}', [
             'id' => $this->primaryKey(),
-            'slug' => $this->string(1024)->notNull(),
+            'slug' => $this->string(255)->notNull(),
             'title' => $this->string(512)->notNull(),
             'body' => $this->text(),
             'parent_id' => $this->integer(),
@@ -25,7 +25,7 @@ class m140703_123803_article extends Migration

         $this->createTable('{{%article}}', [
             'id' => $this->primaryKey(),
-            'slug' => $this->string(1024)->notNull(),
+            'slug' => $this->string(255)->notNull(),
             'title' => $this->string(512)->notNull(),
             'body' => $this->text()->notNull(),
             'view' => $this->string(),
```

**Comment by trntv** [comment]
fixed
