### ISSUE TITLE
Why composer.lock is ignored?

### ISSUE THREAD

**Issue by Lexxtor** [trntv/yii2-starter-kit#491]
Even in pre production, why?
https://github.com/trntv/yii2-starter-kit/blob/master/.gitignore#L8

**Comment by XzAeRo** [comment]
I think this was discussed before, and the reasoning is that this project is not production-ready, it's a developer good starting point to save you time, so it's up to you to fork this project and add a `composer.lock` to your own repository.

Also, it's safe to say that the `composer.json` format ensures at least some level of compatibility with the dependencies, even if you don't have a `composer.lock` file.

**Comment by trntv** [comment]
This project is a skeleton, we don't need to lock dependencies in it. If we do so, we need to update it regularly, to ensure that new projects use latest available compatible versions instead of those locked in composer.lock
