### ISSUE TITLE
symlink(): Cannot create symlink

### ISSUE THREAD

**Issue by zxczxc12** [trntv/yii2-starter-kit#493]
Windows 10 
OpenServer 5.2.2 PHP 7

if ($this->linkAssets) {
            if (!is_dir($dstDir)) {
                FileHelper::createDirectory(dirname($dstDir), $this->dirMode, true);
                symlink($src, $dstDir);
            }
        }

**Comment by XzAeRo** [comment]
This is a Yii2 Framework bug.

That code belongs to [this file](https://github.com/yiisoft/yii2/blob/master/framework/web/AssetManager.php#L520-L522), so you probably need to report an issue in their repository.

**Comment by Kharalampidi** [comment]
Run apache2 as administrator :)

**Comment by zxczxc12** [comment]
> Run apache2 as administrator :)

OpenServer already start with administrator permissions
