### ISSUE TITLE
i18n for articles

### ISSUE THREAD

**Issue by foza** [trntv/yii2-starter-kit#494]
Hi my question is how to implement i18n for **articles**?

**Comment by XzAeRo** [comment]
It has to be implemented from scratch.
There is no i18n for article, so you will have to create some database migrations, edit the models, etc.

There's a lot of job involved.

**Comment by mmx1947** [comment]
Been experimenting with this in an attempt to come up with a single article table solution. I added locale_id, source_id, and sort_order columns to article. The locale_id is populated using a locale table with the 16-character locale as the primary key. The locale table contains all of the language-country combinations I know about (including some of the longer temporary locales ISO is using in countries where multiple dialects of the same language are spoken)). I added enabled and default columns (booleans) to enable supported languages and define the default language (a unique key). The source_id column is populated using a modified adjacency list behavior where parent_id is replaced with source_id to associate each language translation record with the source language record. The sort_order column was required by the behavior. I modified the behavior to limit recursion to two levels. Still a work in progress. If anyone is doing something similar, I would appreciate any advice or recommendations.

**Comment by yanhuixie** [comment]
Content i18n
https://github.com/creocoder/yii2-translateable
https://github.com/2amigos/yii2-translateable-behavior
https://github.com/OmgDef/yii2-multilingual-behavior
https://github.com/mrs2000/yii2-multilang
https://github.com/uniqby/yii2-ar-translatable

**Comment by XzAeRo** [comment]
The only thing that bothers me about those behaviors, is that most of them stopped being maintained 2-3 years ago, so if you're suggesting using one of them, I would prefer to just make a fork and create a new project for it, or include some of that codebase directly in this project and maintain it directly.

**Comment by mmx1947** [comment]
All of those solutions probably still work because the underlying Yii2 approach to translations has not changed. Most of the solutions above follow a two table approach where common information is stored in one table with the actual translations in a second table. This gets out of hand when you have a lot of tables requiring translations so a single table solution makes better sense to me. Doing so while minimizing the number of queries and optimizing speed are the major obstacles to overcome.

**Comment by XzAeRo** [comment]
Open question, would it be possible to use the current i18n module to implement this?
