### ISSUE TITLE
Problem after Vagrant installation 

### ISSUE THREAD

**Issue by gish94** [trntv/yii2-starter-kit#495]
After vagrant installation i have this errors in http://yii2-starter-kit.dev 

Database Exception – yii\db\Exception

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
↵
Caused by: PDOException

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known

in /var/www/vendor/yiisoft/yii2/db/Connection.php at line 602
↵
Caused by: PDOException

PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known

in /var/www/vendor/yiisoft/yii2/db/Connection.php at line 602

**Comment by davidjeddy** [comment]
Check the .env, ensure the DB connection information is correct.
Log into the vagrant machine via `vagrant ssh` and ensure MySQL is running.
If yes, log into MySQL and ensure the database schema is available.
