### ISSUE TITLE
Update demo 

### ISSUE THREAD

**Issue by vladyslavstartsev** [trntv/yii2-starter-kit#496]
Frontend: http://yii2-starter-kit.terentev.net

Backend: http://backend.yii2-starter-kit.terentev.net

is not working. Can't look at it.

**Comment by davidjeddy** [comment]
<img width="1095" alt="screen shot 2016-12-11 at 10 48 01 am" src="https://cloud.githubusercontent.com/assets/6232455/21081187/5cf48826-bf8f-11e6-84b1-01a9ffb8767e.png">
<img width="1174" alt="screen shot 2016-12-11 at 10 48 22 am" src="https://cloud.githubusercontent.com/assets/6232455/21081188/5cf5c5d8-bf8f-11e6-9cc1-16278647d9a9.png">

Working once again.
