### ISSUE TITLE
Add support for front-end JavaScript Tools like Gulp

### ISSUE THREAD

**Issue by senguttuvang** [trntv/yii2-starter-kit#500]
With Bootstrap 4 being SASS only and Angular 2 being Typescript, it is important to bring modern JavaScript tooling into the starter kit to stay current. Kindly refer to the Gulp skeleton by Yii staff

https://github.com/jacmoe/yii2-app-advanced-gulp-sass

**Comment by trntv** [comment]
i'll add webpack support in a few weeks
