### ISSUE TITLE
Duplicated "LoginForm[rememberMe]" elements rendered?

### ISSUE THREAD

**Issue by yanhuixie** [trntv/yii2-starter-kit#501]
As we have suddenly noticed that the "Remember Me" function seems invalid.
We debug to Chrome and find out that Duplicated "LoginForm[rememberMe]" form element are submitted.
![image](https://cloud.githubusercontent.com/assets/1049615/21598978/7bd2aed0-d1a0-11e6-8338-f6f7cdb8384f.png)

Duplicated "LoginForm[rememberMe]" elements has rendered in HTML, one is "hidden" and the other is "checkbox".
```html
<div class="form-group field-loginform-rememberme">
<input type="hidden" name="LoginForm[rememberMe]" value="0">
<label>
	<input type="checkbox" id="loginform-rememberme" name="LoginForm[rememberMe]" value="1" checked> Remember Me
</label>
<div class="help-block"></div>
</div>
```

The login.php file seems normal, nothing strange.
```php
<?php echo $form->field($model, 'rememberMe')->checkbox() ?>
```

**Comment by trntv** [comment]
nope, the first one is a default value, it is rendered inside ``checkbox()`` call
