### ISSUE TITLE
[ENH] /js/app.js and /img/yii2-starter-kit.gif not controlled by assetManager and causing 404 during testing

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#502]
Single domain
Frontend
acceptance testing
docker container

```
[Thu Jan  5 17:55:47 2017] ::1:47438 [404]: /js/app.js - No such file or directory
[Thu Jan  5 17:55:47 2017] ::1:47440 [404]: /img/yii2-starter-kit.gif - No such file or dire
```

The above two assets need to be controlled via a assetManager to prevent the 404s in the given situation.

**Comment by trntv** [comment]
app.js registers in ``FrontendAsset``. yii2-starter-kit.gif is stored in database

**Comment by davidjeddy** [comment]
Not very systematic nor predictable given how the rest of the frontend assets are handles. Thoughts?

**Comment by davidjeddy** [comment]
Any thoughts on this? I could do a PR for it.

**Comment by davidjeddy** [comment]
Circling back to this once again. -bump-

**Comment by davidjeddy** [comment]
Thank you @trntv . I know you were not 100% on board with this idea but it is much appreciated!
