### ISSUE TITLE
Something wrong, yii2-starter-kit doesn`t work

### ISSUE THREAD

**Issue by absentrv** [trntv/yii2-starter-kit#506]
Yesterday i download starter-kit and it doesnt work.

In demo-site (http://yii2-starter-kit.terentev.net/)  doesnt work links.
If enable debug panel (i do it in vagrant + nginx) content of index-page is duplicated.

Backend http://backend.yii2-starter-kit.terentev.net/sign-in/login has redirect loop

**Comment by absentrv** [comment]
Problem in  frontend/config/web.php  and backend/config/web.php files.
For resolve this need coment row:
```php

'baseUrl' => env('FRONTEND_URL')

```

**Comment by lisonghe** [comment]
Modify the contents of .htaccess file
`RewriteRule . index.php`
`RewriteRule ^(.*)$ index.php/$1 [L]`

**Comment by trntv** [comment]
#505
