### ISSUE TITLE
Download to file storage 

### ISSUE THREAD

**Issue by gish94** [trntv/yii2-starter-kit#517]
How to download some file (from url) to file storage ?

**Comment by XzAeRo** [comment]
I have something like this:

```php
// I have a data source that comes with a JSON object with data like:
// $data => {"ean": 1234, "brand": "some text", "model": "some text", "picture":"http://domain.com/image.jpg"}

// check if I haven't downloaded an image already
if( !file_exists(Yii::getAlias('@storage/web/source/') . $product->ean . '.jpg') ) {
    // the copy method can fetch from URL or local paths
    // copy($source_file, $output_file)
    copy($data->picture, Yii::getAlias('@storage/web/source/') . $product->ean . '.jpg');

    // save the image information in database
    $product->image_base_url = Yii::getAlias('@storageUrl/source');
    $product->image_path = $product->ean.'.jpg';
}
```

The magic comes with the [PHP copy function](http://php.net/manual/en/function.copy.php). The rest is business logic and some validation.
I also suggest encapsulate everything in `try-except` blocks to prevent data source errors or filesystems errors.

Hope this helps!

**Comment by trntv** [comment]
It is not possible now without some hacks. It should be done by rewriting some login in storage kit, but it is frozen for now
