### ISSUE TITLE
Backend File Storage action Update

### ISSUE THREAD

**Issue by bonditka** [trntv/yii2-starter-kit#528]
There is update button on view "view":
```https://github.com/trntv/yii2-starter-kit/blob/master/backend/views/file-storage/view.php```, but no actionUpdate on FileStorageController:
```https://github.com/trntv/yii2-starter-kit/blob/master/backend/controllers/FileStorageController.php```

**Comment by yanhuixie** [comment]
file-storage data is generated by upload action automatically, I think there is no need to update a AUTO GENERATED record. Isn't it?

**Comment by bonditka** [comment]
I fully agree with you. I think that is good idea to remove update button from view. Only for this I opened this issue.
Thank you.
