### ISSUE TITLE
How to use file-storage kit with multiple models

### ISSUE THREAD

**Issue by dbd5** [trntv/yii2-starter-kit#531]
Hi @trntv 

The use of the file storage kit with the Articles/Article Attachment models depends on the parent child relationship between them based on article->id. (specified in the uploadbehavior as 'uploadRelation' => 'articleAttachments',)

A desirable approach in most applications is for there to be a single attachment table used by multiple models. In such a case, the attachment table, product table and other tables will store attachments in the same Attachment table. 

It appears that it may be impossible to achieve this with the file storage kit since technically you can't relate multiple parents to the same attachment table (please correct me if I am wrong)

Is there a way you can suggest for me to achieve the use of the file-storage kit with multiple parents saving uploads to the same attachment file? 

Thanks for all your work on this kit

Adam

**Comment by trntv** [comment]
you should create a relation to attachment table in all models where you are using UploadBehavior - this will do the trick.

**Comment by dbd5** [comment]
Thanks, I'll try that and let you know

**Comment by dbd5** [comment]
Yes it worked, thanks again
