### ISSUE TITLE
Storage over https

### ISSUE THREAD

**Issue by Hsidhu** [trntv/yii2-starter-kit#535]
Hello,

I am trying to install SSL certificate on Storage subdomain.
I need access to http://storage.{domain}/.well-known/acme-challenge/{filename}

I try to place that under Storage/web folder but I can't access it. I get 400 error bad request.

Could you point me to right direction.

Thanks in advance

**Comment by XzAeRo** [comment]
Hi @Hsidhu!
I just tried it, and it works fine for me.

I think this is a permission problem rather an application problem.
Make sure that the`/app/storage/web/.well-known` folder and its childs are readable by the webserver user.

Usually running `chown -R www-data:www-data /app/storage/web/.well-known` will make the data readable by the webserver, just make sure that the webserver is using the `www-data` usergroup.

Happy coding!

**Comment by Hsidhu** [comment]
Thanks for reply,
I changed permission but didn't work But when I commented out this ( RedirectMatch 403 /\..*$ ) line from storage/web/.htaccess it worked.

Thanks once again
