### ISSUE TITLE
API get no parameters when set allow to json body-raw "application/json" format

### ISSUE THREAD

**Issue by cncap** [trntv/yii2-starter-kit#539]
When using the API module, if the parameter is submitted in json format via Postman, the API gets no parameters, suggesting "Missing required parameters". Has been configured request in _frontend/config/web.php_:

`        'request' => [
            'baseUrl'=>'',
            'cookieValidationKey' => env('FRONTEND_COOKIE_VALIDATION_KEY'),
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
                'text/json' => 'yii\web\JsonParser',
            ],
        ],`

I found only accept the parameters passed in the url.
How can i configure it to work correctly? Thank you brother!

**Comment by cncap** [comment]
I think I found the reason for my problem, yii2 only $ _GET way to get the action method parameters,

**Comment by trntv** [comment]
have you sent content-type header "application/json"?
