### ISSUE TITLE
Backend - Internal Server Error

### ISSUE THREAD

**Issue by indigitale** [trntv/yii2-starter-kit#548]
Hi all,

i'm trying to install e configure the starter kit (thanks for it). In the frontend everything is ok (also the login), but when i open the backend i receive the "Internal Server Error".
Can you help me? Thanks!

**Comment by sim2github** [comment]
Catch error in `php_error.log`
```shell
➜  ~ php -i | grep error_log
```
or search log path in `phpinfo();`

**Comment by indigitale** [comment]
Ok, it was a problem with my server... thanks!
