### ISSUE TITLE
Gii

### ISSUE THREAD

**Issue by VnukA** [trntv/yii2-starter-kit#553]
Не пойму никак,что изменилось? Перестал загружать Gii. Месяц назад нормально было

18:23:19.644	trace	yii\base\Application::bootstrap	Bootstrap with yii\log\Dispatcher
18:23:19.644	trace	yii\base\Module::getModule	Loading module: gii
18:23:19.648	trace	yii\base\Application::bootstrap	Bootstrap with yii\gii\Module::bootstrap()
18:23:19.681	trace	yii\base\Module::getModule	Loading module: debug
18:23:19.708	trace	yii\base\Application::bootstrap	Bootstrap with yii\debug\Module::bootstrap()
18:23:19.714	trace	yii\base\Application::bootstrap	Bootstrap with common\components\maintenance\Maintenance::bootstrap()
**18:23:19.892	trace	yii\web\Application::handleRequest	Route requested: ''**
18:23:19.898	trace	yii\base\Controller::runAction	Route to run: site/index

Выставил 'enablePrettyUrl'=>false, и по адресу index.php?r=gii нормально загружает

**Comment by trntv** [comment]
Single domain?

**Comment by VnukA** [comment]
Yes

**Comment by davidjeddy** [comment]
# Settings
 - .env 
```
# Framework
# ---------
YII_DEBUG   = true
YII_ENV     = dev

# Application
# -----------
LINK_ASSETS=true

# Databases
# ---------
DB_DSN           = mysql:host=db;port=3306;dbname=yii2-starter-kit
DB_USERNAME      = ysk_dbu
DB_PASSWORD      = ysk_pass
DB_TABLE_PREFIX  =

TEST_DB_DSN           = mysql:host=localhost;port=3306;dbname=yii2-starter-kit-test
TEST_DB_USERNAME      = root
TEST_DB_PASSWORD      = root

# Urls
# ----
#FRONTEND_HOST_INFO    = http://yii2-starter-kit.dev
#BACKEND_HOST_INFO     = http://backend.yii2-starter-kit.dev
#STORAGE_HOST_INFO     = http://storage.yii2-starter-kit.dev

# Single domain example
# ----
FRONTEND_HOST_INFO    = http://yii2-starter-kit.dev
FRONTEND_BASE_URL     = /
BACKEND_HOST_INFO     = http://yii2-starter-kit.dev
BACKEND_BASE_URL      = /backend/web
STORAGE_HOST_INFO     = http://yii2-starter-kit.dev
STORAGE_HOST_INFO     = /storage/web


# Other
# -----
SMTP_HOST = mailcatcher
SMTP_PORT = 1025

FRONTEND_COOKIE_VALIDATION_KEY = <generated_key>
BACKEND_COOKIE_VALIDATION_KEY = <generated_key>

ADMIN_EMAIL    = admin@yii2-starter-kit.dev
ROBOT_EMAIL    = robot@yii2-starter-kit.dev

GITHUB_CLIENT_ID = your-client-id
GITHUB_CLIENT_SECRET = your-client-secret

GLIDE_SIGN_KEY = <generated_key>
GLIDE_MAX_IMAGE_SIZE = 4000000

# To resolve "Invalid volumes",For Toolbox. (https://github.com/docker/toolbox/issues/607)
COMPOSE_CONVERT_WINDOWS_PATHS=1
```

# Commands used to install:

```
docker-compose up --build --force-recreate
docker exec -it yii2starterkit_app_1 bash
wget https://getcomposer.org/composer.phar - O composer.phar
php composer.phar install --ansi --profile --prefer-dist -o -vvv
php ./console/yii app/setup --interactive=0
```

 - On the host machine used `docker network inspect bridge` to get the web servers IP.
```
            "551293ff02fadc31c8e53731032284445f12759f0c4d0a5ffe535a0890f62274": {
                "Name": "yii2starterkit_nginx_1",
                "EndpointID": "472dcefe3c0efc028d2977f7c5e2bf8f42eba6960e59afe676eaa88eb063b6bb",
                "MacAddress": "02:42:ac:11:00:06",
                "IPv4Address": "172.17.0.6/16",
                "IPv6Address": ""
            },
```

 - Visited IP in browser:
![image](https://user-images.githubusercontent.com/6232455/33410732-a14adf30-d54f-11e7-92c1-56f439f30c9a.png)


Unable to duplicate issue. If it continues please provide further setup / configuration so we can try to trouble shoot the issue.
