### ISSUE TITLE
how to extend to add description textfield

### ISSUE THREAD

**Issue by leejosh** [trntv/yii2-starter-kit#554]
How would i extend the filekit extension  to add a description textfield and use the "order" fields?

**Comment by davidjeddy** [comment]
Fork the repo, add your logic, replace original filekit package with your forked one. composer install.

**Comment by yanhuixie** [comment]
Hi @davidjeddy , thanks for your tips. I'd like to know how to "replace original filekit package with your forked one", could you add more details?

**Comment by yanhuixie** [comment]
Oh, @davidjeddy , I think you mean https://getcomposer.org/doc/05-repositories.md#vcs ?

**Comment by davidjeddy** [comment]
@yanhuixie That is one way, adding a VCS. To clarify I mean adding your package to [packagist](https://packagist.org) and using composer to handle dependency management. Either way would solve the request.
