### ISSUE TITLE
ENH: Support emoji in MySQL/Maria DB schema's.

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#556]
By default ./common/config/base.php -> components['db']['charset'] is set to utf8. Under MySQL/Maria database schema's this does not fully support the UTF8 character set. `utf8mb4` is required for such support.

**Recommendation**:
DB connection string / migrations should append `mb4` to the utf8 string when using MySQL/Maria

**References**:
[https://mathiasbynens.be/notes/mysql-utf8mb4#utf8-to-utf8mb4](https://mathiasbynens.be/notes/mysql-utf8mb4#utf8-to-utf8mb4)

[Postgres does support 4 byte character sets](https://www.postgresql.org/docs/9.3/static/multibyte.html)

**Comment by sinfuljosh** [comment]
This also requires verifying the length's of some columns. 

see the section in the above link titled "Step 4: Check the maximum length of columns and index keys".

**Comment by davidjeddy** [comment]
Working on this now. https://github.com/davidjeddy/yii2-starter-kit/tree/alter_mysql_to_be_mb4

Anyone know of Yii2's ARE can alter Schema level values? This is my current hang up...

**Comment by VINTproYKT** [comment]
Thank you! 😄 We definitely need Yii2 Starter Kit to support utf8mb4, because it went to be common thing when people communicate with emoji. And only limitation, surely, is 2 bytes character set.

**Comment by davidjeddy** [comment]
@VINTproYKT Glad to help, only waiting for a CI/CD fix and this should merge right in.

**Comment by VINTproYKT** [comment]
There is one small problem: your migration doesn't affect configuration at `common/config/base.php` to (changing `charset` value to `utf8mb4`).

**Comment by davidjeddy** [comment]
@vintproykt updated PR https://github.com/trntv/yii2-starter-kit/pull/574 with recommendations.

**Comment by vintproykt** [comment]
[It's not what I did mean.](/trntv/yii2-starter-kit/pull/574/files#r149743443)

We need a way to set this only for MySQL users, ya know. 😉

However they should set it for their behalf, if they run your migration script. Eventually, developer may not need to update his database's collation and charset. This is a voluntary process, after all.

**Comment by davidjeddy** [comment]
Oooooo, gotcha. IF the mb4 migration runs, updated the configuration. I can do that when I get in on Monday. That change will correct PR #574 as well.
