### ISSUE TITLE
yii2-queue integration

### ISSUE THREAD

**Issue by trntv** [trntv/yii2-starter-kit#560]
Integrate https://github.com/yiisoft/yii2-queue

**Comment by davidjeddy** [comment]
@trntv which queue service would you want to use as an example? IMO I think RabbitMQ would be the more popular option?

Note: Redis might be more popular but is not a dedicated Queueing service.

**Comment by XzAeRo** [comment]
@davidjeddy I would suggest Redis, specially since the project could take advantage of the caching service that Redis also offers.

**Comment by trntv** [comment]
filesystem based queue would be enough i think

**Comment by davidjeddy** [comment]
@XzAeRo Would this solve the request? https://github.com/yiisoft/yii2-queue If so I can add it to the starter kit.

**Comment by XzAeRo** [comment]
I think so.

Filesystem based queue should be enough. Maybe we can leave some documentation explaining that the queue can use different drivers.

**Comment by davidjeddy** [comment]
Implemented via https://github.com/trntv/yii2-starter-kit/pull/582
