### ISSUE TITLE
init file

### ISSUE THREAD

**Issue by romanshul** [trntv/yii2-starter-kit#564]
Why doesn't exist init file? Can I use it from official distribution?
Or how can I change environments?

**Comment by davidjeddy** [comment]
Please clarify, what would you expect *.init to do?

**Comment by romanshul** [comment]
to init command for working with environments

**Comment by davidjeddy** [comment]
Do you mean to start a VM or container services?

https://github.com/trntv/yii2-starter-kit/blob/master/docs/installation.md contains directions for both Vagrant and Docker installations. Is it lacking direction? Admittedly the documentation for the project does need more information.

**Comment by romanshul** [comment]
I meant the "container" like in official distribution now

**Comment by davidjeddy** [comment]
@romanshul Ah, we all good now then; shall we close this ticket now?
