### ISSUE TITLE
real-time notifications?

### ISSUE THREAD

**Issue by Pedro25** [trntv/yii2-starter-kit#565]
With what tool, or how can I get log notifications to be loaded in real time? Thank you.

**Comment by davidjeddy** [comment]
@Pedro25 using terminal read the web server's access and error logs. `tail -f ./{path}` is a good start.

**Comment by Pedro25** [comment]
@davidjeddy thanks for the contribution, but I refer more to this:

![screenshot_1](https://user-images.githubusercontent.com/11860409/32529658-1473bc62-c410-11e7-9b61-47b2132bd0d5.png)

How can I upload these notifications in real time?

**Comment by davidjeddy** [comment]
@Pedro25 Ah, ok. To change those using a combination of JS ajax calls and dom element replacing. Example process: Every 30s ajax call an API, the response payload would container counters to indicate the new values. Using JS/et al updated the elements that contain the number images.

**Comment by Pedro25** [comment]
@davidjeddy Would you give me an example or a link to know where to start?
