### ISSUE TITLE
Unable to find 'app\controllers\ArticleCategoryController' in backend\yii

### ISSUE THREAD

**Issue by alfredleo** [trntv/yii2-starter-kit#567]
Exception 'yii\base\UnknownClassException' with message 'Unable to find 'app\controllers\ArticleCategoryController' in file: C:\wamp64\www\wiserico\wiserico\backend/controllers/ArticleCategoryController.php. Namespace missing?'

This error i get when run backend\yii.
ArticleCategoryController has a namespace backend\controllers.
This same problem applies to frontend\yii

**Comment by XzAeRo** [comment]
hmmm, I don't have this problem.

Are you using a clean version of the project? Make sure you didn't make any modification.

**Comment by alfredleo** [comment]
Yep, that was misconfiguration problem.
