### ISSUE TITLE
Imperavi radactor misbehave on copy paste. Should use .length in JQuery instead of .size()

### ISSUE THREAD

**Issue by alfredleo** [trntv/yii2-starter-kit#587]
We have a problem of using .size() instead of .length in redactor.js. This bug comes when we upgrade for jquery 3.2+ (since yii 2.0.13).

Here is the solution. It should be merged then we can get rid of this error. While it is not merged just change redactor.js file with the correct one in vendor/asofter/yii2-imperavi-redactor/yii/imperavi/assets/redactor.js
https://github.com/asofter/yii2-imperavi-redactor/pull/64/commits/0b9756201908ff698c802ee63889017e2950fc39
This is a dead project. We can look at https://github.com/vova07/yii2-imperavi-widget. They have already fixed this. If it is fine, we could use this instead of dead.

**Comment by alfredleo** [comment]
@trntv Please take a look at this. I am not sure if they are compatible.

**Comment by trntv** [comment]
Sometime we'll switch everything to vova07/yii2-imperavi-widget but at the time being asofter has fixed his widget
