### ISSUE TITLE
[Suggestion]You may end the HEAD method call in Maintenance to avoid unnecessary cache flow

### ISSUE THREAD

**Issue by yanhuixie** [trntv/yii2-starter-kit#591]
We have noticed that there is a continuous data flow about 1Mbps between a y2sk node and redis cache server which seems caused by haproxy httpcheck HEAD call. After some digs we found out that it just obtaining two cache items, "maintenance status" and "url rule". Because the haproxy httpcheck ticks per second, so it causes the continuous 1Mbps data flow. Suppose we have 100 y2sk nodes, it may cause 100Mbps unnecessary data flow which may makes a big pressure to redis server, right? So we decided to deal with it. We have just add lines of code to the common\components\maintenance\Maintenance->bootstrap() and now it looks working fine.
``` php
    public function bootstrap($app)
    {
        $verb = Yii::$app->getRequest()->getMethod();
        if(strtoupper($verb) == "HEAD"){
            Yii::$app->end(); //avoid unnecessary cache accessing. @yanhuixie
        }
        
        if ($this->enabled instanceof \Closure) {
            $enabled = call_user_func($this->enabled, $app);
        } else {
            $enabled = $this->enabled;
        }
        if ($enabled) {
            $this->maintenanceText = $this->maintenanceText ?: Yii::t('common', 'Dear users, we are performing routine update maintenance tasks. Depending on the update workload, it may take a few minutes to a few hours. Please visit again later. Thank you.');
            if ($this->catchAllRoute === null) {
                $app->controllerMap['maintenance'] = [
                    'class' => 'common\components\maintenance\controllers\MaintenanceController',
                    'retryAfter' => $this->retryAfter,
                    'maintenanceLayout' => $this->maintenanceLayout,
                    'maintenanceView' => $this->maintenanceView,
                    'maintenanceText' => $this->maintenanceText
                ];
                $app->catchAll = ['maintenance/index'];
                Yii::$app->view->registerAssetBundle(MaintenanceAsset::className());
            } else {
                $app->catchAll = [
                    $this->catchAllRoute,
                    'retryAfter' => $this->retryAfter,
                    'maintenanceText' => $this->maintenanceText
                ];
            }
        }
    }
```
![jff phqz8e vjm8 vw 0q](https://user-images.githubusercontent.com/1049615/33925813-8740fecc-e016-11e7-8146-b1b2476428d5.png)

**Comment by trntv** [comment]
Your workaround will break all HEAD requests to your application. As for me, it would be much better to set maintenance status manually in config, eg
```
'maintenance' => [
            'class' => 'common\components\maintenance\Maintenance',
            'enabled' => false
],
```
or set it in environment
 ```
'maintenance' => [
            'class' => 'common\components\maintenance\Maintenance',
            'enabled' => env('APP_MAINTENACE', 0) === '1'
],
```
thank you for use case, i'll change it to respect env variables by default

**Comment by yanhuixie** [comment]
Thanks reply, @trntv . In fact this issue is not related to the MAINTENANCE function itself, but just the "block HEAD request in the BOOTSTRAP moment". In our case, only the haproxy httpchk will use HEAD request, so we can block ALL the HEAD request. 

Our original purpose is to avoid the unnecessary CACHE access flow that caused by haproxy, even if turn on the MAINTENANCE mode, it still wasting the cache network access, isn't it?

**Comment by trntv** [comment]
it wouldn't if you'll block it by config rather than by KeyStorage value. I understand your concerns but see no way except using local file cache to avoid unnecessary network flow
