### ISSUE TITLE
Change development domain from .dev to .lcl

### ISSUE THREAD

**Issue by davidjeddy** [trntv/yii2-starter-kit#592]
As per ICANN's move to add .dev as a TLD and Chromes push to require SSL for .dev domains I would like to recommend we move to using .lcl (short for local) as the development TLD. Thoughts?

**Comment by alfredleo** [comment]
I vote for it. Yesterday lost several hours on finding out why chrome redirect local api.dev to https. While IE worked fine. I even cleared all chrome cache but that did not help either.
Possible candidates are .lcl .loc .test . IMHO lcl is hard to distinguish.

**Comment by davidjeddy** [comment]
@alfredleo Does .localhost redirect to 127.0.0.1 w/o a edit to the OS's host file? Specifically Win, OSX, and Debian?

**Comment by alfredleo** [comment]
No it is not yet. This is a suggestion to make it automatic in all oses.

**Comment by XzAeRo** [comment]
What about `.local`?

**Comment by davidjeddy** [comment]
@XzAeRo My personal opinion is to keep TLD's to 3 characters; though I ICANN now has multiple gTLDs that are longer. The traditional ones (com, gov, net, org) are 3. I would not be against .local though. @trntv opinion?

**Comment by trntv** [comment]
``.local`` will cause problems for those who uses some local dns resolvers, dnsmasq for example.

**Comment by trntv** [comment]
As i can see, there are proposals to standardize ``.localhost`` and ``.test`` domains for such purposes - https://tools.ietf.org/html/draft-west-let-localhost-be-localhost-06
imho ``.localhost`` is long but explicit and unambiguous

**Comment by alfredleo** [comment]
There is another problem with suggested ones. We can not use them on oauth authorization if they are not real TLD. So you can not set this domain for google plus authorization. It errors with "Invalid Redirect: http://api.test/user/sign-in/oauth?authclient=google must end with a public top-level domain (such as .com or .org)". So loc, test, localhost and so on won't work. I checked TLDs that look like 'localhost'. So some suggestions are: lc (Saint Lucia) and lol. [https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#G_2](TLD)
.lol is not a country TLD, .lc is short and looks like a localhost

**Comment by XzAeRo** [comment]
And all of this fucking problems because of an stupid decision from the Chrome team... (it already made me switch to Firefox anyway).

On another note, I really like the **.lc** domain. But, as @trntv said, it lacks the unambiguous nature of other domains.

**Comment by davidjeddy** [comment]
Seems the TLD issue will not be easily resolved; between the browser vendors, the project, and the IETF. Perhaps we should look at this from a different direction: generate a self signed SSL server for the project so https works?

IMO `security first` is a valid principle. This would instill the practice of having a SSL cert from development to production in the user space.

https://letsencrypt.org/ + .dev + local docker tooling could make the process transparent to the repository users.

**Comment by trntv** [comment]
letsencrypt can't be used with not valid TLDs. Sadly, there is no simple way to use https locally.

**Comment by trntv** [comment]
so, lets try .localhost for now. we can change it anytime later.

**Comment by davidjeddy** [comment]
LetsEncrypt can be done locally (at least using container services):

- https://spin.atomicobject.com/2017/10/28/local-https-docker/
- https://medium.com/@nh3500/how-to-create-self-assigned-ssl-for-local-docker-based-lamp-dev-environment-on-macos-sierra-ab606a27ba8a
- https://deliciousbrains.com/https-locally-without-browser-privacy-errors/

Do we still wish to proceed with the local domain change w/o SSL certification? @trntv

**Comment by mehrna** [comment]
How about `.devel` ?
