### ISSUE TITLE
Is better to return 200 (but not 5xx) status code while in maintenance mode?

### ISSUE THREAD

**Issue by yanhuixie** [trntv/yii2-starter-kit#597]
If we run y2sk application in a cluster, we need a load balancer to manage the frontend traffic, for example Haproxy.
Haproxy has an inner function that named httpchk to monitor the application health status. Any time when the 5xx status code is returned, haproxy will consider that "the service is DOWN", and raise a warning to the administrator. The worst thing is that the backend application will also be treated as DOWN at the same time, it means the whole CLUSTER is DOWN.
So, is better to return 200 status code while y2sk running in maintenance mode?

**Comment by trntv** [comment]
503 is a standard status for such cases. Load balancer need to know that server is unavailable to mark it unhealthy and route traffic to other instances. I could move status code to config and leave 503 as a default

**Comment by trntv** [comment]
https://github.com/trntv/yii2-starter-kit/commit/9fd52e13affa21e9a06b2feea9e60e3d630cf8ce
