### ISSUE TITLE
Issues with Bower Dependencies

### ISSUE THREAD

**Issue by XzAeRo** [trntv/yii2-starter-kit#603]
While trying to run `composer update`, I'm getting this error:

```
[Composer\Repository\InvalidRepositoryException]
  No valid bower.json was found in any branch or tag of https://github.com/DmitryBaranovskiy/eve.git, could not load a package from it.
```

It turns out that project comes from one of the dependencies from bower assets (I'm not sure which).

Maybe it's a good time to move away from bower and start using NPM assets?

ps: I'm using the latest master version

**Update:** I removed the `https://asset-packagist.org` composer repository, and instead used the old asset plugin to run the update, and everything ran correctly. It seems like this is an issue with `https://asset-packagist.org` packages.

**Comment by trntv** [comment]
i'll switch assets to npm versions

**Comment by absentrv** [comment]
1) I have removed `fxp/composer-asset-plugin` and everything work
OR
2) In composer.json file add this config section:
`"config": {
    "process-timeout": 1800,
         "fxp-asset": {
            "enabled": false
        }
  },`
