### ISSUE TITLE
Prepare for Yii 2.1

### ISSUE THREAD

**Issue by trntv** [trntv/yii2-starter-kit#611]
- Replace `::className()` calls with `::class` (if you’re running PHP 5.5+).
- Replace usages of `yii\base\InvalidParamException` with `yii\base\InvalidArgumentException`.

**Comment by davidjeddy** [comment]
@trntv If this is not completed yet I am willing to assist with this.

**Comment by trntv** [comment]
We'll need to update everything when new Yii released. Closing so far
