### ISSUE TITLE
Demo is not working

### ISSUE THREAD

**Issue by remizyaka** [trntv/yii2-starter-kit#624]
Database exception on demo  site
`SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known`

**Comment by gantal** [comment]
Set the database host name and resolve it.

**Comment by remizyaka** [comment]
I mean these demo sites 
```
Demo is hosted by awesome Digital Ocean

    Frontend: http://yii2-starter-kit.terentev.net
    Backend: http://backend.yii2-starter-kit.terentev.net
```
and not my local env

**Comment by davidjeddy** [comment]
<img width="877" alt="screen shot 2018-05-06 at 8 11 14 pm" src="https://user-images.githubusercontent.com/6232455/39679322-a4e01066-5169-11e8-859a-d63dc4eca69c.png">
