### ISSUE TITLE
backend/web/content/page/index

### ISSUE THREAD

**Issue by JeKaCompaS** [trntv/yii2-starter-kit#628]
Hi!
I have some error on backend/web/content/page/index uri
Error: Class 'backend\models\search\PageSearch' not found in /app/backend/modules/content/controllers/PageController.php:42
Stack trace:
#0 [internal function]: backend\modules\content\controllers\PageController->actionIndex()
#1 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#2 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#3 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('index', Array)
#4 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('content/page/in...', Array)
#5 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#6 /app/backend/web/index.php(23): yii\base\Application->run()
#7 {main}

Server:
ubuntu 16.04
Docker version 18.03.1-ce, build 9ee9f40
docker-compose version 1.21.2, build a133471
Composer version 1.6.5 2018-05-04 11:44:59
Yii2-starter-kit at 23.05.2018
Nginx and .env config to single-domain mode

**Comment by trntv** [comment]
already fixed
