### ISSUE TITLE
Ошибка в карусели (\common\widgets\DbCarousel)

### ISSUE THREAD

**Issue by sircovsw** [trntv/yii2-starter-kit#629]
Если добавить в карусель еще один слайд, то возникает ошибка вида
"The file or directory to be published does not exist: 1/OwkHUSZVPrSA4EHuKSyCQ5DHKTGXncUE.jpg"
Повторил на вашем демо-сайте:
http://yii2-starter-kit.terentev.net/
Добавил сюда: http://backend.yii2-starter-kit.terentev.net/widget/carousel-item/update?id=2

**Comment by dirzhov** [comment]
фиксится в DbCarousel строка на $url = Yii::$app->assetManager->publish(\Yii::$app->glide->sourcePath.'/'.$item->path);
