### ISSUE TITLE
Default database collations should be UTF-8

### ISSUE THREAD

**Issue by deanpress** [trntv/yii2-starter-kit#634]
Special characters cannot be used for user fields, unless the collations are set to UTF-8 manually (e.g. for `first_name` etc).

**Comment by davidjeddy** [comment]
Full UTF-8 support has been discussed at length. Please see the following:

- https://github.com/trntv/yii2-starter-kit/pull/574
- https://github.com/trntv/yii2-starter-kit/pull/596
