### ISSUE TITLE
Error yii\web\HttpException:403 on login into backend

### ISSUE THREAD

**Issue by satik-kz** [trntv/yii2-starter-kit#635]
Login pages shows correctly, but when I try to login into it with "webmaster:webmaster", "manager:manager" or "user:user" it throws yii\web\HttpException:403. 

Debugger:
exception 'yii\web\ForbiddenHttpException' in E:\xampp\htdocs\nk2\backend\models\LoginForm.php:77
Stack trace:
#0 E:\xampp\htdocs\nk2\backend\controllers\SignInController.php(66): backend\models\LoginForm->login()
#1 [internal function]: backend\controllers\SignInController->actionLogin()
#2 E:\xampp\htdocs\nk2\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#3 E:\xampp\htdocs\nk2\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#4 E:\xampp\htdocs\nk2\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('login', Array)
#5 E:\xampp\htdocs\nk2\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('sign-in/login', Array)
#6 E:\xampp\htdocs\nk2\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#7 E:\xampp\htdocs\nk2\backend\web\index.php(23): yii\base\Application->run()
#8 {main}

**Comment by kudzuu** [comment]
Did you execute `console/yii app/setup` ?
