### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by trntv** [trntv/yii2-starter-kit#72]

**Comment by Beaten-Sect0r** [comment]
_http://www.class.pm/files/jquery/classycountdown/ , _https://github.com/wimbarelds/TimeCircles - имхо годные штуки для Maintenance Mode.

**Comment by trntv** [comment]
Возможно, но чаще всего не особо-то и нужны когда надо просто отключить сайт ненадолго. Так что, я планирую сделать поведение которое будет отдавать просто выводить вьюху, а с ней уже можно делать кому что надо.
