### ISSUE TITLE
Refactor ActiveRecord queries with DISTINCT

### ISSUE THREAD

**Issue by battika** [trntv/yii2-starter-kit#73]
Thank you for this useful project.

I've just found a possible area for improvement regarding the queries using the DISTINCT keyword.

In the file \backend\views\file-storage\index.php the following line
```php
  FileStorageItem::find()->select('DISTINCT `repository`')->all(), 'repository', 'repository'
```
should be replaced with
```php
FileStorageItem::find()->select('repository')->distinct()->all(), 'repository', 'repository'
```

This should be more ActiveRecord flavoured and more compatible with databases other than MySQL (I'm using Postgres).

The same applies to the file \backend\modules\i18n\views\i18n-message\index.php where the following lines

```php
\backend\modules\i18n\models\I18nMessage::find()->select('DISTINCT `language`')->all(),
and
\backend\modules\i18n\models\I18nSourceMessage::find()->select('DISTINCT `category`')->all(),
```
should be replaced with

```php
\backend\modules\i18n\models\I18nMessage::find()->select('language')->distinct()->all(),
and
\backend\modules\i18n\models\I18nSourceMessage::find()->select('category')->distinct()->all(),
```

There might be few more occasions I did not spot.

**Comment by trntv** [comment]
Thank for your interest :)

**Comment by battika** [comment]
Thank you

**Comment by skrsingh1994** [comment]
thank you

**Comment by rahulbabakatalpur** [comment]
thank you
ArrayHelper::map(urmodels::find()->all(), 'license_type','license_type')

**Comment by rahulbabakatalpur** [comment]
thank you
