### ISSUE TITLE
Frontend: Failed to set unsafe attribute 'password' 

### ISSUE THREAD

**Issue by TimNZ** [trntv/yii2-starter-kit#85]
I'm getting this when trying to change a signed in account password from Frontend.
Adding this to rules() in frontend/modules/user/models/AccountForm.php fixes it.

['password', 'string'],

I'm a complete newbie to Yii2 (in fact a PHP novice) so only a cursory look at Model.php, I'm thinking safeAttributes() requires an explicit definition.

Yii 2.0.1

16	01:31:01.503	trace	yii\web\UrlManager::parseRequest	No matching URL rules. Using default URL parsing logic.
17	01:31:01.503	trace	yii\web\Application::handleRequest	Route requested: 'user/default/index'
18	01:31:01.503	trace	yii\base\Module::getModule	Loading module: user
19	01:31:01.504	trace	yii\base\Controller::runAction	Route to run: user/default/index
20	01:31:01.504	trace	yii\base\InlineAction::runWithParams	Running action: frontend\modules\user\controllers\DefaultController::actionIndex()
21	01:31:01.505	trace	yii\base\Model::onUnsafeAttribute	Failed to set unsafe attribute 'password' in 'frontend\modules\user\models\AccountForm'.
/Users/timshnaider/Desktop/Development/Projects/xemware/CustomerProjects/X/Y/yii2-starter-kit/frontend/modules/user/controllers/DefaultController.php (46)

**Comment by trntv** [comment]
very strange how can i miss such an obvious thing :-)

**Comment by TimNZ** [comment]
Thanks for the quick fix!

Great starting framework, you've saved me a lot of time.

**Comment by trntv** [comment]
This is the point :-)
