### ISSUE TITLE
Change language in Admin Panel

### ISSUE THREAD

**Issue by svolga** [trntv/yii2-starter-kit#94]
By default admin panel uses English language. How to switch the admin panel in Russian?

**Comment by svolga** [comment]
Разобрался. Поменял в base.php

**Comment by userlond** [comment]
You may change language in your account settings:
<backend_path>/sign-in/profile

**Comment by trntv** [comment]
> You may change language in your account settings:
backend_path/sign-in/profile

This will change locale in frontend too, but i think this is a VERY rare case when you may need different languages in fronend and backend.

**Comment by trntv** [comment]
@userlond thanks for help
