### ISSUE TITLE
Upload image error with message file_put_contents(/tmp/.dirindex)

### ISSUE THREAD

**Issue by RooneyTu** [trntv/yii2-starter-kit#99]
Error log:
exception 'yii\base\ErrorException' with message 'file_put_contents(/tmp/.dirindex): failed to open stream: No such file or directory' in \www\yii2-starter-kit\vendor\trntv\yii2-file-kit\storage\repository\FilesystemRepository.php:80

Please help me to solve this problem.

**Comment by trntv** [comment]
sorry, my fault. i've added this to repository by mistake...
